### ISSUE TITLE
Add a repository description

### ISSUE THREAD

**Issue by kkomelin** [charliekassel/vuejs-datepicker#10]
I have just sent your project to the Awesome Vue list https://github.com/vuejs/awesome-vue/pull/349
so it would be good if you add a description to the repository. It will help people to find it.

My suggestion is:
> A simple date picker component for Vue.js with inline mode support

I mentioned inline mode here because I did not find it in any other similar projects.

**Comment by charliekassel** [comment]
That's awesome! thanks @kkomelin 
package.json description already exists but I've updated in 4ebeadc

**Comment by kkomelin** [comment]
Cool. Thanks.

**Comment by kkomelin** [comment]
@charliekassel Could you please to add the description from package.json to the repo description (at the top of the page https://github.com/charliekassel/vuejs-datepicker)?
Now it says:
> No description or website provided.

**Comment by charliekassel** [comment]
Got it! OK, done.

**Comment by kkomelin** [comment]
I'am happy now ) Thanks.
