### ISSUE TITLE
Restricting this month's date's shows current month when opening

### ISSUE THREAD

**Issue by garygreen** [charliekassel/vuejs-datepicker#101]
If you disable all dates in Feb and that's the current month.... it'll open to show Feb. Shouldn't it default to the min selectable month's view ?

![date restriction](https://cloud.githubusercontent.com/assets/1702638/23368875/3a1f23aa-fd07-11e6-890f-87b9a70e3a98.gif)

**Comment by charliekassel** [comment]
That's a good point, well spotted @garygreen 
I will take a look when I have time, or am happy to look at a PR if this is a blocker for you.

**Comment by charliekassel** [comment]
On reflection I think this should be the correct behaviour.

**Comment by garygreen** [comment]
Eh? How could it possibly be the correct behaviour? You can't navigate back to the disabled dates... so why should it show the disabled dates that you can't do anything with?

**Comment by charliekassel** [comment]
Well if all dates are disabled there's no point in being able to navigate backwards.
I can see your point but I don't feel strongly enough about it to spend time on it.

I'm still happy to look at a PR if you want to submit one.
