### ISSUE TITLE
Programmatically opening the datepicker

### ISSUE THREAD

**Issue by zawilliams** [charliekassel/vuejs-datepicker#105]
Is there a way of programmatically opening the datepicker?

I was trying to call the component by adding `ref="myComponent"` and then calling it from the parent like `this.$refs.myComponent.showCalendar()` but that doesn't seem to work.

**Comment by charliekassel** [comment]
Have you managed to do this?
It works in the tests:
https://github.com/charliekassel/vuejs-datepicker/blob/master/test/specs/Datepicker.spec.js#L116-L123

**Comment by zawilliams** [comment]
Hey @charliekassel,

I ended up using a different picker for different reasons, but if I do use this one again, I'll be sure to reference this. Thanks!

**Comment by enkay** [comment]
I can't seem to get this to work either.

Same setup as @zawilliams, any idea what could be the issue?

**Comment by jericopulvera** [comment]
@charliekassel I can't seem to get this to work either.

@zawilliams what picker did you use?

**Comment by rcheung9** [comment]
@charliekassel I can't seem to get this to work either.

**Comment by zawilliams** [comment]
I ended up using the date picker from [Buefy](https://buefy.github.io/) but modified the UI pretty heavily.

**Comment by charliekassel** [comment]
This is an issue tracker guys, not a forum.
