### ISSUE TITLE
how can i click a button popup datepicker panel?

### ISSUE THREAD

**Issue by RunningV** [charliekassel/vuejs-datepicker#106]
i want to click a button then popup the datepicker from the bottom, but ur datepicker default datepicker>input focus then show the datepicker panel, hwo can i use it to satisfy my purpose?

**Comment by charliekassel** [comment]
You should be able to call the showDayCalendar() method as you can see in the tests:
https://github.com/charliekassel/vuejs-datepicker/blob/master/test/specs/Datepicker.spec.js#L116-L123
