### ISSUE TITLE
Disable all dates other than those highlighted

### ISSUE THREAD

**Issue by andrewdelprete** [charliekassel/vuejs-datepicker#108]
Hi there, is there a way to disable all dates by default and only highlight a selected few for appointments? Right now I'd have to specify every date this year as disabled other than the ones I want for appointments. Thanks!

**Comment by charliekassel** [comment]
Currently there isn't I'm afraid.

I can see your use case though so am happy to look at a PR for this.

**Comment by JakeDK** [comment]
I could really need this functionality aswell :)

**Comment by mcsystemen** [comment]
Hi, I'm wondering if there's already a solution for this?
