### ISSUE TITLE
Styles are not scoped

### ISSUE THREAD

**Issue by bencodezen** [charliekassel/vuejs-datepicker#110]
The styles are generically named and happened to conflict with my project since it uses the `calendar` class. I would suggest prefixing all the root styles with something like vueDp in order to minimize possible conflict.

PS. Would be happy to help contribute this fix if you want some collaboration on this.

**Comment by maxKimoby** [comment]
Scoping style would make customization of the date-picker's style impossible. IMO it is preferable to change your own class name.

**Comment by bencodezen** [comment]
That's the approach I certainly would have taken, but I'm working with a legacy codebase where that's not an option. 

In my experience, it's standard to at least prefix things like CSS for plugins with a specific name in order to minimize side effects across other people's sites. Then you get the best of both worlds as far as customization as well as "scoped" styles.

**Comment by charliekassel** [comment]
I'm definitely more open to adding a prefixed namespace to internal css classes rather than the Vue scoped property.
