### ISSUE TITLE
Clear-button property should be inside the input element (preferably to the right)

### ISSUE THREAD

**Issue by orhdoga** [charliekassel/vuejs-datepicker#113]
Forgive me if this already was possible..

Right now: 

![clear-button](https://cloud.githubusercontent.com/assets/22965420/24083142/48659d4c-0cd2-11e7-86d8-2af977c5d921.JPG)

PS: maybe also give it some styling (e.g. height and width).

**Comment by charliekassel** [comment]
Styling the clear button inside the input element requires knowledge of the width of the input.
I'm trying to keep the datepicker non opinionated as much as possible in terms of styling.

In your example the input is set to 100% width so pushing the clear button to the next line.

**Comment by ehvetsi** [comment]
Hi, 

I have created this PR [https://github.com/charliekassel/vuejs-datepicker/pull/336](url) that resolve this issue,

I'm verifying if is using bootstrap and set the clear button inside input.

Take a look.

Expected help you
