### ISSUE TITLE
Clear button customisation

### ISSUE THREAD

**Issue by garygreen** [charliekassel/vuejs-datepicker#117]
It would be nice to be able to customise the clear button to...

* Hide the clear icon if there isn't a date selected (makes no sense to have it visible in such a case)
* Customise the icon / text used in the icon, in case you want to use font awesome or easier css styling.

**Comment by charliekassel** [comment]
I'm hiding the clear button from v0.7.9

Re: customisation. You can always target the css class `vdp-datepicker__clear-button`
Happy to review a PR if you have other needs.
