### ISSUE TITLE
on:selected get previous selected value

### ISSUE THREAD

**Issue by WJWang** [charliekassel/vuejs-datepicker#119]
Hi, I got some problems when I use the on:selected  to passing data to parent component. Here is my code snippet. When I use on:selected to execute the setBeginDate / setEndDate, I will get the previous selected date. Did I do anything wrong?
```
<template lang="html">
    <div>
          <datepicker v-model="beginDate" v-on:selected="setBeginDate" format="yyyy-MM-dd" input-class="datepicker-input" wrapper-class="datepicker-wrapper" :clear-button='true'></datepicker>
            <datepicker v-model="endDate" v-on:selected="setEndDate" format="yyyy-MM-dd" input-class="datepicker-input" wrapper-class="datepicker-wrapper" :clear-button='true'></datepicker>
    </div>
</template>

<script>
import Datepicker from 'vuejs-datepicker';

export default {
    data() {
        return {
            beginDate: new Date(),
            endDate: new Date(),
        };
    },
    components: {
        datepicker: Datepicker,
    },
    methods: {
        setBeginDate() {
            console.log(this.beginDate); // always get the previous selected beginDate date
            this.$parent.dateListener(this.beginDate);
        },
        setEndDate() {
            console.log(this.endDate); // always get the previous selected endDate date
            this.$parent.dateListener(null, this.endDate);
        }
    }
}
</script>
```

**Comment by JeanBarriere** [comment]
I had a similar problem.
To fix it, I use `watch` property to listen on data change.
Here you can do:
```javascript
watch: {
  beginDate: function(val) {
    // do whatever you want with the new value
  },
  ...
}
```
and it would works for you.

**Comment by WJWang** [comment]
@JeanBarriere Thanks a a lot, it did work.
However, do you know what cause the on:selected problem?

**Comment by JeanBarriere** [comment]
@WJWang I do not know, that's why I use this instead of the selected prop.

**Comment by romines** [comment]
This can also be fixed with `Vue.next(cb)`, so I'm assuming it has something to do with the digest cycle

**Comment by 07061999** [comment]
> @JeanBarriere Thanks a a lot, it did work.
> However, do you know what cause the on:selected problem?
can you help i am facing the same problem

**Comment by AndreiMsk** [comment]
The selected event emits a value too. You can set that value in local data, bind that with v-model and you get reactivity.

......
               <datepicker
            :inline="true"
            v-model="date"
            class="pb-3"
            @selected="handleDateSelection"
            :language="language"
        ></datepicker>
.......

data() {
        return {
            language: ro,
            date: new Date(),
            events: [],
            dayjs: dayjs
        };
    },

    methods: {
        async loadCalendarEvents() {
            return axios
                .post("xxx", { date: this.date })
                .then(response => {
                    this.events = [...response.data];
                });
        },

        async handleDateSelection(value) {
            Vue.set(this, "date", value);
            this.loadCalendarEvents();
        }
    }
