### ISSUE TITLE
V-model not empty after reset

### ISSUE THREAD

**Issue by kwnovi** [charliekassel/vuejs-datepicker#120]
I've seen the [related issue](https://github.com/charliekassel/vuejs-datepicker/issues/111) but i doesn't appears to work  : 

`datepicker(placeholder="Select date", v-model="date_mod", language="fr", monday-first=true, v-on:selected='addFilter', clear-button=true)`

`date_mod` doesn't change to an empty `string` or to `null`

**Comment by jenkek** [comment]
try add `v-on:cleared='date_mod=null'`

**Comment by charliekassel** [comment]
Fixed in https://github.com/charliekassel/vuejs-datepicker/commit/3d0b3f3aaa0ccdd59ff7a3692e7a766b76f4cff8
Available from v0.7.8
