### ISSUE TITLE
I want it show placeholder text, also i want default date not today when open the datepicker

### ISSUE THREAD

**Issue by liucf** [charliekassel/vuejs-datepicker#121]
I want it show placeholder text in the input box, also i want default date not today when open the datepicker. 

if i pass :value value, it will not show the place holder text in the input box.
if i do not pass that value, the default date is today when i click to open the datepicker.

how can i do that?

thanks.

**Comment by charliekassel** [comment]
Sorry, this behaviour is not supported.
