### ISSUE TITLE
Datepicker should have a way to stay opened when selecting a range

### ISSUE THREAD

**Issue by maxKimoby** [charliekassel/vuejs-datepicker#128]
When you want to highlight a range of dates, we should be able to pass an option to keep the datepicker opened when only a the "to date" is set. 

The problem I am having is the following : I can't use the inline mode because I don't want the calendar always displayed. However, I want it to stay opened until I am done picking a range.

When not using inline mode, the calendar will hide automatically every time a date is picked.

**Comment by charliekassel** [comment]
I see your point, but there is no way to highlight or select a range of dates anyway though.

**Comment by maxKimoby** [comment]
I just coded something really fast which can do it in a component in which I include your lib and it is working. What do you suggest me?

**Comment by maxKimoby** [comment]
Hey, it's me again. First of all, thank you for your plugin! The most easily usable/customizable datepicker for vue in my opinion.

Here is how I managed to set a range selection on your datepicker :

- Create a component in which you inclue vuejs-datepicker
- Pass a v-model to the datepicker which is gonna be a dummy date.
- Set your highlight params in your component. Set "to" and "from" to null.
- Setup the callback on the selected date :
```js
set_range (value) {
  // Compute your range algorithm, this is mine.
  if (!this.highlighted.from) {
    this.highlighted.from = value
  } else {
    if (this.highlighted.to) {
      this.highlighted.from = value
      this.highlighted.to = null
    } else if (value < this.highlighted.from) {
      this.highlighted.to = this.highlighted.from
      this.highlighted.from = value
    } else {
      this.highlighted.to = value
    }
  }
  
  // Force the "from" date to be highlighted before the "to" is selected
  this.highlighted.dates.push(this.highlighted.from)

  // Setup dummy date to null so datepicker doesn't have a selected date
  this.$nextTick( () => {
    this.dummy_date = null
  })
  
  // Force calendar to stay opened if only "to" has been picked
  if (!this.highlighted.to) {
    this.$nextTick( () => {
      this.$children[0].showCalendar()
    })
   }
  }
```

**Comment by charliekassel** [comment]
I think this is functionality that is outside the scope of a simple datepicker.
