### ISSUE TITLE
The demo doesn't appear to work

### ISSUE THREAD

**Issue by gerrat** [charliekassel/vuejs-datepicker#129]
The demo [link](https://www.webpackbin.com/bins/-KfeGHToc68NnMnmlwJ7) in the readme doesn't appear to do anything.

**Comment by BenjaminListwon** [comment]
Early versions of Vue 2.x had an include path that got changed in later versions. If you toggle the demo to the main.js file and change the first line from:
  import Vue from 'vue/dist/vue'

**Comment by gerrat** [comment]
Thanks @BenjaminListwon   
Much better.
