### ISSUE TITLE
Wrong day of the week

### ISSUE THREAD

**Issue by kkomelin** [charliekassel/vuejs-datepicker#13]
I noticed that August 3d, 2016 is displayed as Thursday http://imgur.com/a/DwOda but it should be Wednesday.

**Comment by kkomelin** [comment]
Sadly, the same error is in the screenshot. Why did not I notice it earlier.

**Comment by charliekassel** [comment]
Ooops! That was a fairly fundamental flaw...

**Comment by kkomelin** [comment]
@charliekassel Thanks for fixing this.
