### ISSUE TITLE
request: responsive

### ISSUE THREAD

**Issue by karlpokus** [charliekassel/vuejs-datepicker#134]
Any plans on making the modal responsive?

**Comment by charliekassel** [comment]
Not currently, but happy to look at a PR

**Comment by wmcmurray** [comment]
FYI, I did this in a project to make sure the calendar is fixed at the approximated center of the screen on mobile devices :

Add this class `fullscreen-when-on-mobile` to your datepicker instance (using the `wrapper-class` prop).

And add this style somewhere (SASS) :

```sass
.vdp-datepicker {
    &.fullscreen-when-on-mobile {
        @media (max-width: 767px) {
            position: static;
            .vdp-datepicker__calendar {
                position: fixed;
                top: 50%;
                left: 5%;
                margin-top: -25%;
                width: 90%;
            }
        }
    }
}
```

Hope it helps ! :slightly_smiling_face:

**Comment by rwrz** [comment]
my 2 cents... I added an overlay using outline, easy, and effective:
`        
z-index: 2000;
outline: rgba(0, 0, 0, 0.5) solid 9999px;
`
so, full CSS will be:
`
.vdp-datepicker {
  &.fullscreen-when-on-mobile {
    @media (max-width: 767px) {
      position: static;
      .vdp-datepicker__calendar {
        position: fixed;
        top: 50%;
        left: 5%;
        margin-top: -25%;
        width: 90%;
        z-index: 2000;
        outline: rgba(0, 0, 0, 0.5) solid 9999px;
      }
    }
  }
}
`
