### ISSUE TITLE
Emit event on selected - previous date

### ISSUE THREAD

**Issue by moff** [charliekassel/vuejs-datepicker#136]
When I use `v-on:selected`, I get previously selected Date - not the one I've just selected.
It'll be great to have selected date.

**Comment by whyleee** [comment]
Use `v-on:input` event instead - works for me.

**Comment by charliekassel** [comment]
I'm not seeing this behaviour.
The webpackbin demo for `With minimum and maximum date range` uses `v-on:selected` in the Settings.

**Comment by takeAction** [comment]
i encountered this problem too, fixed it by `@input` with the help of @whyleee , thanks!
