### ISSUE TITLE
Clearing date doesn't actually clear date

### ISSUE THREAD

**Issue by garygreen** [charliekassel/vuejs-datepicker#142]
Should [this](https://github.com/charliekassel/vuejs-datepicker/blob/master/src/Datepicker.vue#L337) also clear the `currDate` ? Vuejs cannot observe changes on Date objects.

**Comment by charliekassel** [comment]
`currDate` is just used internally so changes shouldn't need to be observed.

**Comment by garygreen** [comment]
Hmm ok. Well on my input field I have `v-model` and when using the `clear-button` functionality it doesn't actually remove the date from the bound model. Not sure if this is related to this or not

**Comment by charliekassel** [comment]
Fixed in https://github.com/charliekassel/vuejs-datepicker/commit/3d0b3f3aaa0ccdd59ff7a3692e7a766b76f4cff8
Available from v0.7.8

**Comment by garygreen** [comment]
Woah, thanks!

**Comment by herico** [comment]
@charliekassel thanks, you literally saved my life
