### ISSUE TITLE
Closing on click when wrapped in label

### ISSUE THREAD

**Issue by andycansdale** [charliekassel/vuejs-datepicker#146]
When the datepicker is wrapped in a label tag, there is some strange behaviour possibly related to click events causing the calendar to close and not reopen whenever anything except a date is clicked on.

For example, changing to the previous or next month will close the calendar as will clicking anywhere inside the box but not on an actual date:

```
<label><p>Date</p>
    <datepicker name="max_date" v-model="form_data.max_date" format="dd/MM/yyyy"></datepicker>
</label>
```

**Comment by charliekassel** [comment]
Interesting, it appears that the label fires the click event for the child input element.
I'll have a play with this dom set up and get back to you.

**Comment by charliekassel** [comment]
This is an interesting situation that I've not come across before.
As the opening/closing of the picker on the input works on a toggle switch and a label wrapped around an input triggers a click event the toggle switch fires twice so closing then opening again the picker.
As I don't want to include the label in the datepicker dom markup as it would be too opinionated the best I can think of is to preventDefault on the label, which works but is not pretty I'm afraid :(

**Comment by MithrandirDK** [comment]
I can live with a @click.prevent="" on the label to fix this - confirmed.

**Comment by javierojeda94** [comment]
The ```@click.prevent=""``` did not work for me. This is my markup:

```html
<label @click.prevent="">
    Availability
    <datepicker v-model="home.available_until" language="es" :clear-button="true"></datepicker>
</label>
```

However the bug is still there

**Comment by javierojeda94** [comment]
Can we wait for a fix on this?

**Comment by wpatter6** [comment]
This appears to still be happening in the latest 1.5.3 release.  I have found that a better solution than adding the prevent to the label is to add another element under the label which can perform the @click.prevent behavior.  This allows the label to continue to behave as a label and focus/open the datepicker when clicked.  Working example: https://codesandbox.io/s/5271my6x4k

**Comment by DinnerKang** [comment]
This appears to still be happening in the latest 1.6.2 release
I spent a lot of time looking for this error. I would appreciate it if you could write on ReadMe.
