### ISSUE TITLE
Pre-compile *.vue files to JS

### ISSUE THREAD

**Issue by kkomelin** [charliekassel/vuejs-datepicker#15]
To prevent errors like this:

> ERROR in ./~/vuejs-datepicker/src/components/Datepicker.vue
> Module not found: Error: Cannot resolve module 'stylus-loader' in ../node_modules/vuejs-datepicker/src/components
> @ ./~/vuejs-datepicker/src/components/Datepicker.vue 2:0-172
https://github.com/charliekassel/vuejs-datepicker/issues/7

And this:

> ERROR in static/js/vendor.9868ef83011ecc7ffbea.js from UglifyJs
> SyntaxError: Unexpected token: keyword (default) [./~/vuejs-datepicker/src/utils/DateLanguages.js:1,0]
https://github.com/charliekassel/vuejs-datepicker/pull/14#issuecomment-238161178

And after discussing them with @yyx990803, who gave the idea of pre-compiling *.vue files of the component to plain JS https://github.com/vuejs-templates/webpack/issues/216#issuecomment-238375315, I suggest considering this possibility and solving two above problems with one stone.

**Comment by kkomelin** [comment]
As I see now, the component has a build command that actually builds the component. However, it may be not exactly what we need.
Some ideas:
1) What if we move the demo files into a subfolder?
2) What if we use webpack? Something like this https://github.com/MopTym/vue-waterfall/tree/master/build

**Comment by charliekassel** [comment]
OK @kkomelin I've changed the npm main file to a compiled version and moved demo files to their own dir. `src` dir is much cleaner now.
Not changed to webpack but feel free to submit a PR if you'd like to do that.

**Comment by charliekassel** [comment]
Ah thank you @yyx990803 for spotting that!
So instead of the contents here: https://github.com/charliekassel/vuejs-datepicker/blob/master/src/main.js I should just require the .vue component file?

**Comment by kkomelin** [comment]
With the pre-built version:
> WARNING in ./~/vuejs-datepicker/dist/build.js
> Critical dependencies:
> 1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
>  @ ./~/vuejs-datepicker/dist/build.js 1:113-120

**Comment by charliekassel** [comment]
Yes, I'm aware there are problems with this.
I'm not actually sure what the best approach is to exporting this is.
Personally, I only use this in my projects as a component I can import into other components so exporting the .vue file worked fine for me.
Too bust with work at the moment to spend time on it right now.

**Comment by kkomelin** [comment]
@charliekassel Thanks for making it clear.

**Comment by charliekassel** [comment]
This package has now been updated to use a webpack build and export a compiled js file @kkomelin .

**Comment by kkomelin** [comment]
Thank you @charliekassel for your efforts. I will test it when i have time.
