### ISSUE TITLE
Feature request: Ability to change layout calendar style

### ISSUE THREAD

**Issue by justanne** [charliekassel/vuejs-datepicker#151]
Hopefully a layout could be added, by which we could have ability to change Month and Year by dropdown so its easily accessible. Like in the screenshots below:

![screen shot 2017-05-12 at 9 03 56 pm](https://cloud.githubusercontent.com/assets/1003597/25999344/5db478ee-3757-11e7-9743-93de413b04ad.png)

![screen shot 2017-05-12 at 9 13 16 pm](https://cloud.githubusercontent.com/assets/1003597/25999575/44006ee8-3758-11e7-9e15-3492d50080ce.png)

**Comment by charliekassel** [comment]
Thanks for the suggestion but this requires a lot of core changes and I personally prefer to navigate the way I currently have it.
