### ISSUE TITLE
Disabled Dates not updating until I click next

### ISSUE THREAD

**Issue by eman1000** [charliekassel/vuejs-datepicker#152]
I have a date picker in my vue component whihk looks like this
`<datepicker v-model="fromDate" :language="currentLanguageShort" v-on:selected="departureDateSelected" :disabled="disabledDepartureDateSettings" :inline="true"></datepicker>`

I am disabling dates based on an API call and updating the dates array.

My response from the API call looks like this:
```
{
	"startDate": "2017-05-17",
	"endDate": "2017-10-28",
	"disabledDates": {
		"2017": {
			"5": [17, 19, 22, 24, 26, 29, 31],
			"6": [2, 5, 7, 9, 12, 14, 16, 21, 19],
			"9": [13, 15, 18, 20, 22, 25, 27, 29, 11],
			"10": [2, 4, 6, 9, 11, 13, 16, 18, 20, 23, 25, 27]
		}
	}
}

```

Then I update the disabled dates array with the following code:
```
		disableFromDate(){
			var vm = this;
			var datesApiDate = this.disabledDatesFromApi.disabledDates;
			var i = 0;

			for (var key in datesApiDate) {
			  if (datesApiDate.hasOwnProperty(key)) { 
			    var year = datesApiDate[key];	
			    for (var monthKey in year){
			    	if (year.hasOwnProperty(monthKey)) {

			    		year[monthKey].forEach(function(element){
			    			vm.datesToDisable.push(new Date(key, monthKey-1, element));
			    		});
		
			    	}
			    }	    
			  }
			}

			//this.disabledDepartureDateSettings.dates = [];
			this.disabledDepartureDateSettings.dates = vm.datesToDisable;
			this.nextMonth();
			console.log(this.disabledDepartureDateSettings.dates);
			
		}
```
For some reason the disabled dates only get updated when I click next on the datepicker. A little help will be appreciated.

**Comment by a1tem** [comment]
The same here.

**Comment by praveen-wal** [comment]
Guys, Did you find a solution?

**Comment by lexcode** [comment]
I will replace this plugin with some other that are 100% maintainable, this has a lot fixes but the owner does not seems to be care to merge them. Time to give up
