### ISSUE TITLE
Not showing correct value with format dd/MM/yyyy

### ISSUE THREAD

**Issue by afucher** [charliekassel/vuejs-datepicker#153]
Hi, I'm trying to use datepicker with another format, it shows correctly the value when I'm selecting, but when I pass a value it not respect the format:
`<datepicker format="dd/MM/yyyy" value="01/05/2017"></datepicker>`

It shows 05/01/2017, I'm missing something??

**Comment by charliekassel** [comment]
if you pass a string value to the prop it will try to construct the Date object with that.

Try typing `new Date('01/05/2017')` in your Chrome developer tools console.
