### ISSUE TITLE
bug: nextMonth's button

### ISSUE THREAD

**Issue by Kyleloh** [charliekassel/vuejs-datepicker#156]
1. chose date: May.31
2. click the 'next month' button
you expect it to show the June, but it show July...
because of the following method:(June.31 is July.1st)
```
nextMonth () {
      if (this.nextMonthDisabled()) {
        return false
      }
      let d = new Date(this.currDate)
      const daysInMonth = DateUtils.daysInMonth(d.getFullYear(), d.getMonth())
      d.setDate(d.getDate() + daysInMonth)
      this.currDate = d.getTime()
      this.$emit('changedMonth', d)
    },
```

**Comment by charliekassel** [comment]
I'm not seeing this behaviour and have added a test to assert this - https://github.com/charliekassel/vuejs-datepicker/commit/245e362e95fa724ea28b4f1b36e3c3d6d7a071c6

What version of the datepicker are you using?

**Comment by Kyleloh** [comment]
i try my  in the demo:  [https://www.webpackbin.com/bins/-KhQbtTSVuU6r8VCrIdC](https://www.webpackbin.com/bins/-KhQbtTSVuU6r8VCrIdC)
1. click to show the Calendar and chose the date May.31
2. click to show the Calendar
3.click other place to hide the Calendar
4. click to show the Canelndar and click "nextMonth's button"
you'll find that it show the July

i have made a gif, have a look...
gif:  [https://github.com/Kyleloh/something/blob/master/GIF.gif?raw=true](https://github.com/Kyleloh/something/blob/master/GIF.gif?raw=true)

**Comment by Kyleloh** [comment]
```
    nextMonth () {
      if (this.nextMonthDisabled()) {
        return false
      }
      let d = new Date(this.currDate)
      const daysInMonth = DateUtils.daysInMonth(d.getFullYear(), d.getMonth())

     /* Here~  */
     /* when currDate is May.31th, here is d.setDate(31+31),  is July.1st , right ?*/
      d.setDate(d.getDate() + daysInMonth)

      this.currDate = d.getTime()
      this.$emit('changedMonth', d)
    },
```

**Comment by charliekassel** [comment]
`this.currDate` is a timestamp built from a Date that is always the first of the month - https://github.com/charliekassel/vuejs-datepicker/blob/master/src/Datepicker.vue#L716 - so 1 + 31 equals 32 or the first of the next month.
The demo works for me so it must be something to do with your timezone - what is it please?

**Comment by Kyleloh** [comment]
My timezone is UTC/GMT+08:00. maybe that is the problem.

**Comment by Kyleloh** [comment]
```
document.addEventListener('click', (e) => {
        if (this.$el && !this.$el.contains(e.target)) {
          if (this.isInline()) {
            return this.showDayCalendar()
          }
          this.resetDefaultDate()
          this.close()
        }
      }, false);
```
```
resetDefaultDate () {
      this.currDate = (this.selectedDate === null) ? this.getDefaultDate() : this.selectedDate.getTime()
    },
```
when click document, it run `resetDefaultDate()`;
then if `this.selectedDate!==null`, `this.currDate = this.selectedDate.getTime()`,
in this case, the `currDate` is not the first of the month..

Is that the problem?

**Comment by Kyleloh** [comment]
i added a test, it failed.
```
  it('can set the next month correctly on the last day of a 31 day month', () => {
    const date = new Date(2017, 4, 31)
    vm.$refs.component.selectDate({timestamp: date.getTime()})
    // document click event run resetDefaultDate();
    vm.$refs.component.resetDefaultDate();
    vm.$refs.component.nextMonth()
    expect(vm.$refs.component.getMonth()).to.equal(5)
  })
```
