### ISSUE TITLE
Ability to choose which view the datepicker opens to?

### ISSUE THREAD

**Issue by mismith** [charliekassel/vuejs-datepicker#159]
Pretty slick plugin-- great work (and the source code looks good too)!

I'm specifically using this for a birthday date picker, so the year is the starting point. Right now, users have to click the title bar from the day view, then again from the month view, then scroll through decades to find their birth year, then drill back down to the exact date. It would be handy to be able to skip the first half and show the the year view first.

FWIW, I'd be willing to submit a pull request for this, but I don't wanna start that unless there's some prospect of the changes being merged in, since I also don't want to spawn and support my own fork.

Thoughts?

**Comment by charliekassel** [comment]
I'd be open to reviewing a PR for this.

**Comment by mismith** [comment]
Sweet, I'll submit it soon!
