### ISSUE TITLE
I can't set the calendar to display in months

### ISSUE THREAD

**Issue by nashoshinoda** [charliekassel/vuejs-datepicker#160]
Hi,

I'm noobie with Vue.js (actually, this is my first week working with it) and I'm trying to display the calendar in months with the year at the top like this:
http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode

I tried to do it but I failed. This is the code:

<datepicker :format="format"></datepicker>

<script>

    import Datepicker from 'vuejs-datepicker';

    var state = {
        date: new Date()
    }

    export default {
        components: {
            Datepicker
        },
        data () {
            return {
                format: 'MM/yyyy',
                viewMode: 'months',
                startView: 1,
                state: state
            }
        },
    }
    
</script>

The goal of this if click any month and load the format 'month(MM)/year(YYYY)' to send it to a model through Laravel and display some information. Any idea how to show the calendar in months? Thanks in advance!

**Comment by charliekassel** [comment]
Sorry the component is not built for a month picker, only to navigate the months to then pick a date.

**Comment by charliekassel** [comment]
Maybe keep an eye on [this issue](https://github.com/charliekassel/vuejs-datepicker/issues/159) - it's not exactly what you want but the functionality would be similar.

**Comment by nashoshinoda** [comment]
Thanks ;)
