### ISSUE TITLE
Dynamic class binding raises an error

### ISSUE THREAD

**Issue by alex996** [charliekassel/vuejs-datepicker#169]
I'm using this datepicker with [Bulma](https://github.com/jgthms/bulma) and [VeeValidate](https://github.com/logaretm/vee-validate). The goal is to have an `<input>` with the class of `input` and, if the validator fails, assign the class of `is-danger`. However,

```html
<datepicker :inputClass="{ 'input': true, 'is-danger': errors.has('dob') }"
             v-validate="'required|date_format:YYYY-MM-DD'">
</datepicker>
```

raises an error 

```
Invalid prop: type check failed for prop "inputClass". Expected String, got Object.
```

Is there an alternative to accomplish this? Are you planning to add dynamic class binding in the nearest future? Thanks

**Comment by charliekassel** [comment]
Interesting. I can see this being useful though so I think I can support this - stayed tuned!

**Comment by TylerButh** [comment]
What happened to this? Has it been implemented?
