### ISSUE TITLE
Warning message using the runtime-only build of Vue

### ISSUE THREAD

**Issue by seixasfelipe** [charliekassel/vuejs-datepicker#170]
Hi, I'm having this warning when I use the <datepicker></datepicker> component:

`
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
`

Here's my Appointment.vue file:

```javascript
<template>  
  <div class="container">
    <datepicker placeholder="Select date"></datepicker>
  </div>
</template>

<script>
  import Datepicker from 'vuejs-datepicker';

  export default {
    components: {
      Datepicker,
    },
  };
</script>

<style scoped>
</style>
```

I've also tried to put in my webpack.config the following alias to try to solve the problem:
```javascript
resolve: {
    alias: {
      'datepicker': path.join(__dirname, 'app/node_modules/vuejs-datepicker/dist/build.js'),
    },
}
```

node -v
v6.10.3
npm -v
3.10.10
package.json
"vuejs-datepicker": "^0.7.14"

I'm also using electron-vue as boilerplate.

thanks

**Comment by charliekassel** [comment]
See https://github.com/charliekassel/vuejs-datepicker/issues/147

**Comment by charliekassel** [comment]
This may now work as of v8.0.3 - can you please try and confirm?
