### ISSUE TITLE
Disabled 'days' Override?

### ISSUE THREAD

**Issue by donavonyoung** [charliekassel/vuejs-datepicker#172]
Any plans to have the ability to add an available date array that would override a disabled date? So for instance we would normally disable all Mondays using the "days" array. But there may be specific Mondays during the year that we would need to enable for various reasons.

**Comment by charliekassel** [comment]
No, it's a Boolean. You'll have to handle that yourself I'm afraid

**Comment by charliekassel** [comment]
I'm happy to look at a PR if this helps you btw but I don't have a need for this myself

**Comment by donavonyoung** [comment]
Right on. I'll post a request soon.
