### ISSUE TITLE
Runtime error when using single-file component and Webpack

### ISSUE THREAD

**Issue by alissay** [charliekassel/vuejs-datepicker#178]
Hi, I'm attempting to use vuejs-datepicker in Vue 2 in a single-file component, compiled using Webpack. When I try to use the component, I'm getting the following error: "You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build." 

I haven't run into this error with any other vue components, and wondering if you know what's causing it or have a solution? 

Also, I'd love to be able to register the component globally to use in all my .vue files if possible. Any help you might have would be much appreciated. thanks!

**Comment by charliekassel** [comment]
As of v8.0.3 I am now building with runtime only so this should now work for you - please let me know.

As for registering the component globally I'm assuming you mean as a plugin? i.e. `Vue.use(Datepicker)`

**Comment by charliekassel** [comment]
Closing due to lack of response and inactivity.
