### ISSUE TITLE
Is it possible make date readable but the value returned to my binding defaults to Y-m-d?

### ISSUE THREAD

**Issue by jericopulvera** [charliekassel/vuejs-datepicker#179]
change default date data. 2017-06-21T16:00:00.000Z to 2017-06-21

how do I do this?

**Comment by charliekassel** [comment]
It returns a Date object, you'll have to format it how you want it yourself.
You could potentially use the DateUtils.formatDate method that the package uses internally:
```
import DateUtils from 'vuejs-datepicker/src/utils/DateUtils.js'
```
or go with moment.js

**Comment by pribilinskiy** [comment]
By default `node_modules` aren't processed by UglifyJS in a webpack build and somewhy that class isn't available publicly in the compiled `dist/build.js`

**Comment by charliekassel** [comment]
Ah sorry - I did say _potentially_

The formatting is purely for the input display - the output is a Date object because this is much more useful than a string.

**Comment by pribilinskiy** [comment]
@charliekassel not true, it's convenient for preview purposes.
The `formatDate` uses `DateLanguages` to show the date formatted in the required l10n without the need to load e.g. `moment.js`

I had to extract `formatDate` and import `DateLanguages` from `node_modules/vuejs-datepicker/src/utils/DateLanguages` as it's just a POJO

**Comment by charliekassel** [comment]
Be careful - as noted in the code and the readme, the formatDate is not a great solution. It's quite flaky really :(

**Comment by pribilinskiy** [comment]
> as noted in the code and the readme

Could you tell where it's noted in readme?

Here's the code, what's flaky in it?

```js
    formatDate (date, format, translation) {

        translation = (!translation) ? DateLanguages.translations.en : translation;

        const year = date.getFullYear();
        const month = date.getMonth() + 1;
        const day = date.getDate();

        const str = format
            .replace(/dd/, ('0' + day).slice(-2))
            .replace(/d/, day)
            .replace(/yyyy/, year)
            .replace(/yy/, String(year).slice(2))
            .replace(/MMMM/, this.getMonthName(date.getMonth(), translation.months.original))
            .replace(/MMM/, this.getMonthNameAbbr(date.getMonth(), translation.months.abbr))
            .replace(/MM/, ('0' + month).slice(-2))
            .replace(/M(?!a|ä)/, month)
            .replace(/su/, this.getNthSuffix(date.getDate()))
            .replace(/D(?!e|é|i)/, this.getDayNameAbbr(date, translation.days))
        ;

        return str;
    },
```
