### ISSUE TITLE
Initial View on Inline calendar

### ISSUE THREAD

**Issue by paulschneider** [charliekassel/vuejs-datepicker#182]
Hey @charliekassel 

Not a bug as I can see its intentional but whats the reason on not allowing the initial-view prop to be refused for an inline calendar? I noted from @mismiths PR that he wanted the initial-view prop because of a birthday selection requirement and this is my use case too but it seems odd that we can have it on the inline calendar.

Any plans to support this?

* Great plugin by the way. Very easy to use!

**Comment by charliekassel** [comment]
No reason. This is new functionality so it's not been carried over to the inline mode.
Happy to support, PR welcome.
