### ISSUE TITLE
Format incorrect for spanish

### ISSUE THREAD

**Issue by javierojeda94** [charliekassel/vuejs-datepicker#183]
The users on my app speak spanish so I need to show the date in spanish, when I set the format this way:
```html
<label @click.prevent="">
    <datepicker v-model="available_until" language="es" format="dd de MMMM de yyyy"></datepicker>
</label>
```
I want to get ```20 de Junio de 2017``` but instead the component shows ```20 20e Junio de 2017```

How can I get rid of that replacement for the first "d" in my first "de"?

**Comment by coderdiaz** [comment]
At the moment this format can not be performed.
https://github.com/charliekassel/vuejs-datepicker/blob/master/src/utils/DateUtils.js#L124-L148

**Comment by coderdiaz** [comment]
@javierojeda94 You could get the date from the datepicker with the input event and process it with moment.js to show it to the user.

**Comment by javierojeda94** [comment]
Yes, but that implies using another library (I don't like to use another library to just one simple function). Let me check the code and maybe I can do something. Probably I will do a PR about this. 

I think this is an important issue, not because of the language but the format itself

**Comment by coderdiaz** [comment]
Nice :+1: @javierojeda94

**Comment by charliekassel** [comment]
Yeah, it's a known bug that the date formatter is rubbish.
I've documented in the code and the readme.
Also see here https://github.com/charliekassel/vuejs-datepicker/issues/102

I would like to to a rewrite of this function at some point.

**Comment by charliekassel** [comment]
I'm closing this issue as what you are trying to do is not supported.
Feel free to submit a PR if you can come up with a good solution.
