### ISSUE TITLE
Ease of including vuejs-datepicker component

### ISSUE THREAD

**Issue by Artistan** [charliekassel/vuejs-datepicker#184]
I am using vuejs-datepicker in my component... https://github.com/Artistan/vuejs-range-datepickers
It would be very efficient if you could have the properties be a mixin that you use in your component and have available to other components that want to include your component with all of it's properties.

I did a quick example of how I may do it on my own component...
https://www.webpackbin.com/bins/-KnHRfIsYz8cbqfdH02V

So my component could use your mixin...
```
// Datepicker.vue
  var datepickerPropsMixin = {
    props: {
      value: {
        type: Object,
        default: function() {
          return {
            start: new Date(),
            end: new Date('+14 days')
          }
        },....
    }
```

to properly include your properties
- ease of upgrades
- minimize footprint of parent components
- clean code

```
// component using the datepicker, COMPONENT.vue
  export default {
    mixins: [datepickerPropsMixin],
    components: {
      datepicker
    },
    props: {
      // other properties specific to parent component
    },
    data () {...
```

Let me know what you think...

**Comment by charliekassel** [comment]
I'm not sure I understand what you require from my component?
Surely this is down to the the parent component's management of data and so outside of the scope of the datepicker?

**Comment by charliekassel** [comment]
Closing due to lack of recent interest.
