### ISSUE TITLE
Anyway to let the user only select year and month?

### ISSUE THREAD

**Issue by goncalomarques** [charliekassel/vuejs-datepicker#190]
Imagine, e.g. a credit card expiration date where you just want to know the month and year. Anyway to do this?

**Comment by charliekassel** [comment]
Not currently.
I can't imagine that it would be too much of a stretch to modify this for that purpose though.
Happy to look at a PR.

**Comment by charliekassel** [comment]
Yes as of 0.9.19 this is now possible
