### ISSUE TITLE
Emits erroneous opened/closed events when inline set to true.

### ISSUE THREAD

**Issue by jason-rapp** [charliekassel/vuejs-datepicker#195]
When setting inline to true.

`<datepicker :inline ='true'> </datepicker>`

I get a pair of `opened` and `closed` events whenever I click anywhere on page even outside of datepicker component.  I wouldn't expect to get these events at all.

Not a major issue as I'm not listening for them anyway, but makes a good deal of noise when looking at events I do care about.

**Comment by charliekassel** [comment]
Thanks for the heads up.
Fixed in 07cc734

**Comment by jason-rapp** [comment]
Thanks!
