### ISSUE TITLE
How to custom input class?

### ISSUE THREAD

**Issue by dev-juyoung** [charliekassel/vuejs-datepicker#196]
Hello,
First of all, thank you for providing a good library.

I created css by specifying input-class, but it is not reflected in actual screen.
I ask for help to see how it works. Below is a snippet of code.

* sample.vue
```
<template>
    // ... code
    <date-picker v-model="conditionDate" wrapper-class="datepicker-wrapper" input-class="datepicker"></date-picker>
    // ... code
<template>

<script>
import Datepicker from 'vuejs-datepicker';

export default {
    // ... code
    conponents: { 'date-picker': DatePicker }
}
</script>

<style scoped>
// ... code

input.datepicker {
    border: 1px solid #ff0000;  // <-- This code is not working
}
</style>
```

**Comment by charliekassel** [comment]
That will apply the `datepicker` css class to the input - if it's not working then you have conflicting styles somewhere.

**Comment by markusdanek** [comment]
This is a really bad answer... I have the same issue it is not a conflicting issue here!
Needs to be reopened!

**Comment by magistr4815** [comment]
I can assume that the problem is this:
**wrapperClass**="datepicker-wrapper"
And you use <style **scoped**>. Styles are applied only to this component and not to internal.
