### ISSUE TITLE
Propped value of type String is not formatted correctly.

### ISSUE THREAD

**Issue by roncabal** [charliekassel/vuejs-datepicker#208]
When propping a String value to the component with a format like so:
`<datepicker format="dd/MM/yyyy"  value="01/03/2017"></datepicker>`

The component doesn't use the format propped to it, which creates an incorrect date. It will show "03/01/2017" instead of the value propped. I checked the source codes and it looks like the issue is on *Datepicker.vue* file.

```
formattedValue () {
   if (!this.selectedDate) {
       return null
   }
   return DateUtils.formatDate(new Date(this.selectedDate), this.format, this.translation)
},
```

On *Datepicker.vue*, it passes `new Date(this.selectedDate)` as the first parameter, it uses the default  date format of the Date object which causes the component to return the incorrect value.

Thanks! 👍

**Comment by mubaidr** [comment]
This is clearly mentioned in the Readme that:

> value prop if passed should be a Date object

**Comment by roncabal** [comment]
Isn't it Date|String?

![screen shot 2017-07-12 at 1 15 31 pm](https://user-images.githubusercontent.com/7876034/28102792-35d4e67e-6704-11e7-827c-528b1120ac4e.png)

**Comment by mubaidr** [comment]
I believe this is mistake in the documentation of the API. All examples and usage documentation states that it should be a date object. I too, got confused when using this first time.

**Comment by charliekassel** [comment]
I accepted a PR to pass a string a while back. This just calls `new Date(string)` on the string and doesn't try to parse it in any other way.
So your string value needs to be understood by `Date.parse()`.

I personally recommend passing a Date object as value.

**Comment by roncabal** [comment]
Got it. Maybe it is best to put the string format on the read me file to avoid confusion? 😄 

Anyway, thanks for checking on my issue. 
Also, thanks for building this component! 😄

**Comment by gezichenshan** [comment]
So, is there a format string for the value?
