### ISSUE TITLE
Datepicker still persisting selected value after close.

### ISSUE THREAD

**Issue by akumarcompassites** [charliekassel/vuejs-datepicker#213]

**Comment by charliekassel** [comment]
Isn't that expected behaviour?

**Comment by akumarcompassites** [comment]
> **scenario**

- I opened Datepicker, selected a date , after that i closed it. Now what happening , when i am trying to check in chrome devtool ,Selected value is still persisting. 

It should be , when i closed datepicker selected value should be null.

I would like to suggest , please add any method that can reset selected date.

**Comment by charliekassel** [comment]
That is not how is should work at all I believe.
However, there is a `clear-button` prop available to add a button that will clear the input for you

**Comment by akumarcompassites** [comment]
But If , I don't want any widget or icon to make clear date , is any other ways to do the same?

Thanks ,
Amarkant.
