### ISSUE TITLE
Changing date in code not reflected in display.

### ISSUE THREAD

**Issue by dawgavins** [charliekassel/vuejs-datepicker#215]
Thanks for the component, it works well.

I'm using this picker to define a range of dates (to make a database query).  I have added some shortcut buttons beside the picker to move the range forward/back a month.  When I do this, the value bound via v-model (startDate) does pick up the changes (I see the new results when the query is run), but the text in the input box of the picker does not change.

```
<datepicker v-model="startDate" :disabled="disabledFutureDates()"></datepicker>
<button class="btn-update" v-on:click.prevent="decMonth()"><i class="fa fa-angle-left" aria-hidden="true"></i></button>

...
methods: {
    decMonth() {
        // this does change the value of startDate but is not reflected in the picker display
        this.startDate.setMonth(curMonth - 1);
    }
```

Thanks for your time.

**Comment by charliekassel** [comment]
So `setMonth` only sets a marker for the current 'page' - it does not affect the selected value.
You would need to additionally call `selectDate` to do this.

**Comment by dawgavins** [comment]
Just to be clear....that "setMonth" is being called on a javascript Date object that is bound to the component via v-model...its not the setMonth function on the component.

Your response gave me the idea of calling a function on the component directly.  I hadn't done this before, but I did the following:
```
// added "ref" here
<datepicker ref="startDate" v-model="startDate"></datepicker>
<button class="btn-update" v-on:click.prevent="decMonth()"><i class="fa fa-angle-left" aria-hidden="true"></i></button>
...
decMonth() {
    this.startDate.setMonth(this.startDate.getMonth() - 1);
    // calling component function setDate explicitly here....accessible via $refs
    this.$refs.startDate.setDate(this.startDate);
}
```
and this achieves what I was trying to do.  I wonder if you could detect the external (to the component) modification of the bound date via a watch and update it as I did above.  Just a thought.
