### ISSUE TITLE
Full day word

### ISSUE THREAD

**Issue by nicolasvahidzein** [charliekassel/vuejs-datepicker#216]
Hello Mr Kassel, thank you for a wonderful component, it's a lifesaver.

Do you know how i can implement DD for a full day? I find it more readable, do you have pointers as to how to do it and add support for the different files?

Thanks.

**Comment by charliekassel** [comment]
This is not possible at the moment due to not having this in the language files.
But keep an eye on https://github.com/charliekassel/vuejs-datepicker/issues/211 as this potential PR will introduce a new date library that has more formatting options.
