### ISSUE TITLE
Possible to wrap datepicker around an icon of our choice

### ISSUE THREAD

**Issue by nicolasvahidzein** [charliekassel/vuejs-datepicker#217]
Hello Mr Kassel, is it possible to insert an element inside the datepicker tab and use that? I can't change the styling to fit my needs. Thank you very much.

**Comment by charliekassel** [comment]
Currently there isn't any `slot` elements in the datepicker.
But feel free to submit a PR is this is something you find useful.

**Comment by nicolasvahidzein** [comment]
Can you send me a link that shows how to create a slot i'll happily work on it.

**Comment by charliekassel** [comment]
https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots

**Comment by nicolasvahidzein** [comment]
At the risk of appearing like a noob (which i am) do you also have a link that shows how to load and recompile your project? I always wanted to try but never knew where to look. I will see how you built it and will modify it. The PR will also require your help as i've never done it as well.

**Comment by nicolasvahidzein** [comment]
Hello, i never got a response, i would appreciate your help.

**Comment by charliekassel** [comment]
You can run `npm run dev` to spin up a local express server that watches you changes at localhost:8080

It's based on the vue cli webpack template - you can find more info here: https://github.com/vuejs-templates/webpack

**Comment by nicolasvahidzein** [comment]
Ok i will try that, but when i go inside that folder and run npm install i get a ton of error, so i just run a dev server inside? And how do i export it to use it in my project after that?
