### ISSUE TITLE
selected date offset 1 day?

### ISSUE THREAD

**Issue by aqualaguna** [charliekassel/vuejs-datepicker#218]
here my code 
`<datepicker v-model="form.transaction_date" required language="id" input-class="is-fullwidth input"></datepicker>`

i set the component at 2017-07-20
and i get the result 1 day more of it why?
transaction_date:"2017-07-21"

**Comment by charliekassel** [comment]
How are you setting the component?
And what version are you using please?

**Comment by aqualaguna** [comment]
i delete the language="id" and all work perfectly.
also i had some bug when the component at month "May" it show "5ei"

**Comment by departure** [comment]
Hi Charlie, I’m experiencing this same issue. `Vue 2.2.6`.

I’m attaching a screenshot of Vue devTools. — Note that in the data object, the `selectedDate` property is set to **2017-08-10**, however the computed property `formattedValue` is set to **09 Aug 2017**, (which is correct intended value).

![screen shot 2017-08-04 at 5 41 35 pm](https://user-images.githubusercontent.com/5169100/28991449-9eee6bae-793c-11e7-8346-9850a920b620.png)

**Comment by departure** [comment]
Hi Charlie, the same issue can also be observed on your demo at: `https://www.webpackbin.com/bins/-KhQbtTSVuU6r8VCrIdC`

I’m attaching a screen shot below.

The date selected was **May 10**, yet the `{{ vModelExample }}` outputs **May 11**.

<img width="781" alt="screen shot 2017-08-04 at 11 43 13 pm" src="https://user-images.githubusercontent.com/5169100/28993582-f93986ca-796e-11e7-9c4a-50eda57b5cf9.png">

**Comment by charliekassel** [comment]
The output is the Date object which include the timestamp.

You can see the same behaviour by typing `new Date()` in Chrome console.

**Comment by departure** [comment]
Hi Charlie, I understand it now. Thanks for clarifying.
