### ISSUE TITLE
Question "enabled" days

### ISSUE THREAD

**Issue by luis-conor** [charliekassel/vuejs-datepicker#22]
Hi, 
Is there a property that exposes the enabled days, or at least the first and last enabled days?
Reason is I want to set the :value to the first enabled day and it can be tricky to calculate, but since the datepicker already calculates that I thought it would make sense to expose that somehow..

Thanks in advance!

**Comment by charliekassel** [comment]
There's no calculation for first available day I'm afraid.

**Comment by luis-conor** [comment]
Ok, thanks
