### ISSUE TITLE
Allow user input (don't force readonly)

### ISSUE THREAD

**Issue by rtheunissen** [charliekassel/vuejs-datepicker#231]
The datepicker currently requires that an input field be read-only. If we used a good parsing library like moment.js, it would be very useful to allow user input to be parsed and set as the date if parsed successfully. This would be easy to implement if you can delegate the parsing. 

We are looking for a good vue2 datepicker and this is the best solution we could find, but we have a strong requirement that the user should be able to type the date if they choose to.

**Comment by ak04nv** [comment]
Also it looks shockingly for user. The field is disabled but actually not. :)

**Comment by julienr-geronimo** [comment]
Clearly that would be a great enhancement ! 

Do someone know another vuejs pluggin which do the same thing but which allow user input ? :smile:

**Comment by guilima** [comment]
This is a interesting feature, but not as simple as it seems. I did that [here](https://guilima.github.io/financials-index/) and took more than a 'readonly' removal to make it work decently.

The [fork](https://github.com/guilima/vuejs-datepicker/commits/master) with the changes aren't useful in general and that is why i did not open a PR. In short i have added a mask dependency (lazy), keyup event and a regex to set the value on datepicker only when the date has the correct format and range.

 I really hope to see a multipurpose implementation with the moment library or not.

**Comment by sqpdln** [comment]
I solved it by using inline mode, hiding/showing it with a simple v-if and reacting on selected, changedYear and changedMonth.

**Comment by SzNagyMisu** [comment]
Nice one, @sqpdln ! Only, I would use v-show, not v-if.
And it would surely be nicer if this feature was available :-)

**Comment by adamwright104** [comment]
@sqpdln can you show an example?

**Comment by sqpdln** [comment]
@adamwright104 for what it's worth: https://gist.github.com/sqpdln/8e1be9fde15423a6a422f817c8d248a7

(I blindly stripped away some code, not sure it will actually run without some modifications).

**Comment by charliekassel** [comment]
Ok, this is finally resolved in v1.

**Comment by vbalagovic** [comment]
Hello, i just updated package to latest version but my input still stays read only, was this supposed to be enabled by default or did i missed something? Thanks in advance

**Comment by stephiescastle** [comment]
@charliekassel apologies, just say the "typeable" prop.
