### ISSUE TITLE
No long work with Vue 1.x since v.0.8.0

### ISSUE THREAD

**Issue by ratiw** [charliekassel/vuejs-datepicker#233]
This can be reproduced by updating your demo to use vue@1.0.28 and vuejs-datepicker@0.8.0

**Comment by charliekassel** [comment]
Yes... I think I should drop support for 1.x

What do you think?

**Comment by ratiw** [comment]
I think it would be ok, but you'll just have to update the README.md to reflect that. 

I learned about this because I was trying to replace another component with yours in another project of mine that's still using Vue 1.x.

However, if you could make it work with both Vue 1 and 2, it would be great for those who are using Vue 1.x.  I have updated my component to Vue 2 for quite sometimes, but people are still using the version that works with Vue 1.x for almost a year now. That is quite surprising to me.
