### ISSUE TITLE
Translations reactive

### ISSUE THREAD

**Issue by vip30** [charliekassel/vuejs-datepicker#24]
Will it support to react if we switch the language dynamically?
`<datepicker :language="myLanguage"></datepicker>`
which myLanguage will be changed by pressing the language switch button

I changed the translation to be one of computed properties,
this is ok for switching the language in the calandar but only the date in the textbox does not change

Thanks!

**Comment by charliekassel** [comment]
I've made the value in the text box a computed property now so this should pick up changes to the language.
Can you please check and confirm?

**Comment by vip30** [comment]
https://i.imgsafe.org/2eb6cc887c.png

Sorry about that, actually I found that the string in the datepicker can't be changed.
Is it possible to change that too?
Thanks for your help

**Comment by charliekassel** [comment]
This is not something I personally need so I can't justify spending time on it myself.
But you are more than welcome to put in a PR for this.
