### ISSUE TITLE
Date returned on v-on:selected is incorrect due to daylight saving on Firefox 54

### ISSUE THREAD

**Issue by coxeh** [charliekassel/vuejs-datepicker#241]
When getting the date value when selecting a day from v-on:selected event. In Firefox 54 it is an hour back causing the date to go back to the previous day. For example if I choose 1st Aug 2017 the output in console is: Date 2017-07-31T23:00:00.000Z

my timezone is currently BST (+1:00)

example: https://www.webpackbin.com/bins/-KqcBDQZkjWCvVZ9Vzig. 

Chrome doesnt appear to be affected by this.

**Comment by charliekassel** [comment]
Should be fixed in v9+
