### ISSUE TITLE
How to use calendar-class wrapper-class for the type Object

### ISSUE THREAD

**Issue by laxiry1** [charliekassel/vuejs-datepicker#243]

**Comment by laxiry1** [comment]
<datePicker v-model="personInfo.bornDate" :language="language" :format="format" :disable="disabled"
                    :dplaceholder="holder" calendar-class="calendarCss" wrapper-class="pickerWrapperCss"></datePicker>

<datePicker v-model="personInfo.bornDate" :language="language" :format="format" :disable="disabled"
                    :dplaceholder="holder" :calendar-class="calendarCss" :wrapper-class="pickerWrapperCss"></datePicker>

data () {
      return {
        language: 'zh',
        format: 'yyyy-MM-dd',
        holder: '请选择日期',
        disabled: {
          to: new Date()
        },
        pickerWrapperCss: {
          width: '100%',
          height: '30px',
          lineHeight: '30px',
          border: 'solid 1px rgb(232, 232, 232)'
        },
        calendarCss: {
          fontSize: '6px',
          color: 'red'
        }
      };
    }

**Comment by laxiry1** [comment]
<datePicker v-model="personInfo.bornDate" :language="language" :format="format" :disable="disabled"
                    :dplaceholder="holder" :calendar-class="calendarCss" :wrapper-class="pickerWrapperCss">
        </datePicker>

**Comment by charliekassel** [comment]
```
...
computed: {
   styleObject () {
      return {
         background: red
      }
   }
}
...
<datepicker :wrapper-class="styleObject"></datepicker>
```
