### ISSUE TITLE
Can i trigger open / close datepicker from method ?

### ISSUE THREAD

**Issue by ahmadadityakj** [charliekassel/vuejs-datepicker#244]
i want to trigger click open / close datepicker from method. At vue 2 i try to put ref at datepicker component  and try to trigger click it from method like code below but nothing happened.

at component                
`<datepicker` `ref="datepick"></datepicker>`

at method
this.$refs.datepick.click();

any suggestions ?

**Comment by charliekassel** [comment]
`this.$refs.datepick.showCalendar();`

Always best to look through the code.

**Comment by ahmadadityakj** [comment]
this.$refs.datepick.showCalendar();

that doesnt work @charliekassel ,

**Comment by pushkardeshmukh1992** [comment]
+1. Calling `this.$refs.datepick.showCalendar();` doesn't seem to be working.

Any way to achieve this behavior?

**Comment by Luke-Wilson** [comment]
I solved this issue by manually adding a `ref` attribute to the datepicker. 

In the below example, I have two datepickers. When a user selects a date from the first datepicker, I use the `closed` event emitter to call a method that opens second datepicker will open. I target the second datepicker using its `ref` name, "endDatePicker", and then calling its `showCalendar()` method.

```
<template>
  <div>
  	<datepicker
  		v-model='startDate'
  		ref="startDatePicker"
  		name='startDate'
  		@closed='openEndDatePicker()'
  	/>

  	<datepicker
  		v-model='endDate'
  		ref="endDatePicker"
  		name='endDate'
  	/>
  </div>
</template>

<script>
export default {
	data() {
		return {
			startDate: '',
			endDate: '',
		}
	},
	methods: {
		openEndDatePicker: function() {
			this.$refs.endDatePicker.showCalendar();
		},
	},
};
</script>
```

**Comment by adoniskrasniqi** [comment]
This seems to be working.
`this.$refs.dataPicker.showDatepicker = true;`

**Comment by StasGlebov** [comment]
open:
this.$refs.datepicker.popupVisible = true
close:
this.$refs.datepicker.popupVisible = false

**Comment by boi87** [comment]
do you guys know how to get this to work with TS? import that DatePicker

**Comment by jayeshtharwani** [comment]
**Open:**
this.$refs.datePicker.showCalendar();

**Close:**
this.$refs.datePicker.close();

**Comment by kevpug** [comment]
In your case, boi87 it should work even if you have the error. Just put @ts ignore before the line so there's no error. (Works for me)
