### ISSUE TITLE
Adding custom html to input (parsleyJS)

### ISSUE THREAD

**Issue by cansuB** [charliekassel/vuejs-datepicker#245]
Hi,
I am using pasrleyJS with the date picker and I need to add custom html elements ( e.g data-parsley-group="step-1") to input.  Whenever I add them like below
```
  <datepicker :disabled="datepickerDisabled" bootstrapStyling="true" :required="noStartDate==0" v-model="startDate" v-on:selected="onSelectProjectDate" placeholder="Select date"
                                    input-class="text-field datepicker hasDatepicker col-xs-12" id="datepicker" data-**parsley-trigger="change" data-parsley-group="step-1"** :value="startDate"
                                    name="start-date" ></datepicker>
```

It moves the custom elements to div like below

![untitled](https://user-images.githubusercontent.com/5920641/28962229-e5fdca52-78fc-11e7-9d8d-4d54c1434490.png)

Is there any way to add custom html element to input?

thanks

**Comment by charliekassel** [comment]
Sorry, currently no way to add custom attributes.
