### ISSUE TITLE
why calendar-class input-class have no effect

### ISSUE THREAD

**Issue by laxiry1** [charliekassel/vuejs-datepicker#248]
.pickerWrapperCss {
    width: 100%;
    height: 30px;
    line-height: 30px;
    border: solid 1px rgb(232, 232, 232);
  }
  .inputCss {
    width: 100%;
    text-align: right;
    color: red;
  }
  .calendarCss {
    width: 200px;
    background: red;
  }

`<datePicker
  calendar-class="calendarCss" 
  input-class="inputCss"
  wrapper-class="pickerWrapperCss">
</datePicker>`

the wrapper-class Normal display
![1](https://user-images.githubusercontent.com/29293618/29009908-e159a426-7b59-11e7-9bf0-30b0a77f76e0.png)

**Comment by laxiry1** [comment]
the wrapper-class Normal display

**Comment by charliekassel** [comment]
They are probably being overridden.
This is really a css question - you can ask this on stackoverflow.

**Comment by mlg-emma** [comment]
did anyone figure this out?

**Comment by mrsalitre** [comment]
SOLVED!

The problem begins when you declare your style tag as scope. If you don´t use the scope attribute everything works.
