### ISSUE TITLE
method showCalendar() doesn't work

### ISSUE THREAD

**Issue by ahmadadityakj** [charliekassel/vuejs-datepicker#249]
as you said before, to open datepicker from method without click it directly i use this code : 
at component
`<datepicker` `ref="datepick"></datepicker>`

at method
this.$refs.datepick.showCalendar();

that doesnt work @charliekassel , have you try it ? datepicker doesnt open / close by this function, nothing happened.

**Comment by charliekassel** [comment]
It's not designed to be used outside the component.

**Comment by hasankemaldemirci** [comment]
how can i show calendar manually?
