### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by bglaz** [charliekassel/vuejs-datepicker#25]
Anyone else getting this error?

**Comment by bhulsman** [comment]
It seems that it's not compatible with Vue 2.0. What version of Vue are you using?

**Comment by Donkfather** [comment]
yup same here. I am using Vue 2.0.3 . But why isn't it compatible ? vue-migration-helper says that "everything is migrated ( 80% )"

**Comment by bhulsman** [comment]
I think the `this.$el` calls are not valid anymore for 2.0.

**Comment by charliekassel** [comment]
This component was built for Vue 1.x - I have made some changes in 0.4.16 to help compatibility with 2.x and specifically remove this error.
I can see there are some warnings about prop modification that will require further changes. PR's are welcome!

**Comment by charliekassel** [comment]
Prop modification warn fixed in e5b600d.
