### ISSUE TITLE
format has no effect

### ISSUE THREAD

**Issue by DeanWard** [charliekassel/vuejs-datepicker#253]
I'm trying to change the format of the date to match what my API accepts but the component is ignoring the format prop

`<datepicker v-model="contact.date_of_birth" :inline="true" format="dd-MM-YYYY"></datepicker>`

Have I done something wrong here?

**Comment by charliekassel** [comment]
Format is for the input which is essentially a label as the value is a Date object.

What exactly are you trying to do?

**Comment by DeanWard** [comment]
Oh! My bad, then! I'm trying to control the output format that ends up being added to the model when the user picks a date. I ended up working around it by mutating it on the back end, though.

**Comment by charliekassel** [comment]
Yeah it should be a Date object in the v-model, so if you're sending to a backend server you'll need to format it like something: `date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2)` natively or use a library like moment to format it which would be much more sensible :)
