### ISSUE TITLE
Datepicker input box not showing

### ISSUE THREAD

**Issue by tanhs** [charliekassel/vuejs-datepicker#257]
Hi, 
I need some help.  The input box doesn't seem to be appearing.  I am not using app.js as it gives me problem with Buefy.  No error message on the debugging console.  Anything I did wrongly? Thanks.
`<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
         <link href="{{ asset('css/app.css') }}" rel="stylesheet">
          <script src="{{ asset('js/vue2.4.2.js') }}"></script>
          <script src="{{ asset('js/buefy0.4.6.js') }}"></script>
          <script src="{{ asset('js/axios.min.js') }}"></script>
    </head>
    <body>
      <div id="app">
          <hr>
      <div class="container">
          <datepicker name="test" placeholder="European Format ('d-m-Y')" :config="{ dateFormat: 'd-m-Y', static: true }"></datepicker>
      </div>
    </div>
        <script type="text/javascript">
            Vue.use(Buefy.default)
            var app = new Vue({
              el: '#app',
              components: {
              'datepicker': DatePicker
              },
              data: {
                name:'test'
              },
              methods: {
                }
            });
        </script>
    </body>
</html>
`

**Comment by charliekassel** [comment]
Sorry, I have no idea what Bueify is. Maybe best if you ask there.
