### ISSUE TITLE
:disabled-picker="true" only disabled the button not the calendar icon when set to true

### ISSUE THREAD

**Issue by jericopulvera** [charliekassel/vuejs-datepicker#263]
:disabled-picker="true" only disabled the button not the calendar icon when set to true

**Comment by robbiemu** [comment]
I'd like a solution that allowed us to specify an optional icon like:
```
<datepicker fi="fai" fo="fum">
  <div slot=icon><i class=whatever></i></div>
</datepicker>
```
That way we could style the icon dependently.

**Comment by charliekassel** [comment]
@jericopulvera - the calendar is disabled. I'm presuming you are just talking about css?
@robbiemu - you can specify the icon css class
