### ISSUE TITLE
i want add Mongolian PLS!!!! :((((. 

### ISSUE THREAD

**Issue by redaced** [charliekassel/vuejs-datepicker#264]
'mn': {
            'language': 'Mongolian',
            'months': {
                'original': ['1-р сар', '2-р сар', '3-р сар', '4-р сар', '5-р сар', '6-р сар', '7-р сар', '8-р сар', '9-р сар', '10-р сар', '11-р сар', '12-р сар'],
                'abbr': ['1-р сар', '2-р сар', '3-р сар', '4-р сар', '5-р сар', '6-р сар', '7-р сар', '8-р сар', '9-р сар', '10-р сар', '11-р сар', '12-р сар']
            },
            'days': ['Ня', 'Да', 'Мя', 'Лх', 'Пү', 'Ба', 'Бя']
        },

**Comment by charliekassel** [comment]
Hi, sure.
Please submit a pull request.

- Add above to the DateLanguages.js file
- Add the Language to the available languages in the readme file.
- Run `npm run lint` to make sure your code formatting is in line with the required code style.
