### ISSUE TITLE
Unable to change width/height of datepicker

### ISSUE THREAD

**Issue by thutch10** [charliekassel/vuejs-datepicker#267]
I am unable to figure out how to change the width/height of the datepicker.  If this functionality exists, then it would be helpful to have it in the documentation.

**Comment by thutch10** [comment]
I discovered that you can update the width/height of the datepicker with the following code:

```
.vdp-datepicker input{
    width: 75px;
    height: 20px;
}
```

**Comment by charliekassel** [comment]
This is basic css.
I offer only minimal styling so you can style the datepicker as you wish.

**Comment by thutch10** [comment]
The css is basic, but where you have to put it is not intuitive.  You have to dive into the code to figure out that the css needs to be on the .vdp-datepicker class.

**Comment by noobar** [comment]
It can be done by using `calendar-class`.

```html
<template>
  <datepicker class="my-datepicker" calendar-class="my-datepicker_calendar" />
</template>

<style scoped>
.my-datepicker >>> .my-datepicker_calendar {
  width: 100%;
  height: 330px;
}
</style>
```
