### ISSUE TITLE
the component can't support multi date select

### ISSUE THREAD

**Issue by RunningV** [charliekassel/vuejs-datepicker#270]
i like the datepicker very much, but i have a need to select several date or a phrase of time, it can not support, i read the source code just found it difficult to change to realize my need. any good idea to it?_**tks a lot**_
my idea: create a open and close method that i can use to show or hide the calendar table by self not just trigger by input focus.

**Comment by charliekassel** [comment]
Unfortunately this is outside of the scope of this project
