### ISSUE TITLE
monday-first gives warning in console log

### ISSUE THREAD

**Issue by focussing** [charliekassel/vuejs-datepicker#271]
No matter how it is specified; warning stays.

`<datepicker v-model="startDate" monday-first=true placeholder="Selecteer..." :selected="start()"></datepicker>`

or
`<datepicker v-model="startDate" monday-first="true" placeholder="Selecteer..." :selected="start()"></datepicker>`

Invalid prop: type check failed for prop "mondayFirst". Expected Boolean, got String.

**Comment by charliekassel** [comment]
You're passing it as a string.
You need to use this syntax to bind the JavaScript type. :monday-first="true"

**Comment by focussing** [comment]
OK thanks! that fixed it.
