### ISSUE TITLE
datepicker formatting

### ISSUE THREAD

**Issue by focussing** [charliekassel/vuejs-datepicker#273]
How can I format the datepicker for example like the Bulma input box?

[http://bulma.io/documentation/form/input/](http://bulma.io/documentation/form/input/)

**Comment by charliekassel** [comment]
Just use css

**Comment by focussing** [comment]
Now I know what you mean:

`<datepicker v-model="endDate" :monday-first="true" input-class="input" placeholder="Selecteer..." v-on:selected="end()"></datepicker>`
