### ISSUE TITLE
Datepicker use in table row

### ISSUE THREAD

**Issue by huyjack178** [charliekassel/vuejs-datepicker#274]
![image](https://user-images.githubusercontent.com/11793001/29654525-c743dd0a-88d7-11e7-894b-2af907cf1280.png)

I got this issue when use in table row, who can help me

**Comment by charliekassel** [comment]
This is due to conflicting css in your page.
The datepicker is absolutely positioned so being in a table does not affect it.

**Comment by robjbrain** [comment]
@huyjack178 did you ever resolve this? I'm having the same issue within a bootstrap table and it's not immediately clear that any css styles are causing it.

**Comment by robjbrain** [comment]
Found it.

My td had `white-space: nowrap;` 

Hopefully this helps anyone else finding this via Google :)
