### ISSUE TITLE
Passing event object

### ISSUE THREAD

**Issue by billyshena** [charliekassel/vuejs-datepicker#276]
Hello guys !

I currently have a <datepicker @selected="someFunction></datepicker> and would like to know if there is a way to get the event object (so I can use event.stopPropagation() for instance)
The @selected function is only sending the date as first parameter but I did not manage to pass the event object as an argument aswell.

Any ideas ?

Best

**Comment by charliekassel** [comment]
No sorry, the event object is not passed through.
