### ISSUE TITLE
How do I make it so it uses moment-timezone instead of the computers time?

### ISSUE THREAD

**Issue by jericopulvera** [charliekassel/vuejs-datepicker#278]
How do I make it so it uses moment-timezone instead of the computers time?

**Comment by ianrussel** [comment]
Having also the problem..

**Comment by charliekassel** [comment]
Internally the component uses javascript Date object.
If you want to format the way the date is displayed in the input value you can use the [function formatter](https://github.com/charliekassel/vuejs-datepicker#function-formatter)
