### ISSUE TITLE
v-model is not updated in "selected" event handler

### ISSUE THREAD

**Issue by focussing** [charliekassel/vuejs-datepicker#281]
`                <datepicker v-model="startDate" :monday-first="true" input-class="input" placeholder="Selecteer..." v-on:selected="doSelection()"></datepicker>
`

and

```
    methods: {
        doSelection: function() {
            console.log(this.startDate);
        },
    },
```
variable startDate is empty at the first date selection. Second time date is selected (for example different date) the firstly clicked date is shown on the console

**Comment by mikerodham** [comment]
According to your title, the issue is when the `v-on:selected` fires, it's not firing when the v-model updates? Can you try removing the parentheses from this part: `v-on:Selected="doSelection"` I found it also had issues when declaring it as a method, it should receive payload so inside the doSelection function type:
`doSelection: function( payload ) {
    console.log(payload)
}`

Then you should be able to play with it from there.

**Comment by charliekassel** [comment]
I believe this is because the `selected` event is fired before the Vue `nextTick` function which updates the v-model.
I'm sure if you do this, the second logging will have the value you expect:
```
doSelection: function() {
   console.log(this.startDate);
   this.$nextTick(() => console.log(this.startDate))
}
```

**Comment by focussing** [comment]
@mikerodham this is not working, without parentheses the function is not called

**Comment by focussing** [comment]
@charliekassel this works; can you update the datepicker to fix it?

**Comment by charliekassel** [comment]
No, this is the way Vue works, this is expected behaviour.
The event happens before Vue's internal state of the v-model is updated.

**Comment by focussing** [comment]
OK thanks!
Maybe you could update the documentation with this as an example?
That would help others as well.

**Comment by charliekassel** [comment]
Well I don't think this is specific to this component, it's more a quirk of Vue itself.

**Comment by focussing** [comment]
Even more reason to clarify this in the doc :)

**Comment by focussing** [comment]
... so others can use your great component successfully 👍
