### ISSUE TITLE
Range mode support

### ISSUE THREAD

**Issue by glutaminefree** [charliekassel/vuejs-datepicker#286]
Hi!
Great library! But does it support range mode? If no, do you planned to implement it?

**Comment by charliekassel** [comment]
No not yet.
I might if I was actually using this component from day to day as it's a pretty standard use case.

Maybe one day...

**Comment by BlitZz96** [comment]
I have created a range mode #532 that suited my needs, maybe it will be merged, if not, I'll host it on my github 🥂
