### ISSUE TITLE
How to not load in languages?

### ISSUE THREAD

**Issue by ndjamenamarmon** [charliekassel/vuejs-datepicker#290]
I am working on a project that is English-only, but all the other languages are being loaded up into our final code. Since codebase size is very important in this project, is there any way to not load up all the extra languages?

**Comment by charliekassel** [comment]
Not currently.
But the file is only 16kb, uglified and gzipped it would be next to nothing. I can't see much room for optimisation here to be honest.

**Comment by pinguinjkeke** [comment]
Why the issue is closed? It's really important to keep size small!
