### ISSUE TITLE
Calendar closes when click nexmonth button

### ISSUE THREAD

**Issue by dasbit** [charliekassel/vuejs-datepicker#292]
When click on next month button calendar closes, I want it open,

**Comment by dasbit** [comment]
I fixed it by             
```
changedMonth(){
    event.preventDefault();
}
```

**Comment by charliekassel** [comment]
Thanks for the heads up, but I'm not seeing this behaviour in the demo.

**Comment by R4YM3** [comment]
Got this issue two, this was because i had a label around the datepicker. 
Removing the label fixed the problem

**Comment by adrum** [comment]
@R4YM3 I ran into this same issue. I submitted a [pull request](https://github.com/charliekassel/vuejs-datepicker/pull/520) which fixes the issue.
