### ISSUE TITLE
Date formatting is inconsitent

### ISSUE THREAD

**Issue by websanova** [charliekassel/vuejs-datepicker#293]
I find the "format" and "value" fields are quite inconsistent.

For instance if I set the format to "dd-MM-yyyy", everything should work for this format.

Meaning if I set the value to "21-01-2017" it should get this value and it should also return the value in this format instead of the `Date` object. Otherwise I need to write two additional parsers around this. One for getting the value in and one for getting the value to proper format for a request to my API.

I think format should be fully consistent and if someone wants to deal with a `Date` object they can leave it `undefined` and perhaps offer an additional field 'display-format`.

**Comment by charliekassel** [comment]
In my mind they serve two different purposes - `format` is basically display format.
I don't necessarily want to format the dates in the input display in the way I have to persist it so having the output as a Date object allows you to format it for that requirement, else you will need to parse it again.

**Comment by websanova** [comment]
That's what I mean, so maybe another parameter for full consistent formatting, so if it's null just leave the date object. If it's all auto parsed.

**Comment by charliekassel** [comment]
I don't see this as inconsistent - it's two separate properties.
One an object and the other a formatted string from that object, only used for display purposes.

**Comment by websanova** [comment]
Well, it seems to accept yyyy-MM-dd format so I will just go with that for now.
