### ISSUE TITLE
Release with Catalan Language

### ISSUE THREAD

**Issue by xevicos** [charliekassel/vuejs-datepicker#297]
Hi,

Can you please release a version with the new language?

Thx.

**Comment by charliekassel** [comment]
Hi @xevicos , sorry for the wait!

Available from v0.9.12

**Comment by xevicos** [comment]
Thx, but after this release, in all languages appears a **"> …** before the input.

**Comment by charliekassel** [comment]
Thanks for the heads up!

fixed in v0.9.13
