### ISSUE TITLE
Demo is not working in Chrome.

### ISSUE THREAD

**Issue by pulekies** [charliekassel/vuejs-datepicker#298]
The demo link does not work in Chrome (at least on my macbook). Note that it does work in Safari. I'm not sure if this is a webpackbin or vuejs-datepicker issue. 

Repro: 
Open the demo link in chrome (https://www.webpackbin.com/bins/-KhQbtTSVuU6r8VCrIdC). 

Expected: 
No errors, the demo is usable. 

Actual:
Uncaught ReferenceError: dll_bundle is not defined
    at Object.<anonymous> (template.vue:18)
    at __webpack_require__ (bootstrap b9aec398db70e8089bb4:19)
    at Object.defineProperty.value (main.js:3)
    at __webpack_require__ (bootstrap b9aec398db70e8089bb4:19)
    at __vue_styles__ (bootstrap b9aec398db70e8089bb4:65)
    at main.js:69

**Comment by misha130** [comment]
Demo aint working on firefox either

**Comment by emielmolenaar** [comment]
Confirmed here in Chrome on Linux.

**Comment by wheatevo** [comment]
The demo is also not working for me in Chrome on Windows.

**Comment by huangche007** [comment]
The demo is not working for me too

**Comment by pulekies** [comment]
The issue still repros for me, and a lot of other people seem to have been running into it. Why close it? @charliekassel

**Comment by charliekassel** [comment]
there's a new demo in the readme

**Comment by pulekies** [comment]
Sorry, just looked at the new docs and saw it was working. Thanks!
