### ISSUE TITLE
How to use css for input of vuejs-datepicker.

### ISSUE THREAD

**Issue by hyeokluv** [charliekassel/vuejs-datepicker#300]
refs does not work.

In what ways can I apply css to the input of a vuejs-datepicker?

**Comment by charliekassel** [comment]
Use the inputClass prop.
It’s mentioned in the readme.

**Comment by udittehri** [comment]
You can use 


1. calendar-class | String\|Object |   | CSS class applied to the calendar el
2. input-class | String\|Object |   | CSS class applied to the input el
3. wrapper-class | String\|Object |   | CSS class applied to the outer div
