### ISSUE TITLE
How do you return a date instead of a date time format?

### ISSUE THREAD

**Issue by ChadTaljaardt** [charliekassel/vuejs-datepicker#303]
Hello, 

The picker is returning a date in the format of : 2017-09-12T09:20:00.000Z. 

How do i make it use a specific format such as YYYY[-MM[-DD]]
I would like to do this without using Moment if possible?

Thanks

**Comment by charliekassel** [comment]
It returns a Date object. Above is the string representation.
You can format the Date object anyway you like using native methods:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
