### ISSUE TITLE
Error with :clear-button="true

### ISSUE THREAD

**Issue by tracid** [charliekassel/vuejs-datepicker#305]
Since Version 0.9.14 I get an Error with the enabled clear-button (:clear-button="true"):

> Cannot read property length of undefined

I think it originates in src/components/Datepicker.vue line 26.

Thanks for the nice Component :)

**Comment by e-ts** [comment]
Setting `clear-button-icon` to an empty string seems to be a work around for now.

**Comment by snovakovic** [comment]
@tracid I have open PR for fixing this issue it will be resolved once PR is merged so you can take a look at 
 PR #307
