### ISSUE TITLE
this.$dispatch is not a function(…)

### ISSUE THREAD

**Issue by retrogradeMT** [charliekassel/vuejs-datepicker#31]
I'm using vue 2.0.3 and just testing the most basic setup, upon clicking in the input box, I get an error:  Uncaught TypeError: this.$dispatch is not a function(…)

**Comment by charliekassel** [comment]
I'm attempting to support both Vue 1.x and 2.x at the moment.
Having said that I'm happy to remove the $dispatch functionality as it has been replaced by $emit and I will do on the next release.
I'll leave this ticket open until I release that change.

**Comment by charliekassel** [comment]
should be fixed in b998474
