### ISSUE TITLE
display days of previous/next month

### ISSUE THREAD

**Issue by mlg-emma** [charliekassel/vuejs-datepicker#317]
Hi! is there currently a way to fill each row of the calendar by displaying the days of the previous or next month? For example: 

![datepicker](https://user-images.githubusercontent.com/20781637/31153905-879148fa-a858-11e7-9774-ace47227db77.png)

Is it possible to display days 1, 2, 3, 4 of the following month? (They would be disabled but hopefully there's a way they can still be displayed).

Thanks for your work!

**Comment by mlg-emma** [comment]
Forked the repo and added! Thanks again 👍

**Comment by charliekassel** [comment]
Hi, sorry I didn't get around to this.
I had originally built it with this design and have considered adding an option to support this, but decided against it to keep the code cleaner.
I think it's one of those design choices that you either go with or not - but if you have a clean implementation it would be nice to see.

**Comment by mlg-emma** [comment]
No worries! Yeah I see what you mean though, your code to add the correct # of blank cells at the beginning of the month was very clean. Adding the extra days does complicate things--my implementation now is not as neat as yours, but if get around to refining it I'll let you know :D 
Thanks again

**Comment by Daniyal83** [comment]
Can you please tell me how you fixed that? I need the same style with days of prev and next months.
