### ISSUE TITLE
Can we define start and end date of calender

### ISSUE THREAD

**Issue by msajjadk** [charliekassel/vuejs-datepicker#319]
I want to use the calendar in date of birth field, how can I set the calendar back to 17 years

**Comment by charliekassel** [comment]
There's no setting for this right now, but I can see it being useful - I believe someone else has asked for this.
Something like an initial date property.

**Comment by gbgb66** [comment]
setUpDate() {
                this.startDate = moment().startOf('month').format()
                this.endDate = moment().endOf('month').format()
            },

**Comment by msajjadk** [comment]
Can you please add this functionality to the calander, this will really
help the developers.
 one more thing can we add a drop down list of year to calander.?

**Comment by msajjadk** [comment]
Thanks for your response,

where to use the given method

setUpDate() {
this.startDate = moment().startOf('month').format()
this.endDate = moment().endOf('month').format()
},
I just want to specific date ranges in calander
ᐧ
