### ISSUE TITLE
Feature Request. Accept functions to disable / highlight dates

### ISSUE THREAD

**Issue by vijayanandnandam** [charliekassel/vuejs-datepicker#321]
Current implementation of disabling / highlighting dates does not have an option to add custom logic.
One way is to give ability to add custom function like 
```
disabled: {
  custom: function(date){
    if(date.getDate()/10 == 1){
      return true;
    } else {
      return false;
    }
  }
}
```

**Comment by charliekassel** [comment]
Looks good @vijayanandnandam  - happy to accept a PR on this.
