### ISSUE TITLE
how to open calendar manually

### ISSUE THREAD

**Issue by hasankemaldemirci** [charliekassel/vuejs-datepicker#325]
how can i open calendar manually?

**Comment by samayo** [comment]
What do you mean manually? You just click on the field, or give it a class, target the class and trigger a click event

**Comment by charliekassel** [comment]
I think you mean programatically @hasankemaldemirci ?

**Comment by alioygur** [comment]
@samayo @charliekassel Actually we want an API to Open/Close the calendar without click the input.

**Comment by alioygur** [comment]
mallar anlamiyor haso'cum

**Comment by hasankemaldemirci** [comment]
manually yerine emmanually mi deseydik ne yapsaydık anlamadım ki :)

**Comment by ImpossivelPT** [comment]
I'm also looking for a way to open it programatically

**Comment by anthdm** [comment]
`this.$el.querySelector('yourAssignedClass').click()`

**Comment by samayo** [comment]
Basically what I said

**Comment by ianwalter** [comment]
Better solution: add `ref="datepicker"` to `<datepicker />` and then:
```js
this.$refs.datepicker.$children[0].$emit('showCalendar')
```
You can also emit `closeCalendar` to close the calendar.

**Comment by danieldiazbc** [comment]
This should be the best solution:

add `ref="datepicker"` to your `<datepicker/>`

and then call the openPopup function

`this.$refs.datepicker.openPopup()`
