### ISSUE TITLE
v-model 2017-10-20T16:00:00.000Z to 2017-10-20

### ISSUE THREAD

**Issue by jericopulvera** [charliekassel/vuejs-datepicker#329]
Is it possible to have YYYY-MM-DD format in binded data?

**Comment by charliekassel** [comment]
It binds a Date object which I would argue is infinitely more flexible than a formatted string.

**Comment by Soliman** [comment]
Is this an acceptable workaround? https://codesandbox.io/s/p57yo44x9x
