### ISSUE TITLE
how can i get the date from datepicker

### ISSUE THREAD

**Issue by qianL93** [charliekassel/vuejs-datepicker#33]
just like attribute : v-model in vue

**Comment by jondcampbell** [comment]
I am also wondering this.
If I use v-on:selected="doSomethingInParentComponentFunction"
that function will know the value, but it won't know what particular date field we are even dealing with.

**Comment by CSWilson** [comment]
I too am trying to get data back out of the datepicker, I'm trying to get the "formattedValue" out.

**Comment by charliekassel** [comment]
@qianL93 the datepicker emits an event when a date is selected. If you listen for that event `selected` you can modify the prop passed in to the component.

@jondcampbell you can give each datepicker component a unique name, this name gets appended to the selected event it emits. Have a look at the webpackbin example on Events.

@CSWilson as long as you pass in the format as a prop you can format the date object that the component emits when selected with the same format. Maybe you can separately import the DateUtils.formatDate() method from utils?

**Comment by charliekassel** [comment]
I'm closing this issue if everyone is happy?

**Comment by cashlion** [comment]
I've added a name property to my datepicker but it does not come through in any of the events.

`<datepicker name="test"></datepicker>`

![image](https://cloud.githubusercontent.com/assets/4511652/24202078/fda175e6-0edf-11e7-91df-3279d58b5259.png)

What am I doing wrong?

**Comment by charliekassel** [comment]
payload[0] ?

**Comment by cashlion** [comment]
Is the name attribute not also supposed to come through? Say we have multiple instances of a datepicker within our form, like for a date range, how are we to know which input the event came from?

**Comment by gopal-g** [comment]
I achieved this with listening to the events on the reference, But still not the ideal thing i would like to do.

In my template / HTML
```
<datepicker
 name="d1"
 format="dd/MM/yyyy"
 input-class="form-control"
 placeholder="Select Date"
 ref="datepicker1"
>
</datepicker>

<datepicker
 name="d2"
 format="dd/MM/yyyy"
 input-class="form-control"
 placeholder="Select Date"
 ref="datepicker2"
>
</datepicker>

```

In my Vue instance ...

```
new Vue({

 el: '#application_form', 

 mounted() {

         this.$refs.datepicker1.$on('selected', (date) => {
             console.log('Date 1 changed', date);
         })

         this.$refs.datepicker2.$on('selected', (date) => {
             console.log('Date 2 changed', date);
         })
     },
 });
```
