### ISSUE TITLE
Deactivate day view - only ask for year and month

### ISSUE THREAD

**Issue by Twisterking** [charliekassel/vuejs-datepicker#333]
Is there any way to disable displaying the day view and only ask the user for a year and month?
I would desperately need this - e.g. for "I went to school from X to Y" - no days needed here, only months.

Even better would be maybe to be completely flexible in which views are displayed:
- **year only** - just return 1st of January of that year
- **year and month** - return first of month
- (default) **year, month and day**

Is anything like this maybe already implemented or in the works? Thanks!

**Comment by charliekassel** [comment]
This can now be done.
I have merged https://github.com/charliekassel/vuejs-datepicker/pull/327 and it's available from v0.9.19
