### ISSUE TITLE
Except condition

### ISSUE THREAD

**Issue by JakeDK** [charliekassel/vuejs-datepicker#334]
I would be very useful to have all dates disabled except some specific dates in an array og range.

Help you be much appreciated. :)

**Comment by vijayanandnandam** [comment]
@JakeDK look into the documentation. You can add a custom function in disabled options with key `customPredictor` where you can  disable all dates except a few.

https://github.com/charliekassel/vuejs-datepicker#disabled-dates

**Comment by JakeDK** [comment]
@vijayanandnandam Thanks for the answer! but is it also possible to add a array of date into that function?

**Comment by vijayanandnandam** [comment]
@JakeDK Most possible way to is to query the state like `vuex` into that function.

**Comment by JakeDK** [comment]
Yes that would properly work, thanks a million! and thanks for this awesome date-picker.
It would be nice if it was possible to added an array of dates into a function like this: http://jsfiddle.net/yXMKC/4/

Let me know if I can buy/donate you a beer ;)
