### ISSUE TITLE
Show multiple months

### ISSUE THREAD

**Issue by thom-ass** [charliekassel/vuejs-datepicker#343]
Is there any way to show multiple months inline like this?
I only know jquery-ui datepicker, but i want to get rid of jquery stuff

![screen shot 2017-11-06 at 12 44 09 pm](https://user-images.githubusercontent.com/4485489/32426990-6b575988-c2f0-11e7-954f-0af38b1b1977.png)

**Comment by charliekassel** [comment]
Not as a single component.

**Comment by Ethaan** [comment]
@thom-ass did you get something to make this work? on `datepicker` this option is called, `numberOfMonths`

**Comment by kikky7** [comment]
I am also looking for something similar; 3 months shown in inline datepicker instead of selected month.

Did anyone find a solution for this?

I don't want to go with jQuery library and plugin on this, but I think currently that's the only ready-to-go solution
