### ISSUE TITLE
date_format validating correct date format incorrectly.

### ISSUE THREAD

**Issue by tmacintosh** [charliekassel/vuejs-datepicker#349]
I have a datepicker component that I use in my templates like this:
```
<datepicker 
       v-model="toDate" 
       v-validate="toDateValidator"
       name="To Date"
       data-vv-name="To date"
       :propClass="this.$validator.errors.has('To Date') ? 'input-validation-error' : ''"
       :propDate="toDate" 
       :includeTime="true" 
       @input="toDate = $event">
</datepicker>
```
the v-model property is a string that conforms to the default moment format: `"YYYY-MM-DDTHH:mm:ssZ"` which actually looks like `"2017-11-08T19:00:00-08:00"`

the v-validate object toDateValidator is defined like this:
```
get toDateValidator(): any {
       return {required: true, date_format: 'YYYY-MM-DDTHH:mm:ssZ', after: this.fromDate }
 }
```

When I call `this.$validator.validateAll()` the date_format validation passes correctly. I can change the date on the datepicker and again the date_format passes validation.

The issue I am faced with is if the utcOffset is changed to something different from what was set initially say `"2017-11-09T16:00:00+13:00"` the validation of the string will fail.

When the utcOffset is changed I have tried resetting the validator like so: 

```
this.$validator.errors.clear();
this.$validator.reset();
this.$validator.pause();
setTimeout(() => {
      this.$validator.resume();
}, 400);
```

I can see the aria-invalid attribute equals false, but as soon as I call validateAll() it fails.

Is there something I'm doing wrong here.

**Comment by tmacintosh** [comment]
Would be great to get a response to this, thanks in advance.

**Comment by charliekassel** [comment]
try using a Date object in v-model instead of a string.

**Comment by tmacintosh** [comment]
Thanks for the reply, I actually realised this is more an issue to do with the vee-validate rather than vuejs-datepicker. Sorry...
