### ISSUE TITLE
Works with VueJS 2?

### ISSUE THREAD

**Issue by adrianosaaquino** [charliekassel/vuejs-datepicker#35]
On change to vue 2, examples not works.

Changed "ready" to "mounted" and 

<select v-model="format">

removed "selected" from first element.

**Comment by charliekassel** [comment]
It should work.

Can you confirm what version of the datepicker you are using?

**Comment by chopoti** [comment]
Experience the same issue as adrianosaaquino

**Comment by charliekassel** [comment]
Can you confirm what version of the datepicker you are using please?
Also what errors you are seeing?

**Comment by chopoti** [comment]
@charliekassel this version "vuejs-datepicker": "^0.4.21", and the problem is date change doesn't bind, it is always return current date or default if you pass it.

**Comment by gborcherds** [comment]
You need to specify a callback to update the date for Vue2. For example I did the following:

`
<datepicker :value="mydate" :inline="true" v-on:selected="setDate"></datepicker>
`

Then in my methods for my root instance, I added the following.

`
setDate(val) {
  this.mydate = val;
`

The binding in components is one way, see https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow

In his plugin he is doing $emit.('selected', dateSelected) and that's how you can set the date in your parent component/app.

Hope this helps. 

One question though, shouldn't your dependencies be updated to say vue ^2.0. When I loaded the plugin initial, it loaded a whole version of vue 1. I don't know enough builds to be sure, but thought I'd check.

**Comment by stephantabor** [comment]
I don't think it needs vue as a dependency at all.

**Comment by charliekassel** [comment]
You are actually correct @stephantabor 

I've moved vue to devDependency as of v0.5.2
