### ISSUE TITLE
Add option to disable future dates

### ISSUE THREAD

**Issue by mathiasha** [charliekassel/vuejs-datepicker#352]
Is there an option to make sure the user can't select dates in the future?
I imagine there would also be a need for the opposite, eg. not selection dates in the past.
This would obviously have to update along with the current date.

**Comment by charliekassel** [comment]
Yep.
Look at `disabled.from` in the readme

**Comment by bhavinjr** [comment]
@mathiasha  you can use like that
```
<datepicker :disabledDates="state.disabledDates"></datepicker>

in script

export default {
              data () {
                         return {
                                   state : {
				              disabledDates: {
					                   from: new Date(),
				              }
			           }
                         }
             }
}
```

**Comment by begueradj** [comment]
How to do the same in Vuetify date picker ?

**Comment by adrianmann** [comment]
Should we need to set `use-utc` to true here to avoid any issues?
