### ISSUE TITLE
Developer laptop paths in distributed files

### ISSUE THREAD

**Issue by thiderman** [charliekassel/vuejs-datepicker#357]
![in devtools](https://i.imgur.com/yqPWmG7.png)

So, when using this nifty component I get this error popping up every now and again. I've only seen it in the Firefox devtools, and the component still gets styled properly, so I'm fairly certain this wouldn't bother production.

I'm guessing this is caused by a misconfiguration in the building steps, and unfortunately I don't really have any good idea on how to fix it. Pretty sure the `/Users/[...]/` part isn't supposed to be there, anyway. 🙂 

In the distributed files (installed recently, this can be found some 48000 bytes into the file `dist/build.js`:
```
{version:3,sources:["/Users/charlie.kassel/Server/sites/vuejs-datepicker/src/components/Datepicker.vue"],
[...]
```

**Comment by charliekassel** [comment]
Thanks for the heads up!

Fixed in ee3e25f
