### ISSUE TITLE
An option to use buttons "Ok" and "Cancel"?

### ISSUE THREAD

**Issue by cassiohalmeida** [charliekassel/vuejs-datepicker#358]
Hi, first of all, thanks for the awesome work!

I have one question/idea. Some date pickers have an option to use buttons to confirm if the date is "ok", check the attached image for example:

![240cbf77-8e15-4399-b03f-65fda33a26a8](https://user-images.githubusercontent.com/6843340/33089858-1a3fca86-ced9-11e7-8d7e-4e082a2e766c.jpg)

The date will be selected only when the user clicks on "Ok". Is there any way to do it today?

What do you think? Is that a good idea? I think it will help developers and designers.

**Comment by charliekassel** [comment]
It's not possible to do this right now.
This would require an extra click from the user so I'd prefer to keep it as is at the moment.
