### ISSUE TITLE
Different format between value in input and vue data.

### ISSUE THREAD

**Issue by youyi1314** [charliekassel/vuejs-datepicker#359]
In my vue data it show :( format is what i want (DD/MM/YYYY) Nov 01 2017 in moment)
![image](https://user-images.githubusercontent.com/8391468/33197891-f444ddac-d122-11e7-9376-5fa1c6b0d735.png)

In my input value show diffrent format (MM/DD/YYYY) Jan 11 2017 in moment
![image](https://user-images.githubusercontent.com/8391468/33197934-1c0c1b5c-d123-11e7-81f8-84a2dd4190aa.png)

My Code Below:
**Vue Template**
`<datepicker id="edit-join_date" :value="editForm.join_date" placeholder="d/m/Y" @selected="onDateSelect" inputClass="form-control" :format="format" required></datepicker>`

**Vue Data**
`editForm: { join_date: moment('2017-11-01 00:00:00').format('DD/MM/YYYY') },` //Value from database set at axios response. default value is null (The screenshot upside is after data set.)

**Vue Methods**
onDateSelect(date){
console.log(date) //
                this.editForm.join_date = moment(date).format('DD/MM/YYYY'); // 
 },
format (value) {
console.log(value) // Wed Jan 11 2017 00:00:00 GMT+0800 (+08)
                return moment(value).format('DD/MM/YYYY') 
 },

when i want to change that date, it detect at correct format(DD/MM/YYYY) as Jan 11 2017
![image](https://user-images.githubusercontent.com/8391468/33198179-7f702930-d124-11e7-999e-eebb63aecfcc.png)

thanks and wish can understand what i facing currently.

**Comment by xurshid29** [comment]
Same problem

**Comment by charliekassel** [comment]
This is because you are initiating the component with a string.
The datepicker component uses javascript's Date object internally so needs to convert the string to a Date object.
As you can see when you type into the console:
```
new Date('01/11/2017')
Wed Jan 11 2017 00:00:00 GMT+0000 (GMT)
```
It is better to pass the component a Date object - or if you are using moment, just: `moment('2017-11-01 00:00:00')`

**Comment by smplyjr** [comment]
Any solution this 2019? I'm having the same problem. The format works fine but the result is different.
![vuejs-datepicker-issue](https://user-images.githubusercontent.com/16571669/53740731-cec9e100-3ecf-11e9-931b-720ce98a313e.png)

Reference(s):
#329 
https://github.com/ridewn/vue-date-picker/issues/3#issuecomment-329007983

**Comment by ChewySalmon** [comment]
I found an alternative approach to formatting the bound Vue model variable.

Using the native Date instance, you can do the following as a workaround:

`<datepicker id="datepicker" @input="formatPicker()" v-model="trackedDate" :format="dateFormat"></datepicker>`

As you can see  in the above, I've defined an event emit dubbed 'formatPicker' for when input is received. This is handled by a method defined within my Vue app as seen below:

```
methods: {            
	formatPicker: function(){
		var self = this;
		var d = new Date(self.trackedDate);
		self.trackedDate =  d.getUTCDate() +"/"+ (d.getUTCMonth()+1) +"/"+ d.getUTCFullYear();
	},
}
```
Using the native functionality of Date, you can manually define the format as seen above. This will result in the `trackedDate` variable matching that of my defined format (`'dd-MM-yyyy'`).  Of course these can be swapped out to match your own.

Assuming you've established the format you want using the :format property, you'll now have both the format (in the picker) and the date you want following user input/selection.

For clarity, the `dateFormat` variable defined within the `:format` property of the `<datepicker>`, is a string assigned within the data component of the Vue app (e.g. `'dd-MM-yyyy'`).
 
Hopefully this helps as a temporary workaround!

**Comment by silvesterwali** [comment]
i have same issue.. @ChewySalmon  but still same after change the date
