### ISSUE TITLE
 The data property "language" is already declared as a prop. Use prop default value instead.

### ISSUE THREAD

**Issue by tunele** [charliekassel/vuejs-datepicker#365]
I get this error when I use it in my project.
How can I fix it?

**Comment by tunele** [comment]
my fault.

**Comment by sdudnic** [comment]
please write an explanation, so the others searching for the same subject find an answer

**Comment by tunele** [comment]
Sorry this is from 3 years ago, I really cannot remember right now. I'll write an explanation next time.
