### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by namsir** [charliekassel/vuejs-datepicker#369]
Would love to have the calendar attach to the body so we can control the position anywhere on the screen/window. I did a little hack to get it working and here is what i did.

I set the id of the component via   id="timeframe"

let calendarInput = document.getElementById('timeframe');
                let topValue = calendarInput.getBoundingClientRect().top;
                let inputHeight = calendarInput.clientHeight;
                let inputMarginLeft = window.getComputedStyle(calendarInput).marginLeft;
                let calendar = this.$refs.thisdate.$vnode.elm.childNodes[2];
                let moveTo = Number.parseFloat(topValue) + Number.parseFloat(inputHeight);
                if(typeof calendar.setAttribute === "function"){
                    calendar.setAttribute("style", "top: " + moveTo + "px; left: " + inputMarginLeft);
                    document.body.appendChild(calendar);
                }

**Comment by charliekassel** [comment]
Couldn't you just do this in css?

Make the `vdp-datepicker` position: inherit then position the `vdp-datepicker__calendar` whereever you want.

**Comment by charliekassel** [comment]
Closing as I don't think I'm going to support this.
