### ISSUE TITLE
Vue 2.5.11 warn

### ISSUE THREAD

**Issue by rasko-lazic** [charliekassel/vuejs-datepicker#375]
Since Vue has added spelling check for the component props  [(vuejs/vue@`d02bb37`)](https://github.com/vuejs/vue/commit/d02bb37efb3c4ee14b8cf9db22d1ab3340ba2c0f), the following props have are now throwing a warn

```
[Vue warn]: Invalid key "value" in validation rules object for prop "name".
[Vue warn]: Invalid key "value" in validation rules object for prop "id".
[Vue warn]: Invalid key "value" in validation rules object for prop "format".
[Vue warn]: Invalid key "value" in validation rules object for prop "language".
[Vue warn]: Invalid key "value" in validation rules object for prop "fullMonthName".
```
As you can see, value keys should be removed.

**Comment by zhangyuan** [comment]
I also got the issue. Should `value` be renamed to `type` ?

**Comment by rasko-lazic** [comment]
Oh I forgot to update this issue, I checked the source files on git and in my local version, the problem was that I didn't update the package, this issue has been fixed three months ago...

**Comment by zhangyuan** [comment]
My bad. I was working on an old project and trying to locating the problem but checking the old version. But when I opened the code from master, it has been fixed...
