### ISSUE TITLE
v-model incorrect date

### ISSUE THREAD

**Issue by BrunoPignatari** [charliekassel/vuejs-datepicker#376]
Hi !!
Thanks for the project, very good, but I'm having a difficulty, when I put date () -> value: '2017-12-29' the return of the v-model in the tag is the previous day 2017-12-18, any report of this?

**Comment by BrunoPignatari** [comment]
v-model datepicker

29 Dec 2017
<datepicker placeholder="Select Date" v-model="vmodelexample"></datepicker>
2017-12-30

https://codesandbox.io/s/p92k8l717

v-model value for 
vModelExample: '2017-12-30'

**Comment by charliekassel** [comment]
This is the way javascript builds the date object from a yyy-mm-dd string.

You can pass a ready created Date object in your timezone instead.

> dateString
String value representing a date. The string should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601).
Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by BrunoPignatari** [comment]
Thx for help me…. Solutions ok moment.js


;)



De:  charliekassel <notifications@github.com>
Responder para:  charliekassel/vuejs-datepicker <reply@reply.github.com>
Data:  sexta-feira, 22 de dezembro de 2017 12:04
Para:  charliekassel/vuejs-datepicker <vuejs-datepicker@noreply.github.com>
Cc:  Bruno Pignatari <bruno@triangtec.com.br>, Author <author@noreply.github.com>
Assunto:  Re: [charliekassel/vuejs-datepicker] v-model incorrect date (#376)


This is the way javascript builds the date object from a yyy-mm-dd string.

You can pass a ready created Date object in your timezone instead.

dateString
String value representing a date. The string should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601).
Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/charliekassel/vuejs-datepicker","title":"charliekassel/vuejs-datepicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/charliekassel/vuejs-datepicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@charliekassel in #376: This is the way javascript builds the date object from a yyy-mm-dd string.\r\n\r\nYou can pass a ready created Date object in your timezone instead.\r\n\r\n\u003e dateString\r\nString value representing a date. The string should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601).\r\nNote: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. \"1970-01-01\") are treated as UTC, not local.\r\n\r\n\r\nhttps://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date"}],"action":{"name":"View Issue","url":"https://github.com/charliekassel/vuejs-datepicker/issues/376#issuecomment-353604204"}}}
