### ISSUE TITLE
Disabled attribute having unintended consequence

### ISSUE THREAD

**Issue by brenjt** [charliekassel/vuejs-datepicker#379]
Because of the datepicker component requires are disabled attribute for disabling dates it sends false positives to other components that use the datepicker. Specifically validators. While using vee-validator it thinks the datepicker is disabled because of that property being improperly used.

```
/// Vuejs-datepicker
<datepicker :class="{'has-error': errors.has('date')}" :disabled="disabled"></datepicker>

disabled: {
    customPredictor: function (date) {
        // disables every day of a month which is a multiple of 3
        return date < new Date();
    }
}

/// Vee validator, accesses the disabled flag as would most any other validator plugins
prototypeAccessors$1.isDisabled.get = function () {
  return !!(this.component && this.component.disabled) || !!(this.el && this.el.disabled);
};
```

I'd recommend renaming the following props:

    /// To disable the picker rename it like so
    disabled-picker -> disabled

    /// To disable specific days rename disabled to:
    :disabled-days="disabledDaysConfig"

**Comment by julesbloemen** [comment]
Hi @brenjt . I'm having the same issue. Did you found a workarround for this?

**Comment by brenjt** [comment]
@julesbloemen Yeah, I downloaded the source code in to my project and modified the files temporarily. I renamed ```disabled-picker``` to ```disabled``` and used ```disabled-days``` in place of the original ```disabled```. 

Once the issue is fixed I'll be removing the source files from my project. I should probably just make a pull request.

**Comment by julesbloemen** [comment]
@brenjt Thanks,
I manage to solve this. To put the datepicker in a own component. So it does validate my component instead of this one. (also needed support for typing).

But thanks!

**Comment by RScanlan1990** [comment]
@brenjt hey mate I'm having the exact same issue do you have an example of how you nested the date picker so that it can be validated?

Also i think the repo should be updated by @charliekassel to reflect @brenjt  changes.

**Comment by morinel** [comment]
Yes, same problem here. I solved it by removing the disabled attribute...

**Comment by NickWhiu** [comment]
Yeah this is bad design choice by overriding a default attribute of HTML. Please consider changing the attribute names.

**Comment by charliekassel** [comment]
I think there is definitely some misunderstanding here.
Props !== attributes.
Even though you pass them to the component in the same way as you assign an attribute, when a prop and it's data is passed to a component Vue parses and evaluates this and applies it to the component class but does not render it into the DOM, therefore there is no `disabled` attribute, as there is no `datepicker` html element of course.

**Comment by charliekassel** [comment]
This should be resolved in v1
