### ISSUE TITLE
plural optional

### ISSUE THREAD

**Issue by ayaz323** [charliekassel/vuejs-datepicker#394]
Hey, thank for good component, we  have litte bit problem we dont use plural "'s"  so can you make this optional ?
https://imgur.com/a/i6ZsC

**Comment by Flur3x** [comment]
Yes, please! I was about to say the same. It doesn't make any sense in Germany, for instance. Just "2010" would be fine instead of "2010's".

If it's only there for English, why not just remove it? Or maybe integrate it to the language config? :)

**Comment by charliekassel** [comment]
This is resolved in 7832344
