### ISSUE TITLE
Include in Vanilla JS project?

### ISSUE THREAD

**Issue by akinhwan** [charliekassel/vuejs-datepicker#395]
Would it be possible to use this datepicker component in a vanilla js project?
I am currently using jquery datepicker and the behaviour seems to be almost identical, it is just the default styles that appear to be the difference.

**Comment by charliekassel** [comment]
Not really.
Although it would be a good idea to abstract the datepicker logic to plain javascript and make this a Vue wrapper for it.
Unfortunately not in my immediate plans though.
