### ISSUE TITLE
Don't load all languages - reduce build size by creating a config to specify only the needed locales

### ISSUE THREAD

**Issue by feliperaul** [charliekassel/vuejs-datepicker#401]
To reduce build size, it would be nice if we could install languages optionally. I only need 2 locales from the list, but my bundle is going to include them all. How to achieve this?

**Comment by charliekassel** [comment]
There's currently no way to do this.
I'm not sure what the best approach for this would be as this would require you to bundle the library.

**Comment by elpete** [comment]
While not insignificant, removing all but one language only saved 15 kb.  It's still 41 kb for just English.

**Comment by BlitZz96** [comment]
I like the way [moment.js](https://momentjs.com/) has solved this: [Image](https://i.gyazo.com/8097eca7c8b32a66b3ce981f1e35245d.png)

The way I remove unused languages is by simply using the ContextReplacement plugin from webpack to select the folders where the locale is placed. (not optimal, but gets the job done)

```
plugins: [
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /nb|en-gb|pl|de|ru|lt|lv/) 
],
```
Maybe this could be an alternative?

**Comment by charliekassel** [comment]
I'm considering building each language as a separate file then they can be imported individually by the user at the time of importing the datepicker component.

**Comment by charliekassel** [comment]
Yeah pretty much - maybe `en` would be imported by default by the root component.

**Comment by charliekassel** [comment]
This should be resolved in v1
