### ISSUE TITLE
Source mapping in dest build [npm]

### ISSUE THREAD

**Issue by dikant** [charliekassel/vuejs-datepicker#407]
Hi,
can you remove source mapping in production dist?
there is mapping in `/dist/build.js` ( version 0.9.25 )
- `sourceMappingURL=build.js.map` which is non existing file
- CSS mapping to file `/Users/charlie.kassel/Server/sites/vuejs-datepicker/src/components/Datepicker.vue` with full mapping (almost 5kB)

mapping is good only for development, in production build it's useless bytes

**Comment by dikant** [comment]
i remove it in my fork https://github.com/dikant/vuejs-datepicker/commit/72c1e8c2f9a4123644b439d5bd109696fb8b7f8b

**Comment by charliekassel** [comment]
Ok, I've removed the source map in 5d7b565
