### ISSUE TITLE
Date format working only on input

### ISSUE THREAD

**Issue by mprandot** [charliekassel/vuejs-datepicker#412]
Hello!

I have two questions:

first, I can set a timezone to America/São Paulo?
second, i set the format to "dd/MM/yyyy", but this format works only real time input val, inside a v-model the date is like this : "end_date" : 'Sat Feb 03 2018 22:00:00 GMT-0200 (BRST)', why is not formatted with dd/MM/yyyy?

**Comment by charliekassel** [comment]
This is because the datepicker output value is a Date object.
`Sat Feb 03 2018 22:00:00 GMT-0200 (BRST)` is the string representation of the Date object.
It is much more useful to have a Date object that a pre formatted string.

re: timezone - this is set by your Client i.e the browser.
