### ISSUE TITLE
Next Arrow not clickable with dateRange and late selection

### ISSUE THREAD

**Issue by markuspl** [charliekassel/vuejs-datepicker#415]
If you select a date-range (from 01. Jan 1900 - 12. Feb 2000)  and select a date in the late past, then you can't go to the first possible date via the decade-steps (stops 1999).

Steps to reproduce in the demo:
1. Set Date (from - to (01. Jan 1900 - 12. Feb 2000
2. Select the decade view in the picker (1990's, 1980's)
3. Choose a date in the late past (1. Jan 1930).
4. Select the decade view in the picker again and try to go to the year 2000
5. It will stop in the year 1999

**Comment by charliekassel** [comment]
Thank you for filing this issue - but I cannot recreate it.

**Comment by markuspl** [comment]
Hey, just create a screencast to demonstrate it.
https://youtu.be/PFGqqYFj1d0

I will have a look in this as well, if i find anything, i will create a pr

**Comment by charliekassel** [comment]
You realise you are doing this on the demo demonstrating disabling of dates?
The datepicker is disabled _from_ 14 Feb 2000.
