### ISSUE TITLE
disabled.from and to are the wrong way around?

### ISSUE THREAD

**Issue by GreggOrdHume** [charliekassel/vuejs-datepicker#417]
Hello,

I am confused with the from and to aspect of disabling dates. I would expect that from is the date you are starting on and to is the date you are ending on. From being lowest, to being highest.

from: 2017-01-01
to: 2017-01-15

but with datepicker its the other way around which is a little confusing.
Is there any logic behind this decision that maybe I am missing?

Many Thanks! :)
~G

**Comment by charliekassel** [comment]
Disabled to is to disable all dates _to_ or up to the date and disabled from is disabling all dates _from_ or after the date.
Hope that reasoning makes more sense now?

**Comment by GreggOrdHume** [comment]
@charliekassel thanks for the quick response.

What you saying makes sense but myself and my team mates find it confusing to think that way round.

This makes more sense:
`from` - meaning that anything before is disabled, going from a certain date forward. 
'to' - up until a certain date, anything beyond that date disabled.

Similar logic for comparison would be: minDate/startDate and maxDate/endDate.
`minDate`: The lowest date you can pick.
`maxDate`: The highest date you can pick.

`from`: The lowest date you can pick.
`to`: The highest date you can pick.

Its your component and we are grateful to be using it. Just a suggestion.
