### ISSUE TITLE
Can't import component into Laravel 5.3

### ISSUE THREAD

**Issue by KondukterCRO** [charliekassel/vuejs-datepicker#42]
Hi, I'm using Laravel 5.3 and vue 2.
I added Datepicker.vue from src folder into resources/assets/js/components and added utils folder and there I added DateLanguages.js and DateUtils.js.
I added Vue.component('datepicker', require('./components/Datepicker.vue')); into my app.js file and when I compile it with gulp it gives me error. Module not found: Error: Can't resolve 'stylus-loader' in
Can you help?

**Comment by kyranb** [comment]
Just chiming in to say I had the same issue.

**Comment by charliekassel** [comment]
I'm exporting the component as a prebuilt library file so you should just be able to `require('vuejs-datepicker')`

If you want to go the route of importing the raw component you'll have to npm install all or most of it's dependencies too - certainly stylus, stylus-loader at least

**Comment by KondukterCRO** [comment]
I removed vue.component and added require('vuejs-datepicker') in my app.js in resources folder (that js file is compiled with elixir) but now it gives me error that datepicker is unknown element.

**Comment by renatomaric** [comment]
I had the same problem. I'm using _vuejs-datepicker_ with my component and this is how I imported it and it works fine.

```
import DatePicker from 'vuejs-datepicker';

Vue.component('my-component', {
    components: {
      'datepicker': DatePicker
    }
});
```

**Comment by KondukterCRO** [comment]
Thank you for your help. I added your code in app.js - file that is compiled by gulp and after your code I continue my code - const app = new Vue({el: '#app',.....
But still it can't import component.

**Comment by charliekassel** [comment]
Difficult to say without seeing your code or the errors you are getting I'm afraid.

**Comment by KondukterCRO** [comment]
in js folder I have:
require('./bootstrap');
const app = new Vue
({
    el: '#app',
    data:
    {
        active: 1,....

and in gulp I have
var elixir = require('laravel-elixir');
require('laravel-elixir-vue-2');
elixir(mix => {
    mix.sass('app.scss')
       .webpack('app.js');
});

I'm getting error Unknown custom element: <datepicker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by charliekassel** [comment]
You've imported the datepicker and you're adding the imported datepicker to the components object in the new Vue object?

**Comment by KondukterCRO** [comment]
Problem solved. This is how my app.js looks like now:
import DatePicker from 'vuejs-datepicker';
const app = new Vue
({
    el: '#app',
    data:
    {
        active: 1,
        price: 20,
    },
    components: {
      datepicker: DatePicker
    },...
