### ISSUE TITLE
How to clear date inside input using the function date

### ISSUE THREAD

**Issue by espositodaniele** [charliekassel/vuejs-datepicker#424]
Hello,  

I'm trying to clear the date input from a function inside my Vue component but I can't find a way to this. I've seen that the button use a `clearDate()` function. Is it possible to use it?

Thanks

**Comment by mstrlaw** [comment]
Also interested in this sort of method.

**Comment by espositodaniele** [comment]
I was able to solve this reaching the datepicker's methods by using a ref attribute.


```js
<datepicker ref="myDatepicker"></datepicker>
...
this.$refs.myDatepicker.showCalendar()

**Comment by nelson6e65** [comment]
Do you meant `this.$refs.myDatepicker.clearDate()`?

**Comment by espositodaniele** [comment]
Yes it is! Just editing the answer.
