### ISSUE TITLE
Custom input class

### ISSUE THREAD

**Issue by moenth** [charliekassel/vuejs-datepicker#43]
Currently there is no way specify custom css classes to be applied to the `input` element. This makes it inconvenient to integrate the date picker with existing css frameworks, as separate styles must be specified for the datepicker input.

It would be nice if an option were provided to pass custom classes to the input element.

**Comment by renatomaric** [comment]
This is quick fix.  I'm going to make more cleaner way to do this.

```
mounted() {
            var input = this.$el.querySelector('input');
            //Add class
            input.className = 'form-control';
            //Add style
            input.style = 'background-color: #ffffff';
      }
```

**Comment by charliekassel** [comment]
Support added in c8d29bf

**Comment by agm1984** [comment]
Here's how I styled the cells on the calendar--had to fight against the hyper-specific inline rules the library outputs in order to change the colours from blue to pink:

``` javascript
    mounted() {
        const specificityHax = `
            .vdp-datepicker__calendar .cell:not(.blank):not(.disabled).year:hover { border: 1px solid ${colors.pink}; }
            .vdp-datepicker__calendar .cell:not(.blank):not(.disabled).month:hover { border: 1px solid ${colors.pink}; }
            .vdp-datepicker__calendar .cell:not(.blank):not(.disabled).day:hover { border: 1px solid ${colors.pink}; }
            .vdp-datepicker__calendar .cell.selected {
                background: none;
                background-color: ${colors['pink-lighter']};
                color: ${colors['black-darker']};
            }
            .vdp-datepicker__calendar .cell.selected:hover {
                background: none;
                background-color: ${colors['pink-lighter']};
                color: ${colors['black-darker']};
            }
        `;

        const style = document.createElement('style');
        if (style.styleSheet) style.styleSheet.cssText = specificityHax;
        else style.appendChild(document.createTextNode(specificityHax));
        document.getElementsByTagName('head')[0].appendChild(style);
    },
```

This code appends `<style>` into the document head with those rules. I recommend browsing the styles in your dev tools and override the styles on the same classes they are originally on.

Here is what that code produces:
![dp1](https://user-images.githubusercontent.com/17655219/55008467-486c6080-4f9e-11e9-8dc9-442f84c9158a.gif)

**Comment by DeltaBravo** [comment]
This does not seem to be necessary anymore. The styles are not inline (anymore?). 
I am able to override each class within my site-wide linked CSS without the need for any JavaScript.

**Comment by Sammuel09** [comment]
Hello @DeltaBravo How did you do that? Can you explain or show an example
