### ISSUE TITLE
Trigger an re-run of the customPredictor for disabled dates

### ISSUE THREAD

**Issue by danjohnson95** [charliekassel/vuejs-datepicker#435]
I need to make an API request to check which dates are disabled. On initial load, I'm setting all the dates as disabled. But when my API request is complete, I need to tell the calendar to run the `customPredictor()` method again for all visible dates.

Here's a rough trimmed down example of my code:

```javascript
const disabledDates = {
    return {
        customPredictor: (date) => {
            return !this.isDateAllowed(date)
        }
    }
}
```

```javascript
isDateAllowed (date) {
    // Do we already have data back from the API?
    if (this.availabilityService.hasDataForDate(date)) {
        // This will return a bool - whether or not the date is disabled
        return this.availabilityService.getAvailabilityForDate(date)
    } else {
        // If we haven't got any data yet, set it as disabled
        return false
    }
},
render () {
    // Making an API request here. It's returning a Promise
    this.availabilityService.getAvailabilityData()
        .then(() => {
            // Now that I've got my data, I want to tell the calendar component to run the
            // customPredictor method again on all visible dates
            this.triggerCalendarUpdate()
        })
}
```

@charliekassel I'm happy to submit a PR for this, but just wanted to get your thoughts first on whether you'd like this change and how you'd like it implemented. Cheers

**Comment by charliekassel** [comment]
Hi @danjohnson95 - interesting, I've not actually used the customPredictor myself but yes as it's a function it doesn't change, only it's output so therefore not triggering an update from Vue.
What about only setting the `customPredictor` property of the disabled prop once you've had your promise resolved?

**Comment by danjohnson95** [comment]
@charliekassel thanks for your input! Turns out the disabled dates will update when the `disabled` property is changed on the component. Every time I need to trigger an update, I'm just redefining my `disabled` object 👍 

Example snippet if anyone else is facing the same issue:

```html
<template>
    <datepicker :disabled="disabled"></datepicker>
</template>

<script>
export default {
    data () {
        return {
            disabled: {}
        }
    },
    methods: {
        getDisabledObject () {
            return {
                customPredictor: (date) => {
                    // Stick your logic here
                    return !this.service.isDateAllowed(date)
                }
            }
        },

        mounted () {
            this.disabled = this.getDisabledObject()
        
            this.service.getAvailability()
                .then(() => {
                    this.disabled = this.getDisabledObject()
                })
        }
    }
}
</script>
