### ISSUE TITLE
UDM support?

### ISSUE THREAD

**Issue by rizen** [charliekassel/vuejs-datepicker#444]
I'd love to just use this on a site where I'm not compiling a singe page app.

**Comment by TheAndroidGuy** [comment]
+1

**Comment by charliekassel** [comment]
ok coming soon, with the v1 release

**Comment by lukeramsden** [comment]
V1 just got merged @rizen

**Comment by rizen** [comment]
Very cool! I look forward to try it out when I'm done with my current project. (Hopefully mid-May.) Thank you so much for doing this!

**Comment by charliekassel** [comment]
Resolved in v1
