### ISSUE TITLE
[QUESTION] - Disabling Date

### ISSUE THREAD

**Issue by smplyjr** [charliekassel/vuejs-datepicker#446]
Hi @charliekassel, thanks for this very great datepicker! Really appreciate the ease of use of this datepicker! :+1: Can you show me how to disable all date until the day before the date now? Because when I add the code below, its also disabling the date now which is unwanted..

Script
``` javascript
promoDuration: {
  start: null,
  end: null,
  startState: {
    to: new Date()
  },
  endState: {
    to: this.promoDuration.start
  }
}
```

HTML
``` html
<datepicker input-class="form-control" placeholder="Start Date" v-model="promoDuration.start" :disabled="promoDuration.startState" required />
<datepicker input-class="form-control" placeholder="End Date" v-model="promoDuration.end" :disabled="promoDuration.endState" required />
```

I also wanted to disable all previous date of End Date depending on what date Start Date begins. Just preventing to pick date backwards from start date!! Cheers mate!! :ok_hand:

**Comment by charliekassel** [comment]
I normally use a method on the selected event of the datepicker for this.
You can see this in the demo:
https://github.com/charliekassel/vuejs-datepicker/blob/master/src/Demo.vue#L67
https://github.com/charliekassel/vuejs-datepicker/blob/master/src/Demo.vue#L328-L347

**Comment by smplyjr** [comment]
Got it! In case for some one who will ask here, here's my solution

Add v-on:selected method in your HTML datepicker element like this
``` html
<datepicker input-class="form-control" placeholder="Start Date" v-model="promoDuration.start" :disabled="promoDuration.startState" v-on:selected="disableTo" required />
```

And in your javscript set this method
``` javascript
disableTo (val) {
  this.promoDuration.endState.to = val
}
```

Take note of my data
``` javascript
promoDuration: {
  start: null,
  end: null,
  startState: {
    to: new Date()
  },
  endState: {
    to: null
  }
}
```

In this solutions, it will prevent user from selecting backwards on end date from date started on start date. :ok_hand:
