### ISSUE TITLE
How to define monday-first

### ISSUE THREAD

**Issue by PSausM** [charliekassel/vuejs-datepicker#448]
When I want to define monday-first, I get the following error message:
Invalid prop: type check failed for prop "mondayFirst". Expected Boolean, got String.

My markup:
`<datepicker language="de" format="dd. MMMM yyyy" v-model="selectedDate" mondayFirst="true"></datepicker>`
What am I doing wrong?

**Comment by charliekassel** [comment]
you are binding the prop as a String hence the error message.
if you acdd a `:` before the prop then it will bind the value as the javascript value:
```
<datepicker language="de" format="dd. MMMM yyyy" v-model="selectedDate" :mondayFirst="true"></datepicker>
```
