### ISSUE TITLE
Year and decade change buttons direction for RTL

### ISSUE THREAD

**Issue by RomeroMsk** [charliekassel/vuejs-datepicker#456]
The month is changed according to RTL when the header buttons are clicked (in Day View). I suppose we should do the same for the year and decade change buttons (in Month View and Year View).

I could do the PR if you are ok.

**Comment by charliekassel** [comment]
Thank you that would be useful, but would be better to hold off until I've released the next version as I'm refactoring the component into multiple smaller ones so we'll just get conflicts. ETA ~ 1-2 weeks hopefully...

**Comment by RomeroMsk** [comment]
Sure, will wait. Thanks.

**Comment by charliekassel** [comment]
1.0 has been released if you still want to work on this @RomeroMsk ?

**Comment by RomeroMsk** [comment]
Sorry, I still use the 0.9 version and have no time to upgrade and test the new release right now.

**Comment by RomeroMsk** [comment]
@charliekassel, could you please check and accept the PR?
