### ISSUE TITLE
[QUESTION] - date format, remove extra string

### ISSUE THREAD

**Issue by smplyjr** [charliekassel/vuejs-datepicker#460]
Hello, does any body here set the format as format="yyyy-MM-dd" where this code return '2018-04-14' on the input via v-model? This happened on my case and I assumed that the actual string in the model is just this '2018-04-14', but as I try to render it. It shows extra string character at the end part and looks like this '2018-04-18T17:24:00.000Z' now.

Any thoughts on how to make the model contain only '2018-04-14' and not this '2018-04-18T17:24:00.000Z'.

Thanks in advance!! :+1:

**Comment by charliekassel** [comment]
Hi `format` is only for the text input display, the datepicker component outputs a `Date` object.
`2018-04-18T17:24:00.000Z` is the `toJSON` method that gives a string representation of a `Date` object - which is built in javascript - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON
