### ISSUE TITLE
Is there a way use native input type=date field on mobile devices?

### ISSUE THREAD

**Issue by timchambers** [charliekassel/vuejs-datepicker#461]
Is there a way to fall back to native input type="date" on devices that support them, or at least mobile devices?. Perhaps the default input field could be type="date" anyway?

**Comment by HawkeyePierce89** [comment]
I think we can use [mobile-detect](https://github.com/hgoebl/mobile-detect.js) with Modernizr for v-if: use datepicker or native input
```JavaScript
var md = new MobileDetect(navigator.userAgent),
    grade = md.mobileGrade();
Modernizr.addTest({
    mobile: !!md.mobile(),
    phone: !!md.phone(),
    tablet: !!md.tablet(),
    mobilegradea: grade === 'A'
});
```

**Comment by charliekassel** [comment]
I think this is best handled upstream in your own application
