### ISSUE TITLE
Prevent multiple date pickers from being opened at once

### ISSUE THREAD

**Issue by ja1984** [charliekassel/vuejs-datepicker#464]
Hey!

Really like the date picker, easy to implement, easy to customize, so kudos!

But I'm having a problem and I don't know why. If I open the date picker, the only way for me to close it again is to click in the input field. Looking att the demo page I can see that clicking outside of the datepicker closes it, this also prevents multiple date pickers to be displayed at once. 

            <NoSSR>
              <Datepicker :disabled="disabled" :monday-first="true" v-model="fromDate"></Datepicker>
            </NoSSR>
          </div>
          <div class="column">
            <NoSSR>
              <Datepicker :disabled="disabled" :monday-first="true" v-model="toDate"></Datepicker>
            </NoSSR>
          </div>

This is myc vcode for the datepickers,

**Comment by charliekassel** [comment]
Not sure what the question is? You want prevent or to allow multiple pickers to be open?
Because prevent is the default.

**Comment by charliekassel** [comment]
I think this is likely something to do with the `nossr` component you are wrapping it in, I don't know what that does exactly but closing the picker relies on listening to a click on the document, which in a server environment doesn't exist.

**Comment by ja1984** [comment]
Just wanted to make a little update on this issue. It had noting to to with my NoSSR wrapping tags.

The issue was that I had the datepickers in a modal, and on the backdrop of the modal I had a click event to close the modal, that lead to the modal closing even if clicking within the modal, therefor I had a click.stop on my modal-wrapper which caused your click events to not being triggered.

So a lazy solution a long time ago on my end caused the problem. Maybe this can help some one else :) And again, thank you for a really good lib @charliekassel !

**Comment by charliekassel** [comment]
👍 thanks for the update @ja1984
