### ISSUE TITLE
Disabled dates not working

### ISSUE THREAD

**Issue by LTroya** [charliekassel/vuejs-datepicker#475]
I was looking at the example code in order to get disabled dates to working, but no luck. 

I tried: 
`<datepicker :input-class="'form-control'" :disabled-dates="disabledDates"></datepicker>`
and 
`<datepicker :input-class="'form-control'" :disabledDates="disabledDates"></datepicker>`

I look into the source code of the plugin but I didn't see `disabledDates` prop.  I use the same configuration from the docs:

```
disabledDates: {
    to: new Date(2018, 0, 5), // Disable all dates up to specific date
    from: new Date(2018, 0, 26), // Disable all dates after specific date
    days: [6, 0], // Disable Saturday's and Sunday's
    daysOfMonth: [29, 30, 31], // Disable 29th, 30th and 31st of each month
    dates: [ // Disable an array of dates
        new Date(2018, 9, 16),
        new Date(2018, 9, 17),
        new Date(2018, 9, 18)
    ],
    ranges: [{ // Disable dates in given ranges (exclusive).
        from: new Date(2018, 11, 25),
        to: new Date(2018, 11, 30)
    }, {
        from: new Date(2018, 1, 12),
        to: new Date(2018, 2, 25)
    }],
    // a custom function that returns true if the date is disabled
    // this can be used for wiring you own logic to disable a date if none
    // of the above conditions serve your purpose
    // this function should accept a date and return true if is disabled
    customPredictor: function (date) {
        // disables the date if it is a multiple of 5
        if (date.getDate() % 5 == 0) {
            return true
        }
    },
},
```

Maybe the API changes and the docs wasn't updated.I appreciate any hint.
Thanks in advance.

**Comment by LTroya** [comment]
I am using 0.9.29 version. I can install the v.1.10 but I see the same docs. 

Could you give an example of how to use it in the last version?

**Comment by LTroya** [comment]
I was looking at the wrong documentation.

Thanks @charliekassel.

**Comment by gomnamserri** [comment]
I am using CDN and followed the documentation to disabled the dates.`<script>
var state = {
  disabledDates: {
    to: new Date(2016, 0, 5), // Disable all dates up to specific date
    from: new Date(2016, 0, 26), // Disable all dates after specific date
    days: [6, 0], // Disable Saturday's and Sunday's
    daysOfMonth: [29, 30, 31], // Disable 29th, 30th and 31st of each month
    dates: [ // Disable an array of dates
      new Date(2016, 9, 16),
      new Date(2016, 9, 17),
      new Date(2016, 9, 18)
    ],
    ranges: [{ // Disable dates in given ranges (exclusive).
      from: new Date(2016, 11, 25),
      to: new Date(2016, 11, 30)
    }, {
      from: new Date(2017, 1, 12),
      to: new Date(2017, 2, 25)
    }],
    // a custom function that returns true if the date is disabled
    // this can be used for wiring you own logic to disable a date if none
    // of the above conditions serve your purpose
    // this function should accept a date and return true if is disabled
    customPredictor: function(date) {
      // disables the date if it is a multiple of 5
      if(date.getDate() % 5 == 0){
        return true
      }
    }
  }
}
</script> `
`<datepicker :disabledDates="state.disabledDates"></datepicker>`
But unfortunately I wasn't able to achieve it.
I solved the issue with the following code 
`<datepicker :disabled-dates="state.disabledDates"></datepicker>`
and it worked for me.
hope this help someone else too
