### ISSUE TITLE
Language translations not working

### ISSUE THREAD

**Issue by PointfullDevelopers** [charliekassel/vuejs-datepicker#477]
As per documentation I get the following errors:

- app.js:41701 [Vue warn]: Property or method "es" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

Or if you pass a string and not an object as per documentation:

- Invalid prop: type check failed for prop "language". Expected Object, got String.

My Code:
`import Datepicker from 'vuejs-datepicker';
	import {en, es} from 'vuejs-datepicker/dist/locale';

	export default {
		mounted() {},
		components: {
			Datepicker
		}
	}`

`
<datepicker language="{es}" placeholder="Teste 123"></datepicker>
`

`
<datepicker language="es" placeholder="Teste 123"></datepicker>
`

**Comment by charliekassel** [comment]
You are trying to bind the language data as a string.
You need to use a `:` before the language attribute to get it as javascript data.
```
<datepicker :language="es" placeholder="Teste 123"></datepicker>
```

**Comment by PointfullDevelopers** [comment]
Like I said:

- Property or method "es" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by charliekassel** [comment]
You need to bind the import to a data property of the Vue component, otherwise the component know nothing about it. For example:
```
import Datepicker from 'vuejs-datepicker';
import {es} from 'vuejs-datepicker/dist/locale';
export default {
  data() {
    return {
      es: es
    }
  },
  components: {
    Datepicker
  }
}
```

**Comment by rdomingue** [comment]
> You need to bind the import to a data property of the Vue component, otherwise the component know nothing about it.

It should be added in the readme then at this place ; https://github.com/charliekassel/vuejs-datepicker#translations

**Comment by PointfullDevelopers** [comment]
It still doesn't work. 

For example pt-BR, NPM is unable to find the file 

` import {en, pt-BR} from 'vuejs-datepicker/dist/locale';`

**Comment by charliekassel** [comment]
should be `ptBR`
https://github.com/charliekassel/vuejs-datepicker/blob/master/src/locale/index.js#L81
