### ISSUE TITLE
No prop to allow change the type of input box

### ISSUE THREAD

**Issue by navrt007** [charliekassel/vuejs-datepicker#478]
Html5 feature of input type search not allowed.

**Comment by charliekassel** [comment]
We are not really searching so I don't see this as being important

**Comment by navrt007** [comment]
Needed this to allow the cross feature for clearing input a feature that is provided by html5

**Comment by charliekassel** [comment]
Put in a PR then.

**Comment by navrt007** [comment]
I am currently implementing this using JavaScript document by replacing the type text to search for the datepicker input. By “PR” u meant pre tag ?
