### ISSUE TITLE
I have conflict 'language' prop with Multi-Language plugin for Vue.js has same prop

### ISSUE THREAD

**Issue by nitrojulia** [charliekassel/vuejs-datepicker#480]
I have web app with this plugin for language translations:
https://github.com/leonardovilarinho/vue-multilanguage

and when I put 'vuejs-datapicker' plugin I found conflict in 'lenguage props' ... any idea how to solve this problem?

thx

**Comment by charliekassel** [comment]
I can't help you without code examples or error messages.

**Comment by nitrojulia** [comment]
**The error is:** 
`[Vue warn]: The data property "language" is already declared as a prop. Use prop default value instead.`

**Sample:**
https://codesandbox.io/s/3q5ol20qr6 

_I solved using other lib called:  'vue-i18n'_
