### ISSUE TITLE
Next button on calendar shouldn't be disabled 

### ISSUE THREAD

**Issue by piotrorlowski** [charliekassel/vuejs-datepicker#481]
@charliekassel sorry can I have your help on this?

Next button is disabled but there is still one year that can be selected on the next calendar page.

`    data() {
      return {
        disabledDates: {
          from: this.adultDateSetter(),
        }
      };
    },`

`      adultDateSetter() {
        let momentDate = moment(new Date()).subtract(18, 'years');
        let year = parseInt(moment(momentDate._d).format('YYYY-MM-DD').substring(0, 4));
        let month = parseInt(moment(momentDate._d).format('YYYY-MM-DD').substring(5, 7)) - 1;
        let day = parseInt(moment(momentDate._d).format('YYYY-MM-DD').substring(8)) + 1;
        return new Date(year, month, day);
  }`

![image](https://user-images.githubusercontent.com/23028687/39707178-ec17459e-5213-11e8-956e-c42b000f9047.png)

![image](https://user-images.githubusercontent.com/23028687/39707255-2be846dc-5214-11e8-90be-d2a20682e399.png)

I think that problem is related to `.disabled` and `.next` css classes and :class dependencies in vue js files

**Comment by Laruxo** [comment]
I also encountered this problem. It seems that in year picker next decade is disabled without looking at the month and day. I will provide a couple of cases that indicate this issue:
* when `from` property is 2000-01-01, users should still be able to select 2000-01-01, so next decade should be enabled.
* when `from` property is 2000-12-31, users should still be able to select 2000-12-31, so next decade should be enabled.
* when `from` property is 1999-12-31, next decade should be disabled.
