### ISSUE TITLE
typeable property does not work in v1.1.4

### ISSUE THREAD

**Issue by strangecamelcaselogin** [charliekassel/vuejs-datepicker#482]
I see [PR](https://github.com/charliekassel/vuejs-datepicker/pull/472) and [commit](https://github.com/charliekassel/vuejs-datepicker/commit/866736fc02c1d7bb6a3559ba9fcdbe19ac2892e1#diff-6cdce691a1913cacac9461fea9b2f7c6L24) include `@keypress` event to call `parseTypedDate`, which should prevent keypress if typeable property set to false. But in v1.1.4, this code replaced with `@keyup` event listening ([code](https://github.com/charliekassel/vuejs-datepicker/blob/v1.1.4/src/components/DateInput.vue#L24)), which can not prevent actual typing.

**Comment by charliekassel** [comment]
Yes, you are correct! Thank you for brining this to my attention.

Fixed in 5b588ca and released in v1.1.5

**Comment by strangecamelcaselogin** [comment]
Thank you for fast reply!
