### ISSUE TITLE
Mistake in docs?

### ISSUE THREAD

**Issue by shubich** [charliekassel/vuejs-datepicker#483]
**minimumView, maximumView**
probably it's about all props in kebab case
![image](https://user-images.githubusercontent.com/29312810/39764795-0c959066-52e9-11e8-9c56-401d698c2f07.png)

**Comment by charliekassel** [comment]
Not sure what you mean?
Props can be used hyphenated or camel cased

**Comment by shubich** [comment]
@charliekassel can you please give me an example when I can use kebab-case?
I had promblems with that.

**Comment by shubich** [comment]
When I use minimum-view it doesn't work. But it's work when I use minimumView.

**Comment by charliekassel** [comment]
It's in the Vue documentation - https://vuejs.org/v2/guide/components-props.html

**Comment by stevenspinoza** [comment]
> When I use `minimum-view` it doesn't work. But it's work when I use `minimumView`.

In my case it worked in the kebab-cased way
