### ISSUE TITLE
input field is typable by default in chrome

### ISSUE THREAD

**Issue by vollyimnetz** [charliekassel/vuejs-datepicker#487]
Version 1.1.5
Open https://codesandbox.io/s/mpklq49wp in Google Chrome.

Input field is editable even if it should not. (i.e. you can use backspace to delete the year)

I asume there is something different from the behaviour in firefox (where one is not able to edit the input).

**Comment by vollyimnetz** [comment]
a OK, its not really editable - but you can use _backspace_ and _del_ keys to remove content, wich leads to strange behaviour.

**Comment by charliekassel** [comment]
Ah good spot - apparently `keypress` is not triggered by delete key - looks like I need to change to `keydown` event

**Comment by vollyimnetz** [comment]
After a quick check on my android, i noticed that also on chrome for android.
