### ISSUE TITLE
Input's date value

### ISSUE THREAD

**Issue by kikky7** [charliekassel/vuejs-datepicker#488]
How to store the value as string, instead of JS Date?

Using selected event doesn't help:
```
setDate(name) {
    // Output current value: value is JS Date
    console.log(this.vueModel[name])
    // Try to set custom value
    this.vueModel[name] = '2018-01-01'
    // Output new value: value in console is indeed 2018-01-01, but original value is unchanged, and it is the same as console output above
    console.log(this.vueModel[name])
}
```

Also, if I preset datepickers v-model with some dummy data: 2018-01-01, the value is still transformed in JS Date. I need to have the value of v-model on datepicker to be stored as string (since I validate them on server side).
Also, values having JS Date can't be changed manually in Vue DevTools.

I don't know the reason behind transforming value in JS Date, but there should an option to store it as string.

How can this solution be achieved?

**Comment by charliekassel** [comment]
Then turn it into a string of your preference.
The reason it is a Date object is so it is the most flexible way of transforming the data to whatever you need.

**Comment by kikky7** [comment]
I can't transform it into string, as you can see by the example above. Value of v-model is always set to JS Date, even when I change it manually inside selected event.
