### ISSUE TITLE
Allow formatting of form value

### ISSUE THREAD

**Issue by pjebs** [charliekassel/vuejs-datepicker#490]
I entered 1 May 2018 into the calendar which is inside a html form.
I noticed in chrome's vue extension that the value registered is: `Tue May 01 2018 02:33:00 GMT+1000 (AEST)`

By the time it arrives to the server, the value is:  `2018-04-30T16:31:00.000Z`

For some reason it's converted it to UTC from the client's timezone.

How can I obtain purely `1 May 2018` after form submission?

**Comment by charliekassel** [comment]
The way to do this is to convert the Date object into a string before you send to the server.
Format it the way your server is expecting it.
