### ISSUE TITLE
Failed to mount component: template or render function not defined found in  ---> <VuejsDatepicker>        <Root>

### ISSUE THREAD

**Issue by richoid** [charliekassel/vuejs-datepicker#503]
Getting the "failed to mount" error with the following setup in Laravel:
1. did npm install
2. In Webpack
```
autoload({
       //
        vuejsdatepicker: 'vuejs-datepicker',
       //
    })
```
3. in app.js:
`window.vuejsDatepicker = require('vuejs-datepicker');
`
4. in view:
```
<vuejs-datepicker 
                    name="end_date" 
                    :format="customFormatter" 
                    :bootstrap-styling="true" 
                >
</vuejs-datepicker>
var vm = new Vue({
            el: '#app',
//
            components: {
                vuejsDatepicker,
                VueTimepicker,
            }
```
The code for the datepicker is showing up in my compiled app.js. I had it working with the CDN.

It appears the documentation is not up-to-date or wrong (it says, for instance, to put just 'Datepicker' in the components, which errors)

**Comment by tallredmanxyz** [comment]
Depending on how you have things set up this may work: 

```
import Datepicker from 'vuejs-datepicker';
Vue.component('datepicker', Datepicker);
```

Then you should be able to use the component like this:
```
<datepicker><datepicker>
```

Another ticket for reference: https://github.com/charliekassel/vuejs-datepicker/issues/565

**Comment by charliekassel** [comment]
If you `require` it will use the commonjs version then you'll have to use `vuejs-datepicker`

but if you use es6 import then you can name the component what you like:
```
import xxx from 'vuejs-datepicker'
new Vue({
  components: {
    xxx
  }
});

<xxx></xxx>
```
