### ISSUE TITLE
"today" - link

### ISSUE THREAD

**Issue by Phantom75** [charliekassel/vuejs-datepicker#508]
It would be helpful to have an optional "today" link which jumps to todays date. Sometimes, applications initialize dates with 1.1.01 and it is a pain for the user to move all to 2018.

**Comment by fratzinger** [comment]
Maybe the slot "beforeCalendarHeader" is right for you?

example using BootstrapVue and pug.js:
```
datepicker(format="dd.MM.yyyy" v-model="firstWeek" )
  b-btn(slot="beforeCalendarHeader" @click="firstWeek = new Date()") today
```

**Comment by charliekassel** [comment]
It might be a useful addition and there was once a PR for this, but you could indeed use the example above.
As a side note, why would an application initialize a date with 1.1.01?
I mean you must be passing it as that.
