### ISSUE TITLE
Remove autocomplete on picker input

### ISSUE THREAD

**Issue by daniesy** [charliekassel/vuejs-datepicker#517]
Having autocomplete enabled on the picker input field blocks the display of the calendar. Please see the screenshot below. I've tested this in Chrome 66.0.3359.181 on Mac. 
Can you give us an option to disable autocomplete on the input field?

<img width="755" alt="screen shot 2018-05-31 at 01 54 20" src="https://user-images.githubusercontent.com/3399101/40751831-97b658b8-6475-11e8-8b75-aa33be3c72c6.png">

**Comment by richoid** [comment]
I agree, though I understand autocomplete="off" may not work in all browsers.

**Comment by willashley23** [comment]
Google Chrome ignores `autocomplete`. IIRC, they parse the `name`, `id` `label(for=)` and even `placeholder` for _any_ mention of a field that can be autocompleted. It may require some jumping through hoops and giving attrs strings that it does not recognize as autocomplete-able.

**Comment by rafaferry** [comment]
I'm having the same issue. 

I've tryed to use `<datepicker autocomplete="off"/>` but the generated html sets the autocomplete on the outer div(.vdp-datepicker) instead on input.

I've also noticed that when I set the id of datepicker, the id gets dupplicated. The same Id is used on the outter div(.vdp-datepicker), and on the input. This is should be avoided.

**Comment by jimnordb** [comment]
Opening this again. i applied a pull request for this. autcomplete="off" sets the autcomplete off entirely for that input.

tested and working

**Comment by charliekassel** [comment]
This is the recommended way of solving turning autocomplete of by MDN.
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by aemonge** [comment]
Hi ! I jump right into the conversation:

I don't see the `autocomplete="off"` working at all, neither the `[attr.autocomplete]="off"`, any work-arrounds ? 

Also, It's not clear for me if this auto-complete refers to the fact that a input of `1` turns into `01/01/1901` or if it's a prevention from password manager.....  I'm interested in the first case. I want ( for whatever reason the PO needs ) to keep invalid values such as `1` `1/02` etc....

**Comment by ForTimeBeing** [comment]
> Hi ! I jump right into the conversation:
> 
> I don't see the `autocomplete="off"` working at all, neither the `[attr.autocomplete]="off"`, any work-arrounds ?
> 
> Also, It's not clear for me if this auto-complete refers to the fact that a input of `1` turns into `01/01/1901` or if it's a prevention from password manager..... I'm interested in the first case. I want ( for whatever reason the PO needs ) to keep invalid values such as `1` `1/02` etc....

This is exactly what I need to. I don't want it to autofill, why isn't disabling it an option? I can't filter properly because of it

**Comment by SanduCuragau** [comment]
Did anyone find a solution for this problem being described? "a input of 1 turns into 01/01/1901"

**Comment by Berd74** [comment]
I am waiting for a solution as well..

**Comment by jasperck** [comment]
Isn't `autoComplete="off"` do the trick? It is one of the [supported props ](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md) (not autocomplete but autoComplete).

**Comment by michal-stolarski-k2** [comment]
There are so many options to handle this. For example: create a hidden input for store value and add a div element to looks like the input. Autofill is ugly for datepicker.

**Comment by Manu12bollineni** [comment]
Hello Everyone,
Just wrap your Datepicker field inside <form></form> tag.!
This worked for me 

Thank you.

**Comment by jasperck** [comment]
@Manu12bollineni Glad that work for you as well👍

**Comment by jasperck** [comment]
@Manu12bollineni Glad that works to you as well👍
