### ISSUE TITLE
Wrong property "disabled-dates" in the README.md

### ISSUE THREAD

**Issue by vlad-yaremenko** [charliekassel/vuejs-datepicker#521]
Wrong property [here](https://github.com/charliekassel/vuejs-datepicker/blob/master/README.md#disabled-dates)

Now:
```html
<datepicker :disabled="state.disabledDates"></datepicker>
```
Should be:
```html
<datepicker :disabled-dates="state.disabledDates"></datepicker>
```

**Comment by charliekassel** [comment]
Closed by https://github.com/charliekassel/vuejs-datepicker/pull/514
