### ISSUE TITLE
Cannot highlight dates using only from or to parameters

### ISSUE THREAD

**Issue by qkdreyer** [charliekassel/vuejs-datepicker#525]
We cannot use the "from" or "to" parameters in highlighted param the same way than the "from" or "to" parameters in disabledDates param.

https://codesandbox.io/s/8kx33x4q6l

As you can see on this exemple, dsisabledDates are working but highlighted dates.

**Comment by charliekassel** [comment]
Yes, it it the other way around for highlighted dates, more like a range.
It doesn't make much sense to highlight everything up to a certain date I feel
