### ISSUE TITLE
Disable every day from yesterday to the beginning of time

### ISSUE THREAD

**Issue by devlemire** [charliekassel/vuejs-datepicker#531]
How would you go about accomplishing this?

**Comment by aaemnnosttv** [comment]
Here's how I did it:

```
:disabledDates="{ to: new Date(Date.now() - 8640000) }"
```

![image](https://user-images.githubusercontent.com/1621608/41399552-48ce4e96-6fc3-11e8-9113-6ada8ca62bf7.png)

**Comment by SerikK** [comment]
@aaemnnosttv thanks, it helped

**Comment by Decrux01** [comment]
I tried the same thing but nothing happens. There are no console errors. 
```
<datepicker
     v-model="date"
     :format="DatePickerFormat"
     id="validitydate"
     :disabledDates="disabledDates">
</datepicker>

data(){
      return {

        DatePickerFormat: 'dd/MM/yyyy',
        disabledDates: {
          to: new Date(Date.now() - 8640000)
        }
      }
    }
```

**Comment by SerikK** [comment]
@Decrux01 What version are you using?

**Comment by Decrux01** [comment]
Version of what? I am using the newest version of Vue, if you are asking for that.

**Comment by Decrux01** [comment]
Nope still doesn't work

```
<datepicker
     v-model="date"
     :disabledDates="{ to: new Date(Date.now() - 8640000) }"
     :format="DatePickerFormat"
</datepicker>
```
Again with no console errors or errors at all.

**Comment by Decrux01** [comment]
I would be happy if @charliekassel explain if I am doing it wrong.

**Comment by hari03** [comment]
According to the [docs](https://www.npmjs.com/package/vuejs-datepicker#disabled-dates), the correct usage is `disabled-dates` and **not** `disabledDates`. Changing it fixed my issue.

**Comment by Mirjalol9797** [comment]
> 8640000

                                      <date-picker
                                            v-model="time1"
                                            :disabled-date="disabledDates"
                                        ></date-picker>

**Comment by Mirjalol9797** [comment]
@decrux-io 
                                        <date-picker
                                            v-model="time1"
                                            :disabled-date="disabledDates"
                                        ></date-picker> 
        disabledDates(date) {
            const today = new Date()
            today.setHours(1, 0, 0, 0)
            return date < today
        },
