### ISSUE TITLE
Separate display and submission formats

### ISSUE THREAD

**Issue by mattfletcher** [charliekassel/vuejs-datepicker#533]
It would be great if I could show the user dates in dd/MM/yyyy but submit the form values as yyyy-MM-dd

Is this possible?

**Comment by charliekassel** [comment]
Yes, the datepicker models the value as a regular js Date object.
Just format it how you want before sending.
```${date.getFullYear()}-${('0'+(date.getMonth()+1)).slice(-2)}-${date.getDate()}```
