### ISSUE TITLE
how to load language files manually?

### ISSUE THREAD

**Issue by ikkez** [charliekassel/vuejs-datepicker#535]
```html
<script src="components/vuejs-datepicker/dist/vuejs-datepicker.min.js"></script>
<script src="components/vuejs-datepicker/dist/locale/translations/de.js"></script>
```

without a build-process involved, this is obviously not working, as it gives a `SyntaxError: export declarations may only appear at top level of a module`. What's the alternative? Is there a global setter or something where I can register language objects manually?

**Comment by charliekassel** [comment]
I need to build the lang files as common js or umd for this to work

**Comment by ikkez** [comment]
That would be great. 👍

**Comment by concware** [comment]
I also need some help to use the hungarian language manually. Can you help me, how can i do this?

**Comment by RamonSaldanha** [comment]
> ```
> <script src="components/vuejs-datepicker/dist/vuejs-datepicker.min.js"></script>
> <script src="components/vuejs-datepicker/dist/locale/translations/de.js"></script>
> ```
> 
> without a build-process involved, this is obviously not working, as it gives a `SyntaxError: export declarations may only appear at top level of a module`. What's the alternative? Is there a global setter or something where I can register language objects manually?

      const datepicker = require('vuejs-datepicker');
      var Language = function Language (language, months, monthsAbbr, days) {
        this.language = language;
        this.months = months;
        this.monthsAbbr = monthsAbbr;
        this.days = days;
        this.rtl = false;
        this.ymd = false;
        this.yearSuffix = '';
      };
      var pt = new Language(
        "Brazilian",["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"],["Dom","Seg","Ter","Qua","Qui","Sex","Sab"]
      );
      const app = new Vue({
        el: '#app',
        components: {
          datepicker
        },
        data: {
          ptBR: pt
        }
      })

**Comment by charliekassel** [comment]
This should be working now as of v1.6.1 - reference global variable: `vdp_translation_xx` - see example in the readme.
