### ISSUE TITLE
If i set typeable=true, i can not select in calendar

### ISSUE THREAD

**Issue by xzol** [charliekassel/vuejs-datepicker#542]
Hi.
If i set typeable=true, i can not select in calendar.

I can enter a date on my hands, for example 07/08/1976 and everything will be saved.But if I select the date in the drop-down calendar, then the value, after clicking to another place will fold.

**Comment by xzol** [comment]
![2018-06-22 10-30-44](https://user-images.githubusercontent.com/10128293/41763683-883e7160-7607-11e8-9577-7bbada5a51fe.png)
![2018-06-22 10-30-53](https://user-images.githubusercontent.com/10128293/41763689-8d154b00-7607-11e8-8a41-75250e5390af.png)
![2018-06-22 10-31-10](https://user-images.githubusercontent.com/10128293/41763696-93aba432-7607-11e8-9c30-fb4dc17be603.png)

**Comment by xzol** [comment]
https://youtu.be/687SdulPWgQ.

**Comment by xzol** [comment]
https://www.youtube.com/watch?v=687SdulPWgQ&feature=youtu.be

**Comment by whipsterCZ** [comment]
same here.  problem only in Firefox

**Comment by charliekassel** [comment]
This is working in Chrome, Firefox, Safari
http://jsfiddle.net/charliefarley/eywraw8t/107658/

**Comment by sg-4xxi** [comment]
@charliekassel look it - http://jsfiddle.net/eywraw8t/347464/
select - 28.09.2018, then you focus out the field it fails
and if you select 05.09.2018 it works
i'm sure it's connected with https://github.com/charliekassel/vuejs-datepicker/issues/583
