### ISSUE TITLE
datepicker without input

### ISSUE THREAD

**Issue by n-osennij** [charliekassel/vuejs-datepicker#544]
Hi. Is it possible to hide input and show only button with icon? When I push the button, datepicker is opening. When I chouse date, it disbpayed on button.
Example - http://jsfiddle.net/516zsh7b/390/

**Comment by charliekassel** [comment]
You can access the datepicker's methods by using a ref attribute.
```
<datepicker ref="myDatepicker"></datepicker>
...
this.$refs.myDatepicker.showCalendar()
```

**Comment by inherithandle** [comment]
OP wants to hide input tag. can you tell me how to do that? I tried `<datepicker ref="myDatepicker"></datepicker> on Demo.vue from this repository. this still shows input textbox.
