### ISSUE TITLE
vee-validate require does not work

### ISSUE THREAD

**Issue by AdrianKrebs** [charliekassel/vuejs-datepicker#546]
Given the following datepicker code:
` <datepicker class="datepicker" name="deadlinedate" :class="{'input': true, 'is-danger': errors.has('deadlinedate') }" v-model="goal.deadline"
                                :disabledDates="state.disabledDates" v-validate="'required'"
                                :language="de"></datepicker>`

When the datepicker input stays empty, the is-danger class never gets added to the input field.
Am I missing something?

**Comment by charliekassel** [comment]
I'd create an issue on that repo - sorry, I don't know much about it.
Test if the is-danger class is added by directly setting it to true.
