### ISSUE TITLE
Orientation prop to open datepicker in certain position

### ISSUE THREAD

**Issue by merorafael** [charliekassel/vuejs-datepicker#552]
Hello everybody,

This component have a property like a "orientation" on Bootstrap Datepicker component?
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html?highlight=orientation#orientation

I'm need this feature because my datepicker is cut if my component is positioned on right.

**Comment by paatrick** [comment]
have you solved your problem in any way?

**Comment by raublekick** [comment]
The cut off is likely because some element in your page has overflow: hidden. My way of dealing with this until I can come up with something better is to add this CSS rule and give the datepicker the ".top" class.

.top .vdp-datepicker__calendar {
  position: absolute;
  top: -282px;
}

**Comment by charliekassel** [comment]
No @merorafael - this is not supported, you'll have to target the css classes yourself.

**Comment by Landen13** [comment]
Omg. Not supported? Really?
