### ISSUE TITLE
it is possible to change the language when using CDN?

### ISSUE THREAD

**Issue by Daimioo** [charliekassel/vuejs-datepicker#557]

**Comment by victory-v** [comment]
I solved this problem by adding my language manually:
`data: {
      ru: {
        language: 'Russian',
        months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
        monthsAbbr: ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь', 'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек'],
        days: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
        rtl: false,
        ymd: false,
        yearSuffix: ''
      }
}
....`

`<input type="text" is="vuejs-datepicker" :language="ru">`

**Comment by ugurozturk** [comment]
Solved with : 
the cdns ;
   ```
<script src="https://cdn.jsdelivr.net/npm/vuejs-datepicker@1.6.2/dist/vuejs-datepicker.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/vuejs-datepicker@1.6.2/dist/locale/translations/tr.js" type="text/javascript"></script>
```
and usage : 
`<vuejs-datepicker input-class="form-control" :language="vdp_translation_tr.js"></vuejs-datepicker>`

The importing is `tr.js` change that in two line as wish as you want to change the language
