### ISSUE TITLE
Module parse failed: Unexpected token (237:41)

### ISSUE THREAD

**Issue by roelVerdonschot** [charliekassel/vuejs-datepicker#558]
When i try to build the datepicker I get this error message:

ERROR in ./node_modules/vuejs-datepicker/src/utils/DateUtils.js
Module parse failed: Unexpected token (237:41)
You may need an appropriate loader to handle this file type.
| }
| 
| export const makeDateUtils = useUtc => ({...utils, useUtc})
| 
| export default {

**Comment by charliekassel** [comment]
You shouldn't need to build it when you've installed it via npm/yarn - it is already built.

**Comment by Huang-ChenGang** [comment]
I hava run "npm install vuejs-datepicker --save"  to install it.
But still have this error.


error  in ./node_modules/vuejs-datepicker/src/utils/DateUtils.js

Module parse failed: Unexpected token (237:41)
You may need an appropriate loader to handle this file type.
| }
|
| export const makeDateUtils = useUtc => ({...utils, useUtc})
|
| export default {

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.j
s?type=script&index=0!./node_modules/vuejs-datepicker/src/components/Datepi
cker.vue 102:0-51
 @ ./node_modules/vuejs-datepicker/src/components/Datepicker.vue

**Comment by camilo0119** [comment]
Pudo solucionar el problema?
