### ISSUE TITLE
🐞 Multiple date pickers - same dates different times.

### ISSUE THREAD

**Issue by OwenMelbz** [charliekassel/vuejs-datepicker#566]
Hey,

We're having a bit of problem detecting multiple dates that are the same.

The problem is the model value gets set to a Date object with the current time in it. e.g the scenario might be.

- 14:20 - User picks 10/10/2018
- 14:21 - User picks on another picker 10/10/2018

`modelOne != modelTwo`

This is because the timestamp that is added to the model looks like 

`2018-10-10T14:20:00.000Z` and `2018-10-10T14:21:00.000Z`

Thus when you do things like client and server side validation it sees they're different.

--

The reason I chose to use this "datepicker" package was because I wanted a datepicker :D its pretty annoying that "time" is the thing messing with it.

Can you see anyway to resolve this without having to create a custom validator which chunks off the time and compares only the date?

Thanks

**Comment by OwenMelbz** [comment]
We could it momentjs was PHP as the validation is server-side.

This is why we were hoping to not have the problem in the first place :)

**Comment by jamiechong** [comment]
Format your date on the frontend before you submit it to the server: 
`let dateToSubmitToServer = moment(this.modelOne).format('YYYY-MM-DD');`

**Comment by OwenMelbz** [comment]
Yeah it’s just very awkward as we’ve got multiple dates on the page and it means we have to reassign variables to new ones before sending.

Would seem a better solution would be to be consistent with the dates it returns. If you pick 3 dates the same. They should be the same. Not slightly different

**Comment by charliekassel** [comment]
You just need to pass the value to a format function to get the value how you want to use it.
