### ISSUE TITLE
Format not working on v-model

### ISSUE THREAD

**Issue by mprandot** [charliekassel/vuejs-datepicker#568]
Hello!

I'm formating one component with "dd/MM/yyyy", on the input field is showing correct, but the value of v-model comes like this: Wed Jul 04 2018 21:00:00 GMT-0300 (-03)

it's a bug? How i can force to come like the format specified?

Another thing, in one case we force a input to come with a specified date (formated, like: 30/12/1994), the value of v-model is correct but not show the date on input field. 

Same input in this two cases.

`<datepicker format="dd/MM/yyyy" input-class="form-control" :language="ptBR" v-model="faturamento.data_faturamento"></datepicker>`

thanks!

**Comment by mprandot** [comment]
same problem as  #549

**Comment by amarjit-singh** [comment]
Why this issue is closed? It's not fixed yet and it is really a bug

**Comment by thrazu** [comment]
Same problem here

**Comment by thrazu** [comment]
My solution comes from the backend:
Vue datepicker uses v-model="data.date" and my php backend returns the date with Carbon $dt->toISOString();
For saving the date in a mysql date field I use Carbon::parse($date)

**Comment by kirilkirkov** [comment]
This is javascript Data object. Just call .toUTCString() and this will give you format you want. After that you can parse it with Carbon::parse
