### ISSUE TITLE
New feature request: minimumView & maximumView upper bound to decades

### ISSUE THREAD

**Issue by choi12191995** [charliekassel/vuejs-datepicker#572]
According to bootstrap datepicker, [http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#maxviewmode](url)

We can use:

> Set a maximum limit for the view mode. Accepts: 0 or “days” or “month”, 1 or “months” or “year”, 2 or “years” or “decade”, 3 or “decades” or “century”, and 4 or “centuries” or “millenium”. Gives the ability to pick only a day, a month, a year or a decade. The day is set to the 1st for “months”, the month is set to January for “years”, the year is set to the first year from the decade for “decades”, and the year is set to the first from the millennium for “centuries”.

So, hopefully you can add this feature like the above quote. It is a good function for picking birthday or historical date. To give user better experience.

**Comment by charliekassel** [comment]
We do already have `minimumView` and `maximumView` which should get you where you want.

**Comment by choi12191995** [comment]
my suggestion is the maxiumView is up to 100 years

That's mean:

centuries > decades > years > months > days
