### ISSUE TITLE
Format weekday labels

### ISSUE THREAD

**Issue by asanzdj** [charliekassel/vuejs-datepicker#586]
How can I format the weekday labels? Now, it displays: Mon, Tue, Wed,.... and I want to display: M, T, X,...

Now:
![screen shot 2018-09-03 at 14 23 34](https://user-images.githubusercontent.com/15629285/44986845-5d8f8c80-af85-11e8-89c6-629d0e6b0004.png)

Wanted:
![screen shot 2018-09-03 at 14 25 18](https://user-images.githubusercontent.com/15629285/44986857-684a2180-af85-11e8-9ca4-ce9799e73937.png)

**Comment by charliekassel** [comment]
There is no way to do this currently

**Comment by itxshakil** [comment]
Is there way to do this now. Its showing Su, Mo I want Sun Mon.
