### ISSUE TITLE
Help !  Help !!   Help !!!    I can't start project with vuejs-datepicker

### ISSUE THREAD

**Issue by Huang-ChenGang** [charliekassel/vuejs-datepicker#587]
I hava run "npm install vuejs-datepicker --save" to install it.
And then I run "npm run dev" to start my project.
This error has occurred.

error in ./node_modules/vuejs-datepicker/src/utils/DateUtils.js

Module parse failed: Unexpected token (237:41)
You may need an appropriate loader to handle this file type.
| }
|
| export const makeDateUtils = useUtc => ({...utils, useUtc})
|
| export default {

@ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.j
s?type=script&index=0!./node_modules/vuejs-datepicker/src/components/Datepi
cker.vue 102:0-51
@ ./node_modules/vuejs-datepicker/src/components/Datepicker.vue

**Comment by dudleyf** [comment]
I ran into this same error. Turns out my IDE had autocompleted the import path to the path to the vuejs-datepicker source instead of the compiled output.

I had:

`import Datepicker from 'vuejs-datepicker/src/components/Datepicker'`

when I corrected that to:

`import Datepicker from  'vuejs-datepicker'`

everything works as expected.

**Comment by charliekassel** [comment]
As above, just import the base package which will import the built distributed files.

You were trying to import the src component which will need compiling with all the dependencies that you don;t need unless you are developing on this component.

**Comment by Khanabeev** [comment]
> I ran into this same error. Turns out my IDE had autocompleted the import path to the path to the vuejs-datepicker source instead of the compiled output.
> 
> I had:
> 
> `import Datepicker from 'vuejs-datepicker/src/components/Datepicker'`
> 
> when I corrected that to:
> 
> `import Datepicker from 'vuejs-datepicker'`
> 
> everything works as expected.

Thank you, you're the best
