### ISSUE TITLE
'Day and month view only ' cant work as expect, who can help me, help, help!~

### ISSUE THREAD

**Issue by lihchweb** [charliekassel/vuejs-datepicker#591]
my code looks like this:
![qq 20180917113929](https://user-images.githubusercontent.com/24636279/45605271-66488e00-ba6e-11e8-927a-69a1dbabbc8b.png)

but  I failed. when I set minimumView and maximumView，Actually they did not work. the result is:
![abc](https://user-images.githubusercontent.com/24636279/45605426-79a82900-ba6f-11e8-9f44-b45c04eeb779.png)

i need help. thanks.

**Comment by audun-** [comment]
Hey there. In the future, try to rather copy and paste your code and to use \```your-code-here\```. styling. That makes helping a lot easier to help, because it makes your code render like code:

```
<html>
  <head>
  </head>
</html>
```

As for your issue, it seems like the strings are malformatted. Try `:minimumView="month" maximumView="month"`

**Comment by charliekassel** [comment]
There is an example in the [demo](https://codesandbox.io/s/mpklq49wp)

**Comment by lihchweb** [comment]
> Hey there. In the future, try to rather copy and paste your code and to use ```your-code-here```. styling. That makes helping a lot easier to help, because it makes your code render like code:
> 
> ```
> <html>
>   <head>
>   </head>
> </html>
> ```
> As for your issue, it seems like the prop strings are malformatted. Try `:minimumView="month" maximumView="month"`

I tried, but failed

**Comment by lihchweb** [comment]
> There is an example in the [demo](https://codesandbox.io/s/mpklq49wp)

I knew this demo， i hope it would be ok,but  it  did not work。 I used your vuedatepicker js by `<srcipt></scrpt>`, not  vue-cli  or  webpack.  Looking forward to receiving your reply. 
thanks!~

**Comment by lihchweb** [comment]
> Hey there. In the future, try to rather copy and paste your code and to use ```your-code-here```. styling. That makes helping a lot easier to help, because it makes your code render like code:
> 
> ```
> <html>
>   <head>
>   </head>
> </html>
> ```
> As for your issue, it seems like the prop strings are malformatted. Try `:minimumView="month" maximumView="month"`
besides ,Thank you for your advice

**Comment by audun-** [comment]
What exactly failed? Did you get a stack trace? Try posting your update code.

**Comment by lihchweb** [comment]
> What exactly failed? Did you get a stack trace? Try posting your update code, as well as any error messages

```
<!DOCTYPE html>
<html>
<head>
	<title>picker</title>
	<script src="https://unpkg.com/vue"></script>
	<script src="https://unpkg.com/vuejs-datepicker"></script>
</head>
<body>
<div id="app">
  <vuejs-datepicker :minimumView="'month'" :maximumView="'month'"></vuejs-datepicker>
</div>
</body>
<script type="text/javascript">
	new Vue({
		el: '#app',
		components: {
  			vuejsDatepicker
  		}
	})
</script>
</html>
```
here is my code.
what went wrong? I'm puzzled.

**Comment by audun-** [comment]
@lihchweb Your strings are malformatted. You have an extra set of `'` in `:minimumView` and `:maximumView`. You shouldn't use both `'` and `"`, especially not together like that. Try just using `"month"` instead for both.

**Comment by lihchweb** [comment]
> @lihchweb Your strings are malformatted. You have an extra set of `'` in `:minimumView` and `:maximumView`. You shouldn't use both `'` and `"`, especially not together like that. Try just using `"month"` instead for both.

i don't think you are right.  you should try my code. just look this demo: [https://codesandbox.io/s/mpklq49wp](url). it told me this.

because the minimumView  should be String. so i must wirte my code like this : `:minimumView = '"moth"'`

eh, my English is poor. i'm not sure you know what i mean
