### ISSUE TITLE
How add custom class on day?

### ISSUE THREAD

**Issue by slowas** [charliekassel/vuejs-datepicker#596]
Hi, I'm doing work business on calendars. It's a question of how to put different classes on a daily basis for employment such as:

Data loading from backend when changed month or year changed.

if (a <20) green
if (a <50) yellow
if (c <100) red

**Comment by mtleppay** [comment]
use day-cell-content prop.
:day-cell-content="dayCellContent"

dayCellContent(date) {
    //your logic
   return '<div>' + date.date + '</div>'
}
