### ISSUE TITLE
Accessing Datepicker props

### ISSUE THREAD

**Issue by ianrussel** [charliekassel/vuejs-datepicker#598]
Any ideas to access this Datepicker prop > PickerMonth > pageDate
The idea is, I want to get the month name when @changedMonth is triggered.

                               `<datepicker 
                                    :inline="true" 
                                    v-model="dateState" 
                                    :disabledDates="disabledDates"
                                    :highlighted="highlighted"
                                    @changedMonth="changedMonth"
                                ></datepicker>`

                               changedMonth(value) {
                                           console.log(Datepicker> PickerMonth> pageDate) //which is Fri Feb 01 2019 00:00:00 GMT+0800 as an example
                              }
<img width="753" alt="capture" src="https://user-images.githubusercontent.com/4607692/46052585-a7792600-c171-11e8-8912-32f960337740.PNG">

**Comment by rootboard** [comment]
https://codesandbox.io/s/jp049m0vvy

Did you mean this?

**Comment by ianrussel** [comment]
@rootboard I already solved the issue.

**Comment by charliekassel** [comment]
Then please close the issue @ianrussel
