### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kkomelin** [charliekassel/vuejs-datepicker#6]
Hi @charliekassel,

Could you please include a license file to the project?
Please read more here https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

Thanks so much.

Konstantin

**Comment by coderdiaz** [comment]
@charliekassel I think you could select MIT License.

**Comment by kkomelin** [comment]
Thanks @coderdiaz but I would wait the project author response. Guessing is not an option.

**Comment by charliekassel** [comment]
Hi guys, I have added an MIT license for this project.
e97e163

**Comment by kkomelin** [comment]
Cool. Thanks @charliekassel !

**Comment by coderdiaz** [comment]
Thanks @charliekassel
