### ISSUE TITLE
Event name emitted should be kebab case

### ISSUE THREAD

**Issue by pitapaya** [charliekassel/vuejs-datepicker#602]
https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

Rename the emitted event name using the recommended kebab case so the events would work on a single html application.

Right now, the following example doesn't work.
```
<vuejs-datepicker
  v-on:changedMonth="onMonthChange"
></vuejs-datepicker>
```

**Comment by charliekassel** [comment]
it should _not_ be kabab cased if you read the manual.

**Comment by pitapaya** [comment]
Where in the manual? In the link I sent you, it's written "For these reasons, we recommend you always use kebab-case for event names."

I'm suggesting this fix because the events were not working when the component is included in a html file.

**Comment by haugen86** [comment]
@charliekassel if you read the docs for vuejs, they indeed _should_ be kebab-case.

Pasted from VueJS docs:

> Unlike components and props, event names will never be used as variable or property names in JavaScript, so there’s no reason to use camelCase or PascalCase. Additionally, v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity), so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.
> 
> For these reasons, we recommend you always use kebab-case for event names.

**Comment by charliekassel** [comment]
I've added an example for changedMonth in the codesandbox demo at the bottom -  it seems to be working ok for me on Chrome, Firefox and Safari browsers (Mac).

https://codesandbox.io/s/mpklq49wp

**Comment by pitapaya** [comment]
The issue is not when you use a `.vue` file with Webpack.

Look at the console here and change month: https://codepen.io/anon/pen/LgGaWP

**Comment by pitapaya** [comment]
Also, I noticed that haugen86 made a Pull request with the fix.
