### ISSUE TITLE
Allow customization of year intervals (i.e. years shown per page)

### ISSUE THREAD

**Issue by yl5682** [charliekassel/vuejs-datepicker#607]
I really enjoy using this vuejs component but I wonder if there is a way to customize how many years I can see per year page. In other words, currently by default I can scroll through 10 years at a time, from 1990 to 2000 to 2010, etc. Is there a way to let me scroll through, for example, 20 years at a time? 

Thank you

**Comment by charliekassel** [comment]
No plans for this feature currently.

**Comment by nullablebool** [comment]
I agree with this, it seems that choosing to present a decade doesn't really fit the UX. 

If there were a top level selector expanding to decade...century then it would make sense. I would argue to conform to the UX that this should follow the rule of thirds and be 9 or 12. It doesn't seem to take much effort to make this configurable. +1 from me.
