### ISSUE TITLE
Use v-popover on days

### ISSUE THREAD

**Issue by mtleppay** [charliekassel/vuejs-datepicker#608]
Hello, i need to render bootstrap ( any ) v-popover inside :dayCellContent prop. Is it possible with v-datepicker? I'm trying, but it does not work. 

```
dayCellContent(date) {
return date.date + '<div class="price">'
'<v-popover placement="top"></v-popover>'
'</div>'
}
```

**Comment by charliekassel** [comment]
Sorry no experience with this lib
