### ISSUE TITLE
typeable + using date in format dd.MM.yyyy causes Date.parse to evaluate to NaN

### ISSUE THREAD

**Issue by saraha33** [charliekassel/vuejs-datepicker#609]
Hi,

i have set typeable to true and the date format dd.MM.yyyy which seems to cause problems because my date keeps disappearing 

after some investigation i think the problem is that Date.parse() in the inputBlurred function evaluates to NaN if the date is in format dd.MM.yyyy (of course not always but only if it is an invalid date according to the MM.dd.yyyy format, e.g. 13.10.2018) and it keeps deleting my input because then `this.typeable && isNaN(Date.parse(this.input.value))` evaluates to true...

**Comment by rootboard** [comment]
https://github.com/charliekassel/vuejs-datepicker/issues/597
This problem is already described here, but without information about Date.parse()

**Comment by saraha33** [comment]
@rootboard - thanks for the hint - i was looking but did not come across this one.
