### ISSUE TITLE
Custom format and typeable true

### ISSUE THREAD

**Issue by noemiebolo** [charliekassel/vuejs-datepicker#616]
Hello,

I make an issue even if I already mentionned it in another ticket (#597)

I got a custom format (:format="dd/MM/yyyy") and when I type for example 09/04/2018, the date is the 4th of september 2018 and not the 9th of april 2018.

Someone to help ?
Thanks,
Noémie.

**Comment by zandergr8** [comment]
Unless you are going to use a method/function to do your formatting, unbind the format option (remove the colon) so it takes the string value.

Ex. 

format = "dd/MM/yyyy"

**Comment by noemiebolo** [comment]
Hello,
Thanks for your answer.

Indeed, I made a mistake when typing my issue, the colon is out of purpose.
Take a look at [the example here](https://codesandbox.io/s/q4qjvxvk44), it will show you the problem. Try to enter 09/04/2018 for example and check the result.

Thanks,
Noémie

**Comment by zandergr8** [comment]
Hello,

I just took a quick look at your example via my iphone and I don’t see that the data property “format” bound to the datepicker.  Unless I’m missing something via my small screen, you’ll need to bind your data property by adding :format=“format” to your datepicker.

-Alex

**Comment by noemiebolo** [comment]
Hello

Thanks for your answer. The format was in the data properties of the component but as you suggest I have moved it in the props. As you can see it does not change anything. 
Any idea ?

Thanks,
Noémie

**Comment by zandergr8** [comment]
N,

If you want it to be a property, I would keep it as a data property since there is no need for it to change.  You just need to bind the format property of the datepicker to your “format” as follows:

<datepicker :format=“format” />  

-A

**Comment by charliekassel** [comment]
The way that the `typeable` prop works is by simply passing the value to javascript's Date.parse - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
You can make a proposal to [tc39](https://github.com/tc39/proposals) for date formats if you like - but I wouldn't hold your breath.

The `format` prop only formats the display value, not the input format.
I looked at third party libraries when implementing this but couldn't find anything I liked or that I thought worked very well so simply deferred to Date.parse.
Unfortunately `typeable` seems to be a can of worms that I wish I had never opened and may just rip out eventually.
