### ISSUE TITLE
Integration with moment.js

### ISSUE THREAD

**Issue by kikky7** [charliekassel/vuejs-datepicker#617]
When I pass date value to the moment, I get this warning:

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release.

This is date value:
`Wed Oct 24 2018 19:14:00 GMT+0200 (Central European Summer Time)`

This is filter that uses moment:
```
Vue.filter('formatDate', function(value) {
    if (value) {
        return moment(String(value)).format('YYYY-MM-DD')
    }
})
```

**Comment by charliekassel** [comment]
I think this is an issue for the moment library.
