### ISSUE TITLE
Highlighted dates: do from/to not work together?

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [charliekassel/vuejs-datepicker#62]
Hey there!

I'm trying to get a range of dates to highlight (for example 11/10/16 - 12/3/16).

However, when I try to do something like:

`highlighted: {
          from: new Date(2016, 10, 10),
          to: new Date(2016, 11, 3) // Highlight all dates up to specific date
        }`

All dates are highlighted. Is this functionality not supported or am I just doing something silly?

**Comment by charliekassel** [comment]
Hi @michaelfromtheoutfit - you are correct, thank you for spotting.

I've changed the behaviour in https://github.com/charliekassel/vuejs-datepicker/commit/d4563cf2bdfc85e079527f26462d772c985e65c3 and released in https://github.com/charliekassel/vuejs-datepicker/releases/tag/v0.5.0

I've updated the webpackbin demo accordingly

**Comment by charliekassel** [comment]
@bstelljes ^^

**Comment by michaelfromtheoutfit** [comment]
Thanks @charliekassel!
