### ISSUE TITLE
Remove width: auto on input when selected

### ISSUE THREAD

**Issue by jackbarham** [charliekassel/vuejs-datepicker#631]
Since updating the package, there have been some styling issues. When I click to open the dropdown, the input form forces a `width: auto`. I need to override it, so it remains 100%.

This what happens.

`<input name="" type="text" autocomplete="off" placeholder="Select or type to search" tabindex="0" class="multiselect__input" style="width: auto;">`

I've been through the docs and can't find anything. It was working before I did a package update.

Thank you.

**Comment by charliekassel** [comment]
There is nowhere in the code that does this.
Or adds tabindex... have you got the right package?

**Comment by jackbarham** [comment]
Sorry, no. I meant `vue-multiselect`
