### ISSUE TITLE
Dependency problem: flatmap-stream not available on npm

### ISSUE THREAD

**Issue by AndrejHafner** [charliekassel/vuejs-datepicker#638]
I've found the problem in the dependencies. The `flatmap-stream` package, one of the dependencies for vuejs-datepicker is missing from npm due to a security problem, thus I can't install and use the package. Can you please issue a fix? The security problem is reported [here](https://github.com/dominictarr/event-stream/issues/116).

**Comment by DanielRuf** [comment]
Can you remove the lockfile and install the dependencies again?

**Comment by AndrejHafner** [comment]
This resolved the issue.
Thank you. 👍
