### ISSUE TITLE
Define an input pattern if typeable

### ISSUE THREAD

**Issue by M01n34u** [charliekassel/vuejs-datepicker#639]
Hello, as it's not possible to play direcly with the input (afaik), how can it be possible to add a pattern on the input so when you type in it, slashes or dashes in the input are auto added. 

As it is now, you have to manually put a valid format, and it's not intuitive for everyone. 

Thank a lot in advance, sorry for my approximative English.

**Comment by ma-jahn** [comment]
Hi @M01n34u,

afaik there is no build-in support for formatters in combination with 'typeable'.
We simply added [cleave.js](https://nosir.github.io/cleave.js/) to format the text and it works just fine.

**Comment by fchabouis** [comment]
@ma-jahn but you still have to write dates in the MM/DD/YYYY format ? If I want to write in another format (DD/MM/YYYY for example), cleave.js won't help right ?

**Comment by ma-jahn** [comment]
In combination with `format` it works quite nicely.
In your case, setting the format as `DD/MM/YYYY` and using cleavejs with a configuration like this

`{
          delimiter: '/',
          date: true,
          datePattern: ['DD', 'MM', 'YYYY'],
        }`

should do the trick.
You can register cleave as a global directive, which i recommend if you'll be using it within multiple components or simply set it when your component has mounted like:

```
mounted() {
  let dateInput = this.$refs.yourDatePicker.$el
  new Cleave(dateInput, {
    delimiter: '/',
    date: true
    datePattern: ['DD', 'MM', 'YYYY'],
  });
}
`
``

**Comment by Sander-Toonen** [comment]
@M01n34u Try the following PR: https://github.com/charliekassel/vuejs-datepicker/pull/633
This will likely solve your issue.

**Comment by M01n34u** [comment]
Ok, I successfully tried that solutions. Thanks everyone.
