### ISSUE TITLE
A way to remove the date?

### ISSUE THREAD

**Issue by gkiely** [charliekassel/vuejs-datepicker#64]
Use case: User has selected a date, but want's to remove/clear the date from the input.

An X or cross icon that removes the date when clicked would be great. Happy to work on this if required.

**Comment by charliekassel** [comment]
I think this would be a good addition.

Happy to look at a PR for this.

**Comment by gkiely** [comment]
Basic version working here, happy to workshop the icon or code.
https://github.com/gkiely/vuejs-datepicker

**Comment by charliekassel** [comment]
Great thanks!

I don't think you want to nullify `currDate` as this should always be present and serves as a pointer for which month to open the datepicker on. You shouldn't then need to check for it's existence in `v-show` either.

I like the svg - but looks like there are some errors in your css? As a side note stylus does not require semi colons between property and values.

**Comment by kwnovi** [comment]
Any updates on this fixture ? I can't figure out how to use gkiely's workaround

**Comment by gkiely** [comment]
Hi @kwnovi sorry I haven't had a chance to look at @charliekassel feedback yet.
I'll take a look tomorrow, but looks like #81 might have fixed the issue.
