### ISSUE TITLE
Month Navigation must be corrected

### ISSUE THREAD

**Issue by velociraptor619** [charliekassel/vuejs-datepicker#643]
This is my object for disabling certain dates.
this. disablesDates = {
          from: new Date(2018,7,31),
          to: this.disableTo,
      };
I'm expecting the component to not let me navigate to July. But it does!

**Comment by lexcode** [comment]
Try this.

```
disablesDates = {
  to: new Date(2018,7,31)
}
```

**Comment by charliekassel** [comment]
Months in the Date constructor are zero based - 7 is August
