### ISSUE TITLE
receiving string value

### ISSUE THREAD

**Issue by zweifisch** [charliekassel/vuejs-datepicker#65]
currently only `Date` and `null` are allowed to be passed to value, but usually what I get are strings, which is quite inconvenient:

```
 let user = await this.$http.get('/settings/profile')
 let birthday = new Date(user.birthday)
 user.birthday = +birthday ? birthday : null  // make sure date is valid
 this.user = user
```

if string values are allowed, the above code could be reduced to

```
this.user = await this.$http.get('/settings/profile')
```

**Comment by charliekassel** [comment]
It would certainly make using the datepicker easier.
But the string would have to be parseable by the Date constructor, and nullified or throw if not valid.

Happy to look at a PR for this.

**Comment by charliekassel** [comment]
https://github.com/charliekassel/vuejs-datepicker/pull/69
