### ISSUE TITLE
Display week days?

### ISSUE THREAD

**Issue by Addvilz** [charliekassel/vuejs-datepicker#66]
Any chance of having a weekday displayed along with the week? ISO and simple.

**Comment by charliekassel** [comment]
Can you explain in more detail please?

**Comment by Addvilz** [comment]
[Take this library as example](http://www.daterangepicker.com/#config), there are options to show week numbering next to the week row. This is needed functinallity in a lot of business applications, where business folk work around weekly schedules etc.

**Comment by charliekassel** [comment]
Ok, this is not something I would personally use but I can see it's a useful feature, so happy to look at a PR for this.
