### ISSUE TITLE
Adding an input-class adds the class but doesn't apply its styles.

### ISSUE THREAD

**Issue by jedrekdomanski** [charliekassel/vuejs-datepicker#664]
Adding an input-class adds the class but doesn't apply its styles.
```
<datepicker v-model="invoice.creation_date" input-class="stroke-border"></datepicker>

<style>
  .stroke-border {
    border-style: solid;
    border-width: 2px;
  }
</style>
```
Why doesn't the Datepicker input have default borders appplied? It would look milion times better if it did have borders around it, otherwise it looks unintuitive.

**Comment by charliekassel** [comment]
The class is added but something else is over riding it in your situation. Try being more specific with your selector.
The datepicker is largely left unstyled so as not to dictate the look - you style it yourself to suit your app.

**Comment by ggaabe** [comment]
I'm running into a similar issue, except the class isn't even being added.

**Comment by morneluckybeard** [comment]
Sorry to Necro, this is likely cause of a css pre-processor and scoping, try adding your styles to a global file
