### ISSUE TITLE
inputClass prop is not assigned to the input el

### ISSUE THREAD

**Issue by CS76** [charliekassel/vuejs-datepicker#67]
`<datepicker inputClass="form-control" v-model="bookingDate"></datepicker>
`

It's assigning  a "NaN" value to the wrapper class... 

`<div class="datepicker" inputclass="NaN"><input type="text" readonly="readonly">....`

**Comment by charliekassel** [comment]
you need to make html attributes hyphenated:
```
<datepicker input-class="form-control" v-model="bookingDate"></datepicker>
```

**Comment by CS76** [comment]
Thank you (Y)

**Comment by CS76** [comment]
It would be really helpful if this is mentioned in the documentation. Thanks again for the help 👍

**Comment by charliekassel** [comment]
It's not specific to this component - it's the way Vue works.

**Comment by CS76** [comment]
I just started exploring Vue, good to know. Sorry about that.
