### ISSUE TITLE
How can i prevent multiple datepicker's from being opened at once.

### ISSUE THREAD

**Issue by riddhiparekh** [charliekassel/vuejs-datepicker#690]
I know this is the functionality shown in demo but i don't want to keep one datepicker open when other is clicked. I tried using @focusout.native="$refs.datepicker.closePopup" but does not works for me. Is there a solution to this?

**Comment by charliekassel** [comment]
You need to give each datepicker a distinct ref

**Comment by riddhiparekh** [comment]
Yes i have done that.
But when i call this method i get error closePopup is not a function.Also tried using $refs.datepicker[0].closePopup
