### ISSUE TITLE
why v-model values can't the date format be given

### ISSUE THREAD

**Issue by blackinitial** [charliekassel/vuejs-datepicker#692]
why v-model values cant the date format be given us?
i think that's better to implement it,

so my problem, my date input is dynamic and the values/v-model must be format `YYYY-MM-DD`.
how to handle many date formats like this?

**Comment by NerdGuruDevelopers** [comment]
While I agree with your issue (I experienced it myself...)... I found a work around by doing:

    // Do your HTML like this (NOTE using :value instead of v-model and @input to trigger the fix
    <vuejs-datepicker :value="myDate" placeholder="None" format="yyyy-MM-dd" @input="myDate = fixDate($event)"></vuejs-datepicker>

and then add a function to your vue to format it:

    fixDate(event){
   	return moment(event).format('YYYY-MM-DD');
    },

It's hacky, but it works.

**Comment by blackinitial** [comment]
Yeah, I solved my problem with moment before  POST the data.

But, look many property if hacked it.

I hope the date format implement on v-model.

**Comment by charliekassel** [comment]
Format is only for representing the date in the input. The model value is the date object.
