### ISSUE TITLE
Using bootstrap-styling causing readonly

### ISSUE THREAD

**Issue by samwilcock** [charliekassel/vuejs-datepicker#693]
I am using the datepicker which is fine and found that I can apply bootstrap styling to it using the bootstrap styling property.

However this then sets the input the be readonly, which doesn't actually stop you from entering the date in this case but it give it the readonly style that is applied to all other inputs. 

Why is this happening ? 

Below is my html for the datepicker. 

`<datepicker v-model="newCourse.startDate" bootstrap-styling="true"></datepicker>`

Any help would be great thanks. 

Sam

**Comment by dhrytsenko** [comment]
@samwilcock I have a same problem. Any updates? I can make this field `typeable` but then user will be able to input dates

**Comment by samwilcock** [comment]
@dhrytsenko I have no updates yet, I don't actually want the readonly property but I want the style that the bootstrap-styling property provides.

**Comment by letuhuu** [comment]
My temporary way: 
.vdp-datepicker .input-group .form-control[readonly] {
            background: none !important;
}

**Comment by Maartz** [comment]
Delete the quotes arround.
This is my HTML and it's working great.
`<datepicker
                                    id="bc-data-date_value"
                                    name="date_value"
                                    :class="{
                                        'valid': !$v.bcData.date_value.$invalid,
                                        'invalid': $v.bcData.date_value.$invalid
                                    }"
                                    :bootstrap-styling=true
                                    :full-month-name=true
                                    :value="convertDateTimeFromServer($v.bcData.date_value.$model)"
                                    :clear-button=true
                                    :monday-first=true
                                    :format="formatterDate"
                                    @selected="setDate"
                                >
                                </datepicker>`

**Comment by samwilcock** [comment]
@Maartz thanks i'll give it a go.
