### ISSUE TITLE
Possible to show the calendar inline without hiding the input?

### ISSUE THREAD

**Issue by superfreddialpad** [charliekassel/vuejs-datepicker#697]
This library is really great, but I'm wondering whether there's any combination of properties that might allow me to have the calendar picker open at all times while still showing the input? When I use `inline: true`, the input goes away. I've tried a few things but I feel like I'm missing something.

I'm working around it for now by mirroring the value of the hidden output, but it would be much nicer if I didn't have to do that.

Thanks!

**Comment by charliekassel** [comment]
Unfortunately not at this time
