### ISSUE TITLE
Cannot resolve module 'stylus-loader'

### ISSUE THREAD

**Issue by kkomelin** [charliekassel/vuejs-datepicker#7]
Hi there,

I have started a new project based on Vue Webpack Boilerplate: https://github.com/vuejs-templates/webpack

When I tried to import the Datepicker component to my project I received the following error:
> ERROR in ./~/vuejs-datepicker/src/components/Datepicker.vue
> Module not found: Error: Cannot resolve module 'stylus-loader' in ../node_modules/vuejs-datepicker/src/components
>  @ ./~/vuejs-datepicker/src/components/Datepicker.vue 2:0-172

In fact, the Datepicker project uses Stylus to style the component. 

Would it be reasonable to include **stylus** and **stylus-loader** as dependencies in the package.json of the Datepicker project?

**Comment by coderdiaz** [comment]
@kkomelin Yeah, is reasonable add this.

**Comment by kkomelin** [comment]
@coderdiaz The question is - should they be dev ("devDependencies") or production ("dependencies") dependencies?

**Comment by charliekassel** [comment]
stylus is already included in devDependencies.
I have added stylus-loader to the devDependencies in 8d3afb3

**Comment by kkomelin** [comment]
Thanks.
