### ISSUE TITLE
A prop to format return value

### ISSUE THREAD

**Issue by aswinkp** [charliekassel/vuejs-datepicker#70]
Currently "2015-01-12T18:30:00.000Z" is the default format that is returned by the datepicker. `format` prop  which is available now only changes the format in the input box. Would love to see the feature in the future.

**Comment by mailnike** [comment]
+1

**Comment by charliekassel** [comment]
A date object is returned. You can format this however you like.

The date formatting for the input display within the library is very fragile and no where near as robust as strong mature library such as moment.js.
I do not want to output a string from this lib and rely on the internal formatDate method.
