### ISSUE TITLE
Application of 8 years ago today on disabledDates: {  to:

### ISSUE THREAD

**Issue by chrisj-skinner** [charliekassel/vuejs-datepicker#714]
I want to disable all date previous of todays date - 8 years.

I have the code that works this date out. However when returning this value to the `disabledDates: { to:` function. I get a `TypeError: date.getMonth is not a function` coming from vuejs-datepicker.esm.js?fa33:91

My code
```
data() {
  return {
    state: {
      disabledDates: {
        to: this.setToDate(),
      }
    }
  }
},
methods: {
    setToDate() {
      const newDate = new Date()
      newDate.setTime(newDate.valueOf() - 8 * 365 * 24 * 60 * 60 * 1000)
      return newDate.toString()
    }
  }
```

Any ideas for a work around on this?
Thanks

**Comment by charliekassel** [comment]
You are giving it a string. It should be a date object
