### ISSUE TITLE
Enhancement: Add moment.js

### ISSUE THREAD

**Issue by coderdiaz** [charliekassel/vuejs-datepicker#72]
The **moment.js** library could be implemented for formatting dates and time zones. http://momentjs.com/.

What do you think?

**Comment by charliekassel** [comment]
Yeah it's definitely something I've thought about.

**Comment by coderdiaz** [comment]
I thought so too hahaha Are your working on it?

**Comment by charliekassel** [comment]
Unfortunately, not right now.
The formatDate method is particularly fragile and I've considered extracting this out to it's own library or using moment.js but recently I've not been working much on front end so this component has been at the back of my mind.
It's quite well embedded in my work projects so am hesitant to introduce breaking changes.

**Comment by coderdiaz** [comment]
Oh, ok. Thanks @charliekassel 👍
