### ISSUE TITLE
Can't use locales

### ISSUE THREAD

**Issue by oherik** [charliekassel/vuejs-datepicker#734]
Starting today I can no longer import locales. The following works in 1.5.4:

```js
import { en, sv } from "vuejs-datepicker/dist/locale";
```
Using 1.6.1 Vue provides the following error as output:
```
Error: Can't resolve 'vuejs-datepicker/dist/locale' in '[my Vue component]'
```
This makes sense since I can't find that file in my /node_modules folder. Did I miss something when upgrading to 1.6.1?

**Comment by tomcoonen** [comment]
@oherik beat me to reporting the issue, but I'm running into the same thing.
It seems de `index.js` file in the `dist/locale` folder is gone.

**Comment by Scapal** [comment]
I have to use this to make it work as the `index.js` disappeared from the dist/locale

```javascript
import {en} from 'vuejs-datepicker/dist/locale/translations/en'
import {fr} from 'vuejs-datepicker/dist/locale/translations/fr'
import {nl} from 'vuejs-datepicker/dist/locale/translations/nl'
```

**Comment by charliekassel** [comment]
Good spot guys, thanks - does 1.6.2 work for you?

**Comment by oherik** [comment]
> 
> 
> Good spot guys, thanks - does 1.6.2 work for you?

Yep, it seems to be working fine now. Thanks!

**Comment by marko-mlinarevic** [comment]
still not working for me
