### ISSUE TITLE
Pick range of dates

### ISSUE THREAD

**Issue by golopot** [charliekassel/vuejs-datepicker#748]
I need a component that picks an interval of dates instead of two separate dates. Like this:

![Screenshot from 2019-07-18 15-42-30](https://user-images.githubusercontent.com/16285118/61439045-5f7ef600-a973-11e9-9d1d-c646e0613105.png)

http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

**Comment by charliekassel** [comment]
Sorry, that’s not this one.
