### ISSUE TITLE
Q: Is it possible to open the datepicker in years view, before months, and days?

### ISSUE THREAD

**Issue by 0dp** [charliekassel/vuejs-datepicker#755]
Hi There,

Just wanted to know if it is possible to open the datepicker in years view, before months, and days?

Let's say you have to type in your birthday:

1. Select Year
1. Select Month
1. Select day

Asking for a friend 😜

**Comment by MrWook** [comment]
initial-view="year"

**Comment by 0dp** [comment]
I saw this option but found the description a bit cryptic.
Maybe that is just me?

Thanks for input @MrWook
