### ISSUE TITLE
Request to take over the project

### ISSUE THREAD

**Issue by MrWook** [charliekassel/vuejs-datepicker#764]
Unfortunately I didn't found a way to contact you so I will try it over an issue. 

The company I work for is trying to walk on a open source path and want to publish some of our packages.
One of them is a fork from your vuejs-datepicker. Therefor and because you don't maintain this project anymore we would like to take over this project. 
Please contact us if you have interest and we can talk about the future steps:
 info@sumcumo.com

Here are the changes that we made:

**Bug fixes:**
- use umd file format for languages
- resolve wrong date model for typeable
- remove not used event listener
- resolve issues with incorrect time
- highlight dates without time

**Features:**
- adjust coding style to company styles
- add standard-version
- add Auto direction detecting
- use vuepress for documentation and demo site
- add fixed picker position
- add footer slot
- add show-header prop to hide the header if necessary
- add before dateInput
- add new languages
- add tabIndex
- use kebab-case event names (Breaking-change)
- update dependencies
- use disable utils
- extract css in own file (Breaking-change)
- customize picker header icons

**Comment by charliekassel** [comment]
I would potentially look at individual PR for features but not wholesale changes and I'm not interested in handing this project over to anyone.
I'm glad you've found my work and the work of the other contributors helpful, but I'll pass on that offer thank you.
