### ISSUE TITLE
How to config datepicker only allow choose one month in a year?

### ISSUE THREAD

**Issue by dieuit07** [charliekassel/vuejs-datepicker#803]
Hi guys, the months should run from 1 to 12 and the user choose 1 month

**Comment by thuyduongbka** [comment]
![image](https://user-images.githubusercontent.com/36602468/73926551-66b32480-4902-11ea-868e-c3f6150548d7.png)

**Comment by dieuit07** [comment]
Thank you for your quick help :dancing_men: 

The document may need up to date. I read the "[Usage](https://github.com/charliekassel/vuejs-datepicker#usage)" and "[Props](https://github.com/charliekassel/vuejs-datepicker#available-props)"

the code I used:

`<datepicker format="MM/yyyy"></datepicker>`

the format doesn't apply, event I try to put in the function :format="func", still can not get it work

**Comment by thuyduongbka** [comment]
> Thank you for your quick help 👯‍♂
> 
> The document may need up to date. I read the "[Usage](https://github.com/charliekassel/vuejs-datepicker#usage)" and "[Props](https://github.com/charliekassel/vuejs-datepicker#available-props)"
> 
> the code I used:
> 
> `<datepicker format="MM/yyyy"></datepicker>`
> 
> the format doesn't apply, event I try to put in the function :format="func", still can not get it work

I did it, I followed the instructions.
Can you show me the code?, I can help you.

**Comment by dieuit07** [comment]
It's ok, I think it should work. But now I have no time to try for it. I have already used the other library.
Thanks in advance :)
