### ISSUE TITLE
The worst datepicker ever

### ISSUE THREAD

**Issue by sdaudishvili** [charliekassel/vuejs-datepicker#814]
full of bugs, format prop does not work as expected  - reverses month and day i don't know why. Passing function param does not work as well. Event listeners does not work as expected - 'closed' event works only if you close by selecting date or clicking on the input box, it does not triggers when clicked outside the Date picker box. 'opened' event never triggers!!!

**Comment by charliekassel** [comment]
Beautiful! Comments like this make contributing to open source software so satisfying. 
I'm not asking you to use this. Go forth and write your own.

**Comment by sebenik** [comment]
@sdaudishvili I can understand your frustration but your comment is out of line. Have respect to work people are willing to put in to open source projects (most of them in their free time) and actively contribute where you can.

This said, @charliekassel we would all appreciate you would accept this help from numerous people who also care about this project and are submitting pull requests that would address some quite severe bugs.

If life circumstances are preventing you from maintaining this project we would all respect if you could grant maintenance privileges to other contributors that (by reading the comments) already contacted you about it.

Wish you well and thanks for all the work you put into this.
