### ISSUE TITLE
Disable the picker entirely

### ISSUE THREAD

**Issue by garrettheaver** [charliekassel/vuejs-datepicker#83]
Hi, I can't currently see any way to disable the picker entirely. I can disabled dates but theres no way to stop the user from even being able to open the calendar window?

**Comment by charliekassel** [comment]
No there is not a method for this.
Happy to review a PR is this is a useful feature for you?

**Comment by pflirae** [comment]
Yes, it is usefull, sepecially when you have a form where a user has to change ony some values, but not the date.
