### ISSUE TITLE
Change Datepicker popup start date

### ISSUE THREAD

**Issue by rlambertsen** [charliekassel/vuejs-datepicker#85]
So when you click the Datepicker input the calendar pops out. I want to change what month is shown before its opened (on page load), but not have a date in the input through the `:value`. 

Say I want to show `May 1990` but still have my placeholder text showing. 

Also changing the input from readonly would also be helpful and striping the styles so its more open to other frameworks.
I can make a pull request with these changes if needed. Just some ideas is all.

**Comment by charliekassel** [comment]
I think this is a potentially useful feature.
Please yes, submit a PR for this.
