### ISSUE TITLE
Is there any way to style the input box inside the wrapper div?

### ISSUE THREAD

**Issue by divyanthj** [charliekassel/vuejs-datepicker#86]
I tried doing 

```
div.wrapper-class input{
  border-style:solid !important;
  border-color:#5d5d5d !important;
  border-width:1px !important;
}
```
But it won't work. I don't like the way the borders of the input box look. I'm using this component inside another `.vue` component.

**Comment by coderdiaz** [comment]
Are you using `scoped` in the style tag?

**Comment by SkyDog** [comment]
Have you checked the documentation? Under Props: 
input-class 	String 		css class applied to the input el

**Comment by divyanthj** [comment]
Adding an input-class adds the class but doesn't apply its styles.

**Comment by coderdiaz** [comment]
@divyanthj Your welcome 👍
