### ISSUE TITLE
Default language to Vue.config.lang if available

### ISSUE THREAD

**Issue by Naouak** [charliekassel/vuejs-datepicker#96]
It's annoying to pass language each time you try to use the date picker. 

Vue-i18n use a config var to fetch the language currently used by the user. 

Can you default the language to the config value if it's in the config ?

**Comment by javisperez** [comment]
In case it helps, you can create a wrapper component that pass the language automatically and uses the same props as the date-picker component, so, is just like a wrapper for the language... I dont know, is just an idea of how i would do it. Actually i just set the language as a computed that reads it from Vue-translate and pass it to the datepicker :)

**Comment by Naouak** [comment]
I'm currently passing a computed to each date picker. I'm trying to avoid thinking about translations when writing code. 

I may do the wrapper component but it doesn't seem optimal.

Is there any standard for i18n in vue.js for interop between components?

**Comment by charliekassel** [comment]
Yes, I see no reason why the lang prop could not be a computed property from the parent.

**Comment by wallacemaxters** [comment]
I solved this problem rewriting the value of `props.language.default`.

See:

```
import Datepicker from 'vuejs-datepicker';
import {ptBR} from 'vuejs-datepicker/dist/locale';

Datepicker.props.language.default = () => ptBR;
```
