### ISSUE TITLE
v-model does not support element type: DIV

### ISSUE THREAD

**Issue by IgorLeonenko** [charliekassel/vuejs-datepicker#97]
When I try to use v-model like in example ```<datepicker v-model="state.date" name="uniquename"></datepicker>```, I'm getting error in console **v-model does not support element type: DIV**
Vue 1.0.28, Datepicker 0.6.2

**Comment by DannyFeliz** [comment]
I'm having the same issue too

**Comment by charliekassel** [comment]
I've added an example in the demo - closing as i can't replicate your issue.
