### ISSUE TITLE
Field Validations

### ISSUE THREAD

**Issue by raphcadiz** [charliekassel/vuejs-datepicker#99]
I'm using vee-validate (http://vee-validate.logaretm.com/) for my field validation but I'm not able to use it on date picker, vee-validate is used like this

`<input v-validate data-vv-rules="required" data-vv-as="postal code" :class="{'form-control': true, 'form-control-danger': errors.has('date_from') }" name="date_from" type="text" placeholder="Enter Pick Date.." v-model="date_from">`

The problem is when I used it on datepicker <datepicker v-validate data-vv-rules="required"></datepicker> it does not apply on the input field, it only goes the div wrapper of the input.

It could a nice feature if we are able to use some props like this on vuejs-datepicker

**Comment by charliekassel** [comment]
I would suggest you validate the data in a wrapper component.
I don't want to hard tie my component to any specific other library

**Comment by renatoneri** [comment]
To work just add $emit on watch value. Like this:

```
watch: {
    value (value) {
      this.setValue(value)
      this.$emit('input', value) //only this line
    }
  },
```
